chromium-toolchain: fix multiple issues
:Release Notes:
There was no SRC_URI, so there was nothing to install, not even
files referenced from LIC_FILES_CHKSUM.

The files were installed in do_install, but not packaged anywhere.
Packaging the files fixes installed-vs-shipped QA issue, but then
there are many missing dependencies, already-stripped QA issues and
more importantly wrong architecture (as these are prebuilt x86_64
files which doesn't make sense to include e.g. in aarch64 packages).

Leave only native build, include webruntime-common.inc to get some
SRC_URI, drop useless inherits (which didn't do anything without
SRC_URI and now they are inheritted through webruntime-common.inc)

:Detailed Notes:
Fixes:

do_patch:
http://gecko.lge.com:8000/Errors/Details/566149
ERROR: Target directory 'TOPDIR/BUILD/work/qemux86_64-webos-linux/chromium-toolchain/94.0.4606.128-26-r0/git/src/v8' not found, patchdir 'src/v8' is incorrect in patch file '0001-Fix-build-with-gcc-13.patch'

do_populate_lic:
http://gecko.lge.com:8000/Errors/Details/566361
ERROR: QA Issue: chromium-toolchain: LIC_FILES_CHKSUM points to an invalid file: TOPDIR/BUILD/work/qemux86_64-webos-linux/chromium-toolchain/94.0.4606.128-28-r0/git/src/LICENSE [license-checksum]
ERROR: QA Issue: chromium-toolchain: LIC_FILES_CHKSUM points to an invalid file: TOPDIR/BUILD/work/qemux86_64-webos-linux/chromium-toolchain/94.0.4606.128-28-r0/git/oss-pkg-info.yaml [license-checksum]

do_install:
http://gecko.lge.com:8000/Errors/Details/566362
cp: cannot stat 'TOPDIR/BUILD/work/qemux86_64-webos-linux/chromium-toolchain/94.0.4606.128-28-r0/git/src/third_party/llvm-build/Release+Asserts/bin/*': No such file or directory

do_package [installed-vs-shipped]:
http://gecko.lge.com:8000/Errors/Details/566364
ERROR: QA Issue: chromium-toolchain: Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/clang
  /usr/lib/clang/14.0.0
  /usr/lib/clang/14.0.0/include
  /usr/lib/clang/14.0.0/include/adxintrin.h
  ....
  /usr/lib/clang/14.0.0/include/openmp_wrappers/new
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
chromium-toolchain: 192 installed and not shipped files. [installed-vs-shipped]

do_package_qa:
http://gecko.lge.com:8000/Errors/Details/566366
ERROR: QA Issue: /usr/bin/llvm-objcopy contained in package chromium-toolchain requires libz.so.1(ZLIB_1.2.0)(64bit), but no providers found in RDEPENDS:chromium-toolchain? [file-rdeps]
ERROR: QA Issue: /usr/bin/llvm-undname contained in package chromium-toolchain requires libz.so.1()(64bit), but no providers found in RDEPENDS:chromium-toolchain? [file-rdeps]
ERROR: QA Issue: /usr/bin/lld contained in package chromium-toolchain requires libxml2.so.2(LIBXML2_2.4.30)(64bit), but no providers found in RDEPENDS:chromium-toolchain? [file-rdeps]
ERROR: QA Issue: /usr/bin/lld contained in package chromium-toolchain requires libxml2.so.2(LIBXML2_2.6.0)(64bit), but no providers found in RDEPENDS:chromium-toolchain? [file-rdeps]
ERROR: QA Issue: /usr/bin/lld contained in package chromium-toolchain requires libxml2.so.2()(64bit), but no providers found in RDEPENDS:chromium-toolchain? [file-rdeps]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-12446] CCC: Various build fixes
[WRP-12469] Bitbake world issues 2023-04-01

Cherry-picked-from-commit: 6f9f47fd00b71c09a049356fca9fddce7a487db4
Cherry-picked-from-branch: