webos: pmlogdaemon=r12 (ignore implicit-function-declaration issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/821710
pmlogdaemon/3.1.0-14/git/src/main.c:685:14: error: implicit declaration of function 'open'; did you mean 'popen'? [-Wimplicit-function-declaration]
pmlogdaemon/3.1.0-14/git/src/main.c:698:18: error: implicit declaration of function 'fcntl' [-Wimplicit-function-declaration]
pmlogdaemon/3.1.0-14/git/src/main.c:2484:10: error: implicit declaration of function 'inotify_init' [-Wimplicit-function-declaration]
pmlogdaemon/3.1.0-14/git/src/main.c:2492:10: error: implicit declaration of function 'inotify_add_watch'; did you mean 'g_io_add_watch'? [-Wimplicit-function-declaration]
pmlogdaemon/3.1.0-14/git/src/main.c:2532:5: error: implicit declaration of function 'inotify_rm_watch' [-Wimplicit-function-declaration]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19569] CCC: pmlogdaemon=r12 (ignore implicit-function-declaration issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: 1da5a3add5eab232dbfb71da6199c1cb3e838ba2
Cherry-picked-from-branch: