luna-service2: CMakeLists.txt: replace -std=c++11 with -std=c++14
:Release Notes:
It was commented out in root CMakeLists.txt, but some other parts were still selecting rather
old c++11 which isn't compatible with googletest currently in mickledore.

:Detailed Notes:
With googletest 1.13.0 from:
https://git.openembedded.org/meta-openembedded/commit/?id=46266e59ff36b38f46a67573528cee658960c764
it fails to build with:
http://gecko.lge.com:8000/Errors/Details/561643

FAILED: src/libluna-service2++/test/CMakeFiles/test_error.dir/test_error.cpp.o
TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++  -ITOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/git/src/libluna-service2 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/git/include/public -ITOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/git/include/private -ITOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/git/include/private/tests -I/usr/src/gtest/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/git/include/public/luna-service2++ -isystem TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/recipe-sysroot/usr/src/gtest/include -isystem TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/recipe-sysroot/usr/src/gtest -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/git=/usr/src/debug/luna-service2/3.21.2-32-r30  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/git=/usr/src/debug/luna-service2/3.21.2-32-r30  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/build=/usr/src/debug/luna-service2/3.21.2-32-r30  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/build=/usr/src/debug/luna-service2/3.21.2-32-r30  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/recipe-sysroot-native=  -fvisibility-inlines-hidden  -DWEBOS_TARGET_MACHINE_IMPL_EMULATOR -DTARGET_EMULATOR -include TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/build/Configured/webospaths.h -UNDEBUG -DUSE_PMLOG_DECLARATION -DMEMCHECK -DLSHANDLE_CHECK -Wall -Werror=switch -DSECURITY_COMPATIBILITY -Wl,--no-undefined -Wall -std=c++11 -Wl,-LTOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/recipe-sysroot/usr/lib -Wl,-lpbnjson_cpp -Wl,-lpbnjson_c -DNDEBUG -DLS_SCHEMA_ROOT=\"TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/git/files/schema\" -MD -MT src/libluna-service2++/test/CMakeFiles/test_error.dir/test_error.cpp.o -MF src/libluna-service2++/test/CMakeFiles/test_error.dir/test_error.cpp.o.d -o src/libluna-service2++/test/CMakeFiles/test_error.dir/test_error.cpp.o -c TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/git/src/libluna-service2++/test/test_error.cpp
In file included from TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/recipe-sysroot/usr/include/gtest/gtest-message.h:57,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/recipe-sysroot/usr/include/gtest/gtest-assertion-result.h:46,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/recipe-sysroot/usr/include/gtest/gtest.h:64,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/git/src/libluna-service2++/test/test_error.cpp:17:
TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-service2/3.21.2-32-r30/recipe-sysroot/usr/include/gtest/internal/gtest-port.h:270:2: error: #error C++ versions less than C++14 are not supported.
  270 | #error C++ versions less than C++14 are not supported.
      |  ^~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-412] Create GPVB with Yocto 4.2 Mickledore
[WRP-12233] googletest-1.13.0 no longer supports -std=c++11 and older
[WRP-12449] CCC: Use C++ 2014 to support googletest-1.13.0

Cherry-picked-from-commit: 921a4a8adc495d0d1f272803b7845ba2e43cdf82
Cherry-picked-from-branch: