ffmpeg: drop 2.3.6 version and use 4.2.1 from oe-core
gstreamer-1.0-libav isn't compatible with this ancient version

ERROR: gstreamer1.0-libav-1.16.1-r0 do_configure: meson failed
ERROR: gstreamer1.0-libav-1.16.1-r0 do_configure: Execution of '/jenkins/mjansa/build-ros/webos-crystal-master/tmp-glibc/work/qemux86-webos-linux/gstreamer1.0-libav/1.16.1-r0/temp/run.do_configure.67464' failed with exit code 1:
The Meson build system
Version: 0.52.1
Source dir: /jenkins/mjansa/build-ros/webos-crystal-master/tmp-glibc/work/qemux86-webos-linux/gstreamer1.0-libav/1.16.1-r0/gst-libav-1.16.1
Build dir: /jenkins/mjansa/build-ros/webos-crystal-master/tmp-glibc/work/qemux86-webos-linux/gstreamer1.0-libav/1.16.1-r0/build
Build type: cross build
Project name: gst-libav
Project version: 1.16.1
C compiler for the build machine: gcc (gcc 7.4.0 "gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
C linker for the build machine: GNU ld.bfd 2.30
C++ compiler for the build machine: g++ (gcc 7.4.0 "g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
C++ linker for the build machine: GNU ld.bfd 2.30
C compiler for the host machine: i686-webos-linux-gcc -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type --sysroot=/jenkins/mjansa/build-ros/webos-crystal-master/tmp-glibc/work/qemux86-webos-linux/gstreamer1.0-libav/1.16.1-r0/recipe-sysroot (gcc 9.2.0 "i686-webos-linux-gcc (GCC) 9.2.0")
C linker for the host machine: GNU ld.gold 2.33.1.20191208
C++ compiler for the host machine: i686-webos-linux-g++ -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type --sysroot=/jenkins/mjansa/build-ros/webos-crystal-master/tmp-glibc/work/qemux86-webos-linux/gstreamer1.0-libav/1.16.1-r0/recipe-sysroot (gcc 9.2.0 "i686-webos-linux-g++ (GCC) 9.2.0")
C++ linker for the host machine: GNU ld.gold 2.33.1.20191208
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86
Host machine cpu: i686
Target machine cpu family: x86
Target machine cpu: i686
Found pkg-config: /jenkins/mjansa/build-ros/webos-crystal-master/tmp-glibc/work/qemux86-webos-linux/gstreamer1.0-libav/1.16.1-r0/recipe-sysroot-native/usr/bin/pkg-config (0.29.2)
Found CMake: NO
Run-time dependency libavfilter found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libavfilter

meson.build:18:0: ERROR: Subproject directory not found and FFmpeg.wrap file not found

[PLAT-115145] CCC: Upgrade to Yocto 3.1 Dunfell

Change-Id: Ibbcb67cc006cf9e9305bd6e786cf5dafffb3bbc6