com.webos.service.unifiedsearch: fix FILES and LIC_FILES_CHKSUM
:Release Notes:
Use LICENSE file from the repository, it was there since the
submissions/1.
Use libdir in FILES, because with multilib CMake correctly installs
it in /usr/lib64, not /usr/lib.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/574298

ERROR: QA Issue: com.webos.service.unifiedsearch: Files/directories were installed but not shipped in any package:
  /usr/lib64/plugins/unifiedsearch/libmediaplugin.so
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
com.webos.service.unifiedsearch: 1 installed and not shipped files. [installed-vs-shipped]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-12446] CCC: Various build fixes
[WRP-12469] Bitbake world issues 2023-04-01

Cherry-picked-from-commit: b4f1f1e4a935c528bfe7f8cee39f8b7f2bd87b00
Cherry-picked-from-branch: