webruntime=r59.* (Fix build with python-3.11)
:Release Notes:
Remove usage of 'U' mode bit for opening files in python

The 'U' mode bit is removed in python 3.11. It has been
deprecated for a long time. The 'U' mode bit has no effect
so this change doesn't change any behavior.

See https://docs.python.org/3.11/whatsnew/3.11.html#changes-in-the-python-api

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/475737

FAILED: gen/extensions/extensions_resources_grd_grit.d.stamp gen/extensions/grit/extensions_resources.h gen/extensions/extensions_resources.pak gen/extensions/extensions_resources.pak.info
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime/94.0.4606.128-9-r58.1/recipe-sysroot-native/usr/bin/python3-native/python3 ../../git/src/tools/grit/grit.py -i ../../git/src/extensions/extensions_resources.grd build -o gen/extensions --depdir . --depfile gen/extensions/extensions_resources_grd_grit.d --write-only-new=1 --depend-on-stamp -E root_gen_dir=gen -E root_src_dir=../../git/src/ -D SHARED_INTERMEDIATE_DIR=gen -D scale_factors=2x -D _chromium -E CHROMIUM_BUILD=chromium -D desktop_linux -D toolkit_views -D use_aura -D use_nss_certs -D use_ozone -t linux2 -f gen/tools/gritsettings/default_resource_ids --assert-file-list obj/extensions/extensions_resources_grd_expected_outputs.txt
Traceback (most recent call last):
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime/94.0.4606.128-9-r58.1/build/Release/../../git/src/tools/grit/grit.py", line 29, in <module>
    sys.exit(grit.grit_runner.Main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime/94.0.4606.128-9-r58.1/git/src/tools/grit/grit/grit_runner.py", line 314, in Main
    return toolobject.Run(options, args[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime/94.0.4606.128-9-r58.1/git/src/tools/grit/grit/tool/build.py", line 254, in Run
    self.res = grd_reader.Parse(opts.input,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime/94.0.4606.128-9-r58.1/git/src/tools/grit/grit/grd_reader.py", line 231, in Parse
    handler.root.AssignFirstIds(filename_or_stream, defines)
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime/94.0.4606.128-9-r58.1/git/src/tools/grit/grit/node/misc.py", line 611, in AssignFirstIds
    src_root_dir, first_ids = _ReadFirstIdsFromFile(first_ids_filename,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime/94.0.4606.128-9-r58.1/git/src/tools/grit/grit/node/misc.py", line 67, in _ReadFirstIdsFromFile
    first_ids_dict = eval(util.ReadFile(filename, 'utf-8'))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime/94.0.4606.128-9-r58.1/git/src/tools/grit/grit/util.py", line 214, in ReadFile
    with io.open(filename, mode, encoding=encoding) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-4709] Create GPVB with Yocto 4.1 Langdale
[WRO-14425] CCC: Various build fixes

Change-Id: I64b97e56e45122a008287d538f963229638aaf89