com.webos.service.camera=r5 (fix build with gcc-13)
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/529518

FAILED: CMakeFiles/v4l2-camera-plugin.dir/src/hal/v4l2/usrptr_handle.cpp.o
TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++ -Dv4l2_camera_plugin_EXPORTS -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/files -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/files/sysbus -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/files/systemd -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/service -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/service/notifier -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/service/notifier/pdm -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/service/solutions -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/hal -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/hal/v4l2 -I/usr/src/gtest/include -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git=/usr/src/debug/com.webos.service.camera/1.0.0-32-r4  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git=/usr/src/debug/com.webos.service.camera/1.0.0-32-r4  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/build=/usr/src/debug/com.webos.service.camera/1.0.0-32-r4  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/build=/usr/src/debug/com.webos.service.camera/1.0.0-32-r4  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot-native=  -fvisibility-inlines-hidden  -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot/usr/lib/glib-2.0/include -Wall -funwind-tables -Wall -rdynamic -std=c++14 -g -lrt -Werror=return-type -Wno-stringop-truncation -Wno-stringop-overflow -DFEATURE_LG_AUTOCONTRAST -DFEATURE_LG_DUMMY -g -fPIC -MD -MT CMakeFiles/v4l2-camera-plugin.dir/src/hal/v4l2/usrptr_handle.cpp.o -MF CMakeFiles/v4l2-camera-plugin.dir/src/hal/v4l2/usrptr_handle.cpp.o.d -o CMakeFiles/v4l2-camera-plugin.dir/src/hal/v4l2/usrptr_handle.cpp.o -c TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/hal/v4l2/usrptr_handle.cpp
TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/hal/v4l2/usrptr_handle.cpp: In function 'usrptr_handle_t* create_usrptr_handle(stream_format_t, int)':
TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/hal/v4l2/usrptr_handle.cpp:15:33: error: 'calloc' was not declared in this scope
   15 |     husrptr = (usrptr_handle_t*)calloc(1, sizeof(usrptr_handle_t));
      |                                 ^~~~~~
TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/hal/v4l2/usrptr_handle.cpp:4:1: note: 'calloc' is defined in header '<cstdlib>'; did you forget to '#include <cstdlib>'?
    3 | #include "camera_hal_types.h" // HAL_LOG_INFO
  +++ |+#include <cstdlib>
    4 |

TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++  -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/files -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/files/sysbus -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/files/systemd -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/service -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/service/notifier -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/service/notifier/pdm -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/service/solutions -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/hal -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/hal/v4l2 -I/usr/src/gtest/include -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git=/usr/src/debug/com.webos.service.camera/1.0.0-32-r4  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git=/usr/src/debug/com.webos.service.camera/1.0.0-32-r4  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/build=/usr/src/debug/com.webos.service.camera/1.0.0-32-r4  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/build=/usr/src/debug/com.webos.service.camera/1.0.0-32-r4  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot-native=  -fvisibility-inlines-hidden  -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/recipe-sysroot/usr/lib/glib-2.0/include -Wall -funwind-tables -Wall -rdynamic -std=c++14 -g -lrt -Werror=return-type -Wno-stringop-truncation -Wno-stringop-overflow -DFEATURE_LG_AUTOCONTRAST -DFEATURE_LG_DUMMY -g -MD -MT CMakeFiles/com.webos.service.camera2.dir/src/service/solutions/camera_solution_async.cpp.o -MF CMakeFiles/com.webos.service.camera2.dir/src/service/solutions/camera_solution_async.cpp.o.d -o CMakeFiles/com.webos.service.camera2.dir/src/service/solutions/camera_solution_async.cpp.o -c TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/service/solutions/camera_solution_async.cpp
TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/service/solutions/camera_solution_async.cpp: In member function 'void CameraSolutionAsync::startThread()':
TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.camera/1.0.0-32-r4/git/src/service/solutions/camera_solution_async.cpp:173:40: error: expected unqualified-id before '&' token
  173 |         catch (const std::system_error &e)
      |                                        ^

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-8053] CCC: Various build fixes

Cherry-picked-from-commit: 5b69340ce93e243fb8dbb37cb13ad44569593bc2
Cherry-picked-from-branch: