g-media-pipeline=r5 (drop patch which doesn't apply correctly anymore)
:Release Notes:
Since submissions/21 there is different change in master branch which
causes this patch to apply with patch-fuzz ERROR.

:Detailed Notes:
Please note that the change which was merged into g-media-pipeline sets
-DPLATFORM_RASPBERRYPI4 instead of -DPLATFORM_RASPBERRYPI3 added by this
.patch file, but nothing seems to be using these definitions, so it doesn't
matter. Also the change in master sets -DMAX_NUM_DISPLAY=1 which is probably
wrong (but it's the same as what .patch was using).

Fixes:
ERROR: g-media-pipeline-1.0.0-21-r4 do_patch: Fuzz detected:

Applying patch 0001-Add-raspberrypi4-and-raspberrypi4-64-targets.patch
patching file CMakeLists.txt
Hunk #1 succeeded at 34 with fuzz 1.

The context lines in the patches can be updated with devtool:

    devtool modify g-media-pipeline
    devtool finish --force-patch-refresh g-media-pipeline <layer_path>
Don't forget to review changes done by devtool!

ERROR: g-media-pipeline-1.0.0-21-r4 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-47016] CCC: linux-raspberrypi=v4.19.88

Change-Id: If8d7da9f92739d073c3004ec378c5584937fdad7