com.webos.service.tts=r7 (use -std=c++14)
:Release Notes:
abseil-cpp was upgraded in:
https://git.openembedded.org/meta-openembedded/commit/?id=3ab22400d180529d2ad9d18a77c1d2863c3d838e
and it requires c++14:
https://github.com/abseil/abseil-cpp/commit/97ab3dcfd6490434202e4ab00b2eaba9449e42a1

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/475738

FAILED: CMakeFiles/tts-service.dirTOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/google/api/annotations.grpc.pb.cc.o
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ -DNOT_SUPPORT_GFLAGS -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/git/src/engines/tts/google -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/git/src/engines/audio/pulse -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/git/src/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/git/src/utils -mcpu=cortex-a72 -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/git=/usr/src/debug/com.webos.service.tts/1.0.0-22-r6  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/git=/usr/src/debug/com.webos.service.tts/1.0.0-22-r6  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/build=/usr/src/debug/com.webos.service.tts/1.0.0-22-r6  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/build=/usr/src/debug/com.webos.service.tts/1.0.0-22-r6  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot-native=  -fvisibility-inlines-hidden  -DUSE_PMLOG_DECLARATION -std=c++11 -Wall -DNDEBUG -MD -MT CMakeFiles/tts-service.dirTOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/google/api/annotations.grpc.pb.cc.o -MF CMakeFiles/tts-service.dirTOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/google/api/annotations.grpc.pb.cc.o.d -o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/google/api/annotations.grpc.pb.cc.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/google/api/annotations.grpc.pb.cc
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/absl/base/config.h:86,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/absl/base/const_init.h:25,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/absl/synchronization/mutex.h:65,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/grpcpp/impl/codegen/sync.h:32,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/grpcpp/impl/codegen/client_context.h:55,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/grpcpp/impl/codegen/call_op_set.h:33,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/grpcpp/impl/codegen/server_callback.h:28,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/grpcpp/impl/codegen/server_callback_handlers.h:25,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/grpcpp/generic/async_generic_service.h:24,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/google/api/annotations.grpc.pb.h:25,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/google/api/annotations.grpc.pb.cc:6:
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.tts/1.0.0-22-r6/recipe-sysroot/usr/include/absl/base/policy_checks.h:79:2: error: #error "C++ versions less than C++14 are not supported."
   79 | #error "C++ versions less than C++14 are not supported."
      |  ^~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-4709] Create GPVB with Yocto 4.1 Langdale
[WRO-14425] CCC: Various build fixes

Change-Id: Ida86d30158986bb48c9bfc64f5af97bd3b411942