meta-webos-iot: define LAYERDEPENDS
:Release Notes:
Define LAYERDEPENDS to fix layer parsing with yocto-check-layer tool.

:Detailed Notes:
Fixes erros like:
INFO: ======================================================================
INFO: ERROR: test_parse (common.CommonCheckLayer)
INFO: ----------------------------------------------------------------------
INFO: Traceback (most recent call last):
  File "/OE/openembedded-core/scripts/lib/checklayer/cases/common.py", line 30, in test_parse
    check_command('Layer %s failed to parse.' % self.tc.layer['name'],
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 256, in check_command
    raise RuntimeError(msg)
RuntimeError: Layer meta-webos-iot failed to parse.
Command: bitbake -p
Output:
Loading cache...done.
Loaded 0 entries from dependency cache.
Parsing recipes...ERROR: ParseError at /OE/meta-webosose/meta-webos-iot/classes/webos_iot_image.bbclass:16: Could not inherit file classes/webos_image.bbclass

Summary: There was 1 ERROR message shown, returning a non-zero exit code.

======================================================================
INFO: ERROR: test_signatures (common.CommonCheckLayer)
INFO: ----------------------------------------------------------------------
INFO: Traceback (most recent call last):
  File "/OE/openembedded-core/scripts/lib/checklayer/cases/common.py", line 52, in test_signatures
    curr_sigs, _ = get_signatures(self.td['builddir'], failsafe=True)
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 281, in get_signatures
    check_command('Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.',
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 256, in check_command
    raise RuntimeError(msg)
RuntimeError: Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.
Command: BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BB_SIGNATURE_HANDLER" BB_SIGNATURE_HANDLER="OEBasicHash" bitbake -k -S none world
Output:
Loading cache...done.
Loaded 697 entries from dependency cache.
Parsing recipes...ERROR: ParseError at /OE/meta-webosose/meta-webos-iot/recipes-core/packagegroups/packagegroup-webos-iot-bsp.bb:12: Could not inherit file classes/webos_machine_impl_dep.bbclass

Summary: There was 1 ERROR message shown, returning a non-zero exit code.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-122674] CCC: build fixes for host-user-contaminated QA issues

Change-Id: I5ff961bc42d46bc5049cfef99d705db48654292d