webos_preferred_gfx_image_format.bbclass: change the warning into fatal error
:Release Notes:
It's easy to disable with WEBOS_PREFERRED_GFX_IMAGE_FORMAT_ENABLED
so this should be triggered only when something is really wrong.

:Detailed Notes:
I've noticed this in kirkstone builds which trigger:
WARNING: com.webos.app.camera-0.0.1-8-r0
  do_convert_webos_preferred_gfx_image_format:
  Could not find com.webos.app.camera:appinfo.json,
  no conversion will be performed

But the issue is actually caused by broken enact (old
webpack not compatible with openssl-3):

grep Error: BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/temp/log.do_install
Error: error:0308010C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported

10%  building 1/2 modules  src/index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/webpack/lib/NormalModule.js:417:16)
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/webpack/lib/NormalModule.js:452:10
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/webpack/lib/NormalModule.js:323:13
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/eslint-loader/dist/cacheLoader.js:48:12

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-6542] CCC: Various build fixes

Change-Id: Iced4e13bb767c66fa19f8f3e91b6b99f41a5c54f