qtmultimedia=webos8 (inherit pkgconfig)
:Release Notes:
Newer oe-core doesn't pull many default dependencies anymore:
https://lists.openembedded.org/g/openembedded-core/message/156185
add explicit dependency on pkgconfig through pkgconfig.bbclass as
we're using it here.

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/241750
ERROR: Feature 'pulseaudio' was enabled, but the pre-condition 'libs.pulseaudio' failed.

Similar change was already applied in meta-qt5:
https://github.com/meta-qt5/meta-qt5/commit/f200be9d671ced4d2f8054c238527a7c6ed5b4b8
and upstream recipe in meta-qt6:
https://code.qt.io/cgit/yocto/meta-qt6.git/commit/?id=d718354d16d1e65b0d02b360f56d23f56d083d69

:Testing Performed:
See the CCC JIRA ticket.

:QA Notes:
No change to the image.

:Issues Addressed:
[WRN-8503] CCC: Update meta-qt6 to v6.2.1

Change-Id: Ibfd1369b3ee4b9e9b6e20caaef53f59c551800ef