base-files=webos11webosrpi2 (don't create /mnt for SOTA)
:Release Notes:

:Detailed Notes:
With newer meta-updater I see:
WARNING: webos-image-1.0-r3 do_image_ostree: Data in /mnt directory is not preserved by OSTree. Consider moving it under /usr
ERROR: webos-image-1.0-r3 do_image_ostree: Function failed: do_image_ostree (log file is located at /jenkins/mjansa/build-webos-thud/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3/temp/log.do_image_ostree.33820)

mjansa@gorilla-build:~/mjansa/build-webos-thud$ ls -lahd /jenkins/mjansa/build-webos-thud/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3/rootfs/mnt/
drwxr-xr-x 4 mjansa mjansa 4.0K Dec 31  1969 /jenkins/mjansa/build-webos-thud/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3/rootfs/mnt/
mjansa@gorilla-build:~/mjansa/build-webos-thud$ ls -lahd /jenkins/mjansa/build-webos-thud/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3/rootfs/mnt/*
drwxr-xr-x 2 mjansa mjansa 4.0K Dec 31  1969 /jenkins/mjansa/build-webos-thud/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3/rootfs/mnt/bootpart
drwxr-xr-x 2 mjansa mjansa 4.0K Dec 31  1969 /jenkins/mjansa/build-webos-thud/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3/rootfs/mnt/pica

There was similar issue with /usr/local (see fix in http://gpro.lge.com/254814)

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-85669] CCC: Upgrade meta-updater to latest revision and fix it

Change-Id: Ie695d481f51c709e51b0dc5e6a9f3fb5719f1809