webos: expect=webos2 (ignore incompatible-pointer-types issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/821861
expect5.45.4/exp_chan.c:62:5: error: initialization of 'struct Tcl_ChannelTypeVersion_ *' from incompatible pointer type 'int (*)(void *, int)' [-Wincompatible-pointer-types]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19569] CCC: expect=webos2 (ignore incompatible-pointer-types issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: 0a1b76d13301dc12152f2d6608d3186f61568004
Cherry-picked-from-branch: