{solana-program-library,solana,sugar}-crates.inc: refresh with checksums
:Release Notes:
checksums are now mandatory since:
https://git.openembedded.org/bitbake/commit/?id=9c07e377a21fe1d9660d084da93873acd289b581
https://git.openembedded.org/bitbake/commit/?id=4920686c13dd66f9bfa4f7dd38d6e955f153eeec
and cargo-update-recipe-crates.bbclass now generates them since:
https://git.openembedded.org/openembedded-core/commit/?id=c75b924a3de02625aa90ad4db4403f00d1ffeba2

The latest format of generated .inc files is backwards compatible
with fetcher used in kirkstone, so apply these changes there.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Builds/Details/1381905

ERROR: solana-cli-1.14.5-r0 do_fetch: No checksum specified for 'downloads/Inflector-0.11.4.crate', please add at least one to the recipe:
ERROR: solana-cli-1.14.5-r0 do_fetch: Bitbake Fetcher Error: NoChecksumError('Missing SRC_URI checksum', 'https://crates.io/api/v1/crates/Inflector/0.11.4/download')
ERROR: Logfile of failure stored in: BUILD/work/qemux86_64-webos-linux/solana-cli/1.14.5-r0/temp/log.do_fetch.1153193
ERROR: Task (meta-webos/recipes-upstreamable/solana/solana-cli_1.14.5.bb:do_fetch) failed with exit code '1'

ERROR: sugar-1.1.0-r0 do_fetch: No checksum specified for 'downloads/Inflector-0.11.4.crate', please add at least one to the recipe:
ERROR: sugar-1.1.0-r0 do_fetch: Bitbake Fetcher Error: NoChecksumError('Missing SRC_URI checksum', 'https://crates.io/api/v1/crates/Inflector/0.11.4/download')
ERROR: Logfile of failure stored in: BUILD/work/qemux86_64-webos-linux/sugar/1.1.0-r0/temp/log.do_fetch.1153331
ERROR: Task (meta-webos/recipes-upstreamable/sugar/sugar_1.1.0.bb:do_fetch) failed with exit code '1'

ERROR: solana-keygen-1.14.5-r0 do_fetch: No checksum specified for 'downloads/Inflector-0.11.4.crate', please add at least one to the recipe:
ERROR: solana-keygen-1.14.5-r0 do_fetch: Bitbake Fetcher Error: NoChecksumError('Missing SRC_URI checksum', 'https://crates.io/api/v1/crates/Inflector/0.11.4/download')
ERROR: Logfile of failure stored in: BUILD/work/qemux86_64-webos-linux/solana-keygen/1.14.5-r0/temp/log.do_fetch.1153360
ERROR: Task (meta-webos/recipes-upstreamable/solana/solana-keygen_1.14.5.bb:do_fetch) failed with exit code '1'

ERROR: solana-program-library-2.1.1-r0 do_fetch: No checksum specified for 'downloads/Inflector-0.11.4.crate', please add at least one to the recipe:
ERROR: solana-program-library-2.1.1-r0 do_fetch: Bitbake Fetcher Error: NoChecksumError('Missing SRC_URI checksum', 'https://crates.io/api/v1/crates/Inflector/0.11.4/download')
ERROR: Logfile of failure stored in: BUILD/work/qemux86_64-webos-linux/solana-program-library/2.1.1-r0/temp/log.do_fetch.1153519
ERROR: Task (meta-webos/recipes-upstreamable/solana-program-library/solana-program-library_git.bb:do_fetch) failed with exit code '1'

The easiest way to refresh the .inc files is to empty them first, e.g.:
  echo > meta-webos/recipes-upstreamable/solana/solana-crates.inc
  echo > meta-webos/recipes-upstreamable/sugar/sugar-crates.inc
  echo > meta-webos/recipes-upstreamable/solana-program-library/solana-program-library-crates.inc
before regenerating the .inc files with:
  bitbake -c update_crates solana-program-library sugar solana
because otherwise do_fetch will fail, because of missing crate checksums
before update_crates task is executed.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-412] Create GPVB with Yocto 4.2 Mickledore
[WRP-12446] CCC: Various build fixes
[WRP-12469] Bitbake world issues 2023-04-01

Cherry-picked-from-commit: 66707179a3fa248b5eb4fd6eb313efd14b93d1f9
Cherry-picked-from-branch: