rpi: linux-raspberrypi=v4.14.39 (add support for RaspberryPi 3B+)
:Release Notes:
Backport the changes from:
https://github.com/agherzan/meta-raspberrypi/pull/215
to get latest stable kernel and firmware which also supports
RaspberryPi 3B+

:Detailed Notes:
Also include overlays/vc4-fkms-v3d.dtbo in default KERNEL_DEVICETREE
(for 32bit as well as 64bit, because we use vc4graphics for both).
Include bcm2710-rpi-3-b-plus.dtb also for raspberrypi3-64.conf.
Backport few more rpi-config changes:
1c99862 rpi-config: fix config variables with the same initial name being overwritten
ab5ef24 rpi-config: allow VC4DTBO override on raspberrypi3-64
9bf9180 rpi-config: Add RPI_EXTRA_CONFIG option

Backport few more kernel changes to fix 4.14 configuration:
14fd58b raspberrypi0-wifi, raspberrypi3: drop unused KERNEL_DEFCONFIG variables
e7bac0b linux-raspberrypi: Merge inc files
46f78e3 linux-raspberrypi: Drop ineffective code
cbd2412 linux-raspberrypi-base.bbclass: Drop
8311d16 linux-raspberrypi: Drop unnecessary code
b934304 linux-raspberrypi: Disable DRBD lkm
88478c3 linux-raspberrypi: fix kernel configuration using cfg files

Backport newer lttng-modules 2.10.5, because old 2.8.0 isn't compatible
with 4.14 kernel:
lttng-modules/2.8.0+gitAUTOINC+6e4fc6f36d-r0/git/wrapper/kref.h:39:24:
  error: passing argument 1 of 'atomic_add_unless' from incompatible
  pointer type [-Werror=incompatible-pointer-types]

Backport few more v4.14 changes from 2.5 Sumo:
9e3a5ef linux-raspberrypi: Update to v4.14.34
8aca17a linux-raspberrypi: Update to v4.14.39

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-52479] Upgrade to Yocto 2.5 Sumo
[PLAT-78511] [OSE] CCC: Upgrade to Yocto 2.5 Sumo

Change-Id: Ie863be1aaa57596457cc17f8d4b7f4570ab4962c