rpi: packagegroup-webos-graphics: remove kernel-module-v3d
:Release Notes:
It's already included in MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS
through RPI_KERNEL_MODULES for raspberrypi4 and kernel modules
should be always listed in RRECOMMENDS, not RDEPENDS as the same
functionality might be included in kernel image, just not as
separate package with module.

:Detailed Notes:
Fixes rpi3 builds:
http://gecko.lge.com:8000/Errors/Details/581133

NOTE: Installing the following packages: opkg packagegroup-core-boot packagegroup-core-ssh-dropbear packagegroup-webos-audio packagegroup-webos-bluetooth packagegroup-webos-camera packagegroup-webos-connectivity packagegroup-webos-diagnostics packagegroup-webos-extended packagegroup-webos-graphics packagegroup-webos-i18n packagegroup-webos-media packagegroup-webos-media-drm packagegroup-webos-minimal packagegroup-webos-ml packagegroup-webos-screencast packagegroup-webos-systemapps packagegroup-webos-testapps run-postinsts
NOTE: TOPDIR/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3normal1/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f TOPDIR/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3normal1/opkg.conf -t TOPDIR/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3normal1/temp/ipktemp/ -o TOPDIR/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3normal1/rootfs  --force_postinstall --prefer-arch-to-version   --add-ignore-recommends openssh-sftp-server --add-ignore-recommends update-rc.d install opkg packagegroup-core-boot packagegroup-core-ssh-dropbear packagegroup-webos-audio packagegroup-webos-bluetooth packagegroup-webos-camera packagegroup-webos-connectivity packagegroup-webos-diagnostics packagegroup-webos-extended packagegroup-webos-graphics packagegroup-webos-i18n packagegroup-webos-media packagegroup-webos-media-drm packagegroup-webos-minimal packagegroup-webos-ml packagegroup-webos-screencast packagegroup-webos-systemapps packagegroup-webos-testapps run-postinsts
ERROR: Unable to install packages. Command 'TOPDIR/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3normal1/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f TOPDIR/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3normal1/opkg.conf -t TOPDIR/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3normal1/temp/ipktemp/ -o TOPDIR/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3normal1/rootfs  --force_postinstall --prefer-arch-to-version   --add-ignore-recommends openssh-sftp-server --add-ignore-recommends update-rc.d install opkg packagegroup-core-boot packagegroup-core-ssh-dropbear packagegroup-webos-audio packagegroup-webos-bluetooth packagegroup-webos-camera packagegroup-webos-connectivity packagegroup-webos-diagnostics packagegroup-webos-extended packagegroup-webos-graphics packagegroup-webos-i18n packagegroup-webos-media packagegroup-webos-media-drm packagegroup-webos-minimal packagegroup-webos-ml packagegroup-webos-screencast packagegroup-webos-systemapps packagegroup-webos-testapps run-postinsts' returned 1:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - conflicting requests
 *   - nothing provides kernel-module-v3d needed by packagegroup-webos-graphics-1.0-r1webosrpi1.raspberrypi3
 *
 * Solution 1:
 *   - do not ask to install a package providing packagegroup-webos-graphics

 * opkg_finalize_intercepts: Failed to open dir TOPDIR/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3normal1/temp/ipktemp//opkg-5fmKwR/opkg-intercept-i3rSJn: No such file or directory.
 * rm_r: Failed to open dir TOPDIR/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3normal1/temp/ipktemp//opkg-5fmKwR/opkg-intercept-i3rSJn: No such file or directory.
 * rm_r: Failed to open dir TOPDIR/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3normal1/temp/ipktemp//opkg-5fmKwR: No such file or directory.
Disfavor package: openssh-sftp-server

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-12469] Bitbake world issues 2023-04-01
[WRP-13300] CCC: Various build fixes

Cherry-picked-from-commit: c4e0c0de0f38a43f74e175b6ceb78ac66d349ab9
Cherry-picked-from-branch: