webos: luna-service2=r33 (ignore incompatible-pointer-types issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/821701
luna-service2/3.21.2-37/git/src/libluna-service2/transport.c:2001:50: error: passing argument 2 of '_LSTransportMessageGetString' from incompatible pointer type [-Wincompatible-pointer-types]
luna-service2/3.21.2-37/git/src/libluna-service2/transport.c:6758:12: error: returning 'LSTransportTrustLevelGroupBitmask *' from a function with incompatible return type 'LSTransportCategoryBitmask *' [-Wincompatible-pointer-types]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19569] CCC: luna-service2=r33 (ignore incompatible-pointer-types issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: 15d82fe4599932df479b47090615beedf0b4ca23
Cherry-picked-from-branch: