rust: backport 1.63.0 version from 4.1 Langdale
:Release Notes:
With necessary bbclasses, imported as-is in:
521872ab2c rust: Use libc++ runtime when using clang with llvm runtime
with only a small tweak in rust-common.bbclass to restore RUST_LIBC
to fix parsing of older 1.59.0 recipe in oe-core/kirkstone

:Detailed Notes:
Includes following changes:
521872ab2c rust: Use libc++ runtime when using clang with llvm runtime
332df9ebbd rust: Use variable to specify extra tools to install
7cd6faf4e0 rust-cross-canadian: Fix for the issue caused by using sdk shell
78aecd6d4e rust: Enable verbose-tests to get the test results in readable format
02133f92c5 rust: Add linker configurations for cross compilation
7fe15d0581 rust-llvm: Update to matching LLVM_VERSION from rust-source
5d8c01dfed rust: Fix crossbeam-utils for arches without atomics
097e38f289 rust: Fix build failure on riscv32
9f390accf5 rust: update from 1.62.1 to 1.63.0
0371e429d9 rust-target-config: Fix qemuppc target cpu option
8e1614a906 rust-target-config: Drop has-elf-tls option
74307f57ad rust-cross-canadian: rename shell variables for easier appends
6baa224158 rust: update 1.62.0 -> 1.62.1
f5c1280083 classes: Update classes to match new bitbake class scope functionality
081a391fe0 classes: Add SPDX license identifiers
880c1ea3ed classes: Add copyright statements to files without one
e4d5625693 rust: Remove unneeded RUST_TARGETGENS settings
dabd97e78a rust-cross-canadian: Use shell from SDK, not the host
388e7cac9f cargo: Work around host system library conflicts
ef347bd395 rust-common: Remove conflict with utils create_wrapper
fa5d16692d rust: Update README
c7a5297435 rust: Ensure buildpaths are handled in debug symbols correctly
1c5ab57ddd rust: Fix musl builds
b9b0cd99cd rust: Enable nativesdk and target builds + replace rust-tools-cross-canadian
4b54f5f52b rust: Drop cross/crosssdk
6ec18de9d6 rust-cross-canadian: Simplify and fix
06af65757b rust-common: Set rustlibdir to match target expectation
6d6d135924 cargo: Drop cross-canadian variant and fix/use nativesdk
f35d5af06d rust-common: Simplify libc handling
ec15882fbf rust-target-config: Make target workaround generic
dc134c0311 rust-common: Update to match cross targets
e2cdbf9df8 rust.inc: Fix for cross compilation configuration
b4b24dc53f rust-llvm: Enable nativesdk variant
0dc9635c28 cargo_common: Handle build SYS as well as HOST/TARGET
d02c28b221 rust-common/rust: Improve bootstrap BUILD_SYS handling
9160e4a375 rust: Generate per recipe target configuration files
b30ee171de rust-target-config: Show clear error when target isn't defined
35e1ecf88c rust/mesa: Drop obsolete YOCTO_ALTERNATE_MULTILIB_NAME
f355e55c1f rust.inc: Fix cross build llvm-config handling
279b809e83 rust.inc: Rename variables to make code clearer
ee0c0fdf9c rust: Switch to use RUST_XXX_SYS consistently
c08c522fc2 rust: Work around reproducibility issues
dfff5a1767 rust-common: Rework wrappers to handle musl
1a992268e5 rust-common: Drop export directive from wrappers
e2fc083529 rust-common: Add CXXFLAGS
255be90dc8 rust-target-config: Add mips n32 target information
2d4b35a0db rust-target-config: Allow the targets generated to be configurable
3795285cbf rust-target-config: Create new class to contain target json config generation
0f83d95946 rust-common/rust-cross: Clean up target json generation code
5cb62d0a33 rust-cross: Simplfy the rust_gen_target calls
ff3c3dbbd2 rust-cross/rust-common: Merge arm target handling code to fix cross-canadian
1912c4e9e0 rust-cross-canadian: Fix ordering of target json config generation
d554161a04 rust-common: Set llvm-target correctly for cross SDK targets
abb1f3f12b cargo-cross-canadian: Use SDK's flags during target linking
94760bc118 rust: update 1.60.0 -> 1.62.0
ef566af964 rust: fix issue building cross-canadian tools for aarch64 on x86_64
2b9bb4c07d rust-common: Fix native signature dependency issues
bd36593ba3 rust-common: Drop LLVM_TARGET and simplify
8ed000debb rust-common: Fix for target definitions returning 'NoneType' for arm
65ce2d1291 rust-common: Ensure sstate signatures have correct dependencues for do_rust_gen_targets
38b61aeaf8 rust-common: Fix sstate signatures between arm hf and non-hf
e3a910af0c libstd-rs: Forward port rust libc patches
786a9a6648 rust: update 1.59.0 -> 1.60.0

Older cargo isn't compatible with solana manifests, e.g.
http://gecko.lge.com:8000/Errors/Details/475064

solana-program-library-2.1.1-r0 do_compile:
NOTE: cargo build -v --target aarch64-webos-linux --release --manifest-path=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/solana-program-library/2.1.1-r0/git/token/cli//Cargo.toml
error: failed to load manifest for workspace member `TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/solana-program-library/2.1.1-r0/git/token-upgrade/cli`

Caused by:
  failed to load manifest for dependency `spl-token-client`

Caused by:
  failed to parse manifest at `TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/solana-program-library/2.1.1-r0/git/token/client/Cargo.toml`

Caused by:
  namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line

We also need to backport updated python3_pyo3.bbclass, because without the change from:
ee0c0fdf9c rust: Switch to use RUST_XXX_SYS consistently
python3-cryptography would fail with:
http://gecko.lge.com:8000/Errors/Details/475133
error: Error loading target specification: Could not find specification for target "aarch64-webos-linux". Run `rustc --print target-list` for a list of built-in targets

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12360] Prepare CCC for the solana NFT minting based on build-webos yocto 4.0
[WRO-14510] CCC: Various build fixes

Change-Id: I71c5152bcc92f749b852c255643c52ae4c8175b5