bluez5 (refresh patches to apply on 5.64 version)
:Release Notes:

:Detailed Notes:
Fixes:
NOTE: recipe bluez5-5.64-r0: task do_patch: Started
ERROR: bluez5-5.64-r0 do_patch: Applying patch '0019-Enabled-EMAIL-support-based-on-MAPInstance-Name-Modi.patch' on target directory '/OE/lge/build/webosose/kirkstone/BUILD/work/qemux86_64-webos-linux/bluez5/5.64-r0/bluez-5.64'
CmdError('quilt --quiltrc /OE/lge/build/webosose/kirkstone/BUILD/work/qemux86_64-webos-linux/bluez5/5.64-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0019-Enabled-EMAIL-support-based-on-MAPInstance-Name-Modi.patch
patching file obexd/client/bluetooth.c
patching file obexd/client/manager.c
patching file obexd/client/map.c
patching file obexd/client/session.c
patching file obexd/client/session.h
patching file obexd/client/transport.h
patching file tools/obexctl.c
Hunk #1 succeeded at 1308 with fuzz 2 (offset 1194 lines).
Hunk #2 FAILED at 145.
Hunk #3 FAILED at 154.
Hunk #4 FAILED at 163.
Hunk #5 FAILED at 1833.
Hunk #6 succeeded at 1868 (offset 15 lines).
4 out of 6 hunks FAILED -- rejects in file tools/obexctl.c
Patch 0019-Enabled-EMAIL-support-based-on-MAPInstance-Name-Modi.patch does not apply (enforce with -f)

stderr: ')
ERROR: Logfile of failure stored in: /OE/lge/build/webosose/kirkstone/BUILD/work/qemux86_64-webos-linux/bluez5/5.64-r0/temp/log.do_patch.1967342
NOTE: recipe bluez5-5.64-r0: task do_patch: Failed

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12999] CCC: Upgrade to Yocto 4.0 Kirkstone
[WRN-9820] Create GPVB with Yocto 4.0 Kirkstone

Change-Id: Idaf9a1e93bde840eefd19e928d3a45183d0f246c