mdadm=webos2 (fix file-rdeps QA issue about /bin/bash)
:Release Notes:
ERROR: mdadm-4.2-r0 do_package_qa: QA Issue: mdadm rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]

:Detailed Notes:

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12999] CCC: Upgrade to Yocto 4.0 Kirkstone
[WRN-9820] Create GPVB with Yocto 4.0 Kirkstone

Change-Id: Ia27430c9c13185f7a8a256eefc6ddc6485c472fd