webos: webos-backports-5.0: skip rust-hello-world
:Release Notes:
Doesn't build with updated .bbclasses from this layer.

:Detailed Notes:
It was removed from oe-core in nanbield:
https://git.openembedded.org/openembedded-core/commit/?h=nanbield&id=8baaf94d200f5355791ecd980727698b1ab0e539
so no need to fix it here.

Fails to build due to --frozen:
http://gecko.lge.com:8000/Errors/Details/851518
error: the lock file rust-hello-world/git-r0/git/Cargo.lock needs
to be updated but --frozen was passed to prevent this

Remove it from packagegroup-core-tools-testapps as oe-core later did
to avoid:

NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'rust-hello-world' (but oe-core/meta/recipes-core/packagegroups/packagegroup-core-tools-testapps.bb RDEPENDS on or otherwise requires it)
rust-hello-world was skipped: Recipe will be skipped because: BROKEN: doesn't build since rust and related bbclasses were updated by this layer, already removed in newer oe-core/nanbield
NOTE: Runtime target 'rust-hello-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rust-hello-world']
NOTE: Runtime target 'packagegroup-core-tools-testapps' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-core-tools-testapps', 'rust-hello-world']

Drop BBFILE_PATTERN_IGNORE_EMPTY_meta-webos-backports-5.0
as this layer isn't empty for a while.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-22410] CCC: webos-backports-5.0: skip rust-hello-world
[WRQ-22079] Update rust 1.75 from scarthgap

Cherry-picked-from-commit: 5359fec476efd6270ba0a7bea0f37629ff074845
Cherry-picked-from-branch: