nodejs: update patch to apply on new 16.11.1 version
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: nodejs-16.11.1-r0 do_patch: Fuzz detected:

Applying patch 0001-Use-human-readable-process-name-for-chrome-inspector.patch
patching file src/inspector_io.cc
patching file src/node_internals.h
Hunk #1 succeeded at 91 with fuzz 2 (offset -9 lines).
patching file src/util.cc
Hunk #1 succeeded at 164 (offset 3 lines).

The context lines in the patches can be updated with devtool:

    devtool modify nodejs
    devtool finish --force-patch-refresh nodejs <layer_path>

Don't forget to review changes done by devtool!

ERROR: nodejs-16.11.1-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12999] CCC: Upgrade to Yocto 4.0 Kirkstone
[WRN-9820] Create GPVB with Yocto 4.0 Kirkstone

Change-Id: Ib50c21832da969b33c0f20e9f41bbe4e27901ad3