rpi: meta-webos-raspberrypi: raspberrypi3-64.conf: sync from warrior
:Release Notes:
Import tune-cortexa53.inc from warrior and use it for raspberrypi3-64.
tune-cortexa72.inc was already backported for raspberrypi4, import
the other tune as well to use the same config as warrior does.

:Detailed Notes:
Fixes:
  ERROR: ParseError at meta-webos-raspberrypi/conf/machine/
  raspberrypi3-64.conf:19: Could not include required file
  conf/machine/include/arm/arch-armv8.inc

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-77937] Create GPVB with Yocto 2.7
[PLAT-80962] Upgrade linux-raspberrpi to 4.19
[PLAT-86843] CCC: Various build fixes

Change-Id: I496de71ab59c21479449216ca9672fc4a32daf33