webos: libgcrypt=webos1
:Release Notes:
Fix for sed command in libgcrypt component
As it is updating the path of build directory

:Detailed Notes:
| ../../libgcrypt-1.9.4/random/rndjent.c:40:10: fatal error: stdio.h: No such file or directory
|    40 | #include <stdio.h>
|       |          ^~~~~~~~~
| compilation terminated.
| make[2]: *** [Makefile:737: rndjent.lo] Error 1

Above error was found as it is updating PWD directory path and
because of it sysroot path and effected path are updating and result in
wrong path

:Testing Performed:
Locally Tested

:QA Notes:
N/A

:Issues Addressed:
[WRQ-18125] CCC: libgcrypt=webos1

Cherry-picked-from-commit: 03618aefe5254b6a48c49263e5c6508fcae890f6
Cherry-picked-from-branch: