webos: auto-luna-surface-manager=r8
:Release Notes:
Add ANY_OF_DISTRO_FEATURES restriction.

:Detailed Notes:
ERROR: Nothing PROVIDES 'luna-surfacemanager' (but /OE/lge/build/webos/kirkstone/meta-lg-webos/meta-webos/recipes-webos/auto-luna-surface-manager/auto-luna-surface-manager.bb DEPENDS on or otherwise requires it)
luna-surfacemanager was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-22410] CCC: auto-luna-surface-manager=r8
[WRQ-7027] ...
[WRQ-8249] ...
[WRQ-7034] ...
[WRQ-17413] ...

Cherry-picked-from-commit: 833bb3fffaac795d93dfe68c0508c36cb30cc547
Cherry-picked-from-branch: