db8=r32 (link with libatomic to fix qemuarm build failure)
:Release Notes:
Otherwise it fails with:
http://caprica.lgsvl.com:8080/Errors/Details/885044

:Detailed Notes:
| /jenkins/mjansa/build-webos-master-mcf/BUILD/work/qemuarm-webos-linux-gnueabi/db8/3.2.0-229-r30/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++   -march=armv5te -mthumb  --sysroot=/jenkins/mjansa/build-webos-master-mcf/BUILD/work/qemuarm-webos-linux-gnueabi/db8/3.2.0-229-r30/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/jenkins/mjansa/build-webos-master-mcf/BUILD/work/qemuarm-webos-linux-gnueabi/db8/3.2.0-229-r30=/usr/src/debug/db8/3.2.0-229-r30 -fdebug-prefix-map=/jenkins/mjansa/build-webos-master-mcf/BUILD/work/qemuarm-webos-linux-gnueabi/db8/3.2.0-229-r30/recipe-sysroot-native= -fdebug-prefix-map=/jenkins/mjansa/build-webos-master-mcf/BUILD/work/qemuarm-webos-linux-gnueabi/db8/3.2.0-229-r30/recipe-sysroot=  -fvisibility-inlines-hidden  -march=armv5te -mthumb  --sysroot=/jenkins/mjansa/build-webos-master-mcf/BUILD/work/qemuarm-webos-linux-gnueabi/db8/3.2.0-229-r30/recipe-sysroot -pthread -DUSE_PMLOG -DWITH_SNAPPY_COMPRESSION -Wall -Wextra -fPIC -Wconversion --std=c++0x -Wno-unused-but-set-variable -Wno-unused-variable -fno-exceptions -frename-registers -DMOJ_LINUX -fno-strict-aliasing -Wno-psabi -DMOJ_INTERNAL -D_REENTRANT -Werror=return-type -Wno-unused-parameter -Wno-empty-body -Wl,--no-undefined -DWITH_SEARCH_QUERY_CACHE -DUSE_PMLOG_DECLARATION  -DMOJ_USE_LDB -DMOJ_USE_SANDWICH -DNDEBUG  -march=armv5te -mthumb  --sysroot=/jenkins/mjansa/build-webos-master-mcf/BUILD/work/qemuarm-webos-linux-gnueabi/db8/3.2.0-229-r30/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/jenkins/mjansa/build-webos-master-mcf/BUILD/work/qemuarm-webos-linux-gnueabi/db8/3.2.0-229-r30=/usr/src/debug/db8/3.2.0-229-r30 -fdebug-prefix-map=/jenkins/mjansa/build-webos-master-mcf/BUILD/work/qemuarm-webos-linux-gnueabi/db8/3.2.0-229-r30/recipe-sysroot-native= -fdebug-prefix-map=/jenkins/mjansa/build-webos-master-mcf/BUILD/work/qemuarm-webos-linux-gnueabi/db8/3.2.0-229-r30/recipe-sysroot=  -fvisibility-inlines-hidden  -march=armv5te -mthumb  --sysroot=/jenkins/mjansa/build-webos-master-mcf/BUILD/work/qemuarm-webos-linux-gnueabi/db8/3.2.0-229-r30/recipe-sysroot -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -rdynamic CMakeFiles/performance.dir/testsuite.cpp.o CMakeFiles/performance.dir/__/__/src/engine/leveldb/defs.cpp.o CMakeFiles/performance.dir/__/__/src/engine/leveldb/MojDbLevelEngine.cpp.o CMakeFiles/performance.dir/__/__/src/engine/leveldb/MojDbLevelFactory.cpp.o CMakeFiles/performance.dir/__/__/src/engine/leveldb/MojDbLevelDatabase.cpp.o CMakeFiles/performance.dir/__/__/src/engine/leveldb/MojDbLevelQuery.cpp.o CMakeFiles/performance.dir/__/__/src/engine/leveldb/MojDbLevelTxn.cpp.o CMakeFiles/performance.dir/__/__/src/engine/leveldb/MojDbLevelSeq.cpp.o CMakeFiles/performance.dir/__/__/src/engine/leveldb/MojDbLevelCursor.cpp.o CMakeFiles/performance.dir/__/__/src/engine/leveldb/MojDbLevelEnv.cpp.o CMakeFiles/performance.dir/__/__/src/engine/leveldb/MojDbLevelIndex.cpp.o CMakeFiles/performance.dir/__/__/src/engine/leveldb/MojDbLevelItem.cpp.o CMakeFiles/performance.dir/__/__/src/engine/leveldb/MojDbLevelTxnIterator.cpp.o CMakeFiles/performance.dir/__/__/src/engine/leveldb/MojDbLevelIterator.cpp.o CMakeFiles/performance.dir/__/__/src/engine/leveldb/MojDbLevelContainerIterator.cpp.o CMakeFiles/performance.dir/__/__/src/engine/sandwich/MojDbSandwichEngine.cpp.o CMakeFiles/performance.dir/__/__/src/engine/sandwich/MojDbSandwichFactory.cpp.o CMakeFiles/performance.dir/__/__/src/engine/sandwich/MojDbSandwichDatabase.cpp.o CMakeFiles/performance.dir/__/__/src/engine/sandwich/MojDbSandwichQuery.cpp.o CMakeFiles/performance.dir/__/__/src/engine/sandwich/MojDbSandwichTxn.cpp.o CMakeFiles/performance.dir/__/__/src/engine/sandwich/MojDbSandwichSeq.cpp.o CMakeFiles/performance.dir/__/__/src/engine/sandwich/MojDbSandwichEnv.cpp.o CMakeFiles/performance.dir/__/__/src/engine/sandwich/MojDbSandwichIndex.cpp.o CMakeFiles/performance.dir/__/__/src/engine/sandwich/MojDbSandwichItem.cpp.o CMakeFiles/performance.dir/__/__/src/engine/sandwich/MojDbSandwichLazyUpdater.cpp.o  -o performance ../../src/db/libmojodb.so.3.2.0 -lboost_regex-mt -lboost_filesystem-mt -lboost_system-mt -lboost_program_options-mt -lboost_chrono-mt -lleveldb -lleveldb libperfutils.a ../../src/core/libmojocore.so.3.2.0 -lPmLogLib -lboost_regex-mt -lglib-2.0 -lgthread-2.0 -lglib-2.0 -lgthread-2.0 -pthread -licuuc -licui18n
| /usr/include/c++/7.2.0/bits/atomic_base.h:374: error: undefined reference to '__atomic_store_8'
| /usr/include/c++/7.2.0/bits/atomic_base.h:374: error: undefined reference to '__atomic_store_8'
| /usr/include/c++/7.2.0/bits/atomic_base.h:396: error: undefined reference to '__atomic_load_8'
| /usr/include/c++/7.2.0/bits/atomic_base.h:374: error: undefined reference to '__atomic_store_8'
| /usr/include/c++/7.2.0/bits/atomic_base.h:374: error: undefined reference to '__atomic_store_8'
| /usr/include/c++/7.2.0/bits/atomic_base.h:396: error: undefined reference to '__atomic_load_8'
| /usr/include/c++/7.2.0/bits/atomic_base.h:514: error: undefined reference to '__atomic_fetch_add_8'
| /usr/include/c++/7.2.0/bits/atomic_base.h:396: error: undefined reference to '__atomic_load_8'
| /usr/include/c++/7.2.0/bits/atomic_base.h:396: error: undefined reference to '__atomic_load_8'
| /usr/include/c++/7.2.0/bits/atomic_base.h:514: error: undefined reference to '__atomic_fetch_add_8'
| collect2: error: ld returned 1 exit status
| make[2]: *** [test/performance/performance] Error 1
| make[2]: Leaving directory `/jenkins/mjansa/build-webos-master-mcf/BUILD/work/qemuarm-webos-linux-gnueabi/db8/3.2.0-229-r30/build'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-64986] [OSE] CCC: Various build issues