com.webos.service.mediaindexer: CMakeLists.txt: respect libdir setting
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/665168

ERROR: QA Issue: lib32-com.webos.service.mediaindexer: Files/directories were installed but not shipped in any package:
  /usr/lib/libmediaindexerclient.so
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
lib32-com.webos.service.mediaindexer: 1 installed and not shipped files. [installed-vs-shipped]

when libdir is /usr/lib32 or /usr/lib64.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-20118] Bitbake world issues 2023-07
[WRP-24156] CCC: Various build fixes

Cherry-picked-from-commit: 76bdc2dcc3a7c5c8f44a27aa4f9720c4b43487cf
Cherry-picked-from-branch: