qtbase=webos83 qtbase-native=webos5
:Release Notes:
Backport changes from:
https://bugreports.qt.io/browse/QTBUG-18870

:Detailed Notes:
https://code.qt.io/cgit/qt/qtbase.git/commit/qmake/generators/makefile.cpp?id=2f672b223900e056ffa642d3186e6cdcac9152aa
https://code.qt.io/cgit/qt/qtbase.git/commit/qmake/generators/makefile.cpp?id=20e9422e069a27b7e29b54207447e6ca02b3a55a

This should help to detect qinstall errors much earlier than
when host-user-contaminated QA issue is triggered in very
rare cases where it breaks pseudo as well.

E.g. with qml-webos-framework, I've recently seen:
ERROR: QA Issue: qml-webos-framework: /usr/share/luna-service2/roles.d/qt_temp.EfLlOH is owned by uid 1101, which is the same as the user running bitbake. This may be due to host contamination [host-user-contaminated]

but in the log.do_install it shows more issues which lead to this:

cd runner/ && ( test -e Makefile || /qml-webos-framework/1.0.0-149-r30/recipe-sysroot-native/usr/bin/qmake -o Makefile /qml-webos-framework/1.0.0-149-r30/git/tools/runner/runner.pro WEBOS_STAGING_INCDIR=/qml-webos-framework/1.0.0-149-r30/recipe-sysroot/usr/include WEBOS_INSTALL_BINS=/usr/bin WEBOS_INSTALL_LIBS=/usr/lib WEBOS_INSTALL_HEADERS=/usr/include/ WEBOS_INSTALL_QML=/usr/lib/qml WEBOS_INSTALL_QTPLUGINSDIR=/usr/lib/plugins WEBOS_INSTALL_WEBOS_APPLICATIONSDIR=/usr/palm/applications WEBOS_PREFERENCESDIR=/var/preferences WEBOS_INSTALL_ROOT= WEBOS_INSTALL_PREFIX=/usr WEBOS_INSTALL_DATADIR=/usr/share WEBOS_INSTALL_SYSCONFDIR=/etc WEBOS_INSTALL_SYSBUS_DATADIR= WEBOS_INSTALL_TESTSDIR=/usr/opt/webos/tests WEBOS_INSTALL_UPSTARTCONFDIR=/etc/event.d WEBOS_INSTALL_WEBOS_SDKDIR=/usr/opt/webos/sdk WEBOS_INSTALL_SYSBUS_SERVICEDIR=/usr/share/luna-service2/services.d WEBOS_INSTALL_SYSBUS_SERVICESDIR=/usr/share/luna-service2/services.d WEBOS_INSTALL_SYSBUS_PUBSERVICESDIR=/usr/share/dbus-1/services WEBOS_INSTALL_SYSBUS_PRVSERVICESDIR=/usr/share/dbus-1/system-services WEBOS_INSTALL_SYSBUS_ROLESDIR=/usr/share/luna-service2/roles.d WEBOS_INSTALL_SYSBUS_PUBROLESDIR=/usr/share/ls2/roles/pub WEBOS_INSTALL_SYSBUS_PRVROLESDIR=/usr/share/ls2/roles/prv WEBOS_INSTALL_SYSBUS_APIDIR=/usr/share/luna-service2/api-permissions.d WEBOS_INSTALL_SYSBUS_PERMDIR=/usr/share/luna-service2/client-permissions.d WEBOS_INSTALL_SYSBUS_GROUPDIR=/usr/share/luna-service2/groups.d -after CONFIG-=create_cmake ) && make -f Makefile install
make[2]: Entering directory '/qml-webos-framework/1.0.0-149-r30/build/tools/runner'
make[2]: Entering directory '/qml-webos-framework/1.0.0-149-r30/build/tools/runner-debug'
/qml-webos-framework/1.0.0-149-r30/recipe-sysroot-native/usr/bin/qmake -install qinstall -exe qml-runner /qml-webos-framework/1.0.0-149-r30/image/usr/bin/qml-runner
/qml-webos-framework/1.0.0-149-r30/recipe-sysroot-native/usr/bin/qmake -install qinstall /qml-webos-framework/1.0.0-149-r30/build/tools/runner/sysbus/com.webos.app.qmlrunner.role.json /qml-webos-framework/1.0.0-149-r30/image/usr/share/luna-service2/roles.d/com.webos.app.qmlrunner.role.json
/qml-webos-framework/1.0.0-149-r30/recipe-sysroot-native/usr/bin/qmake -install qinstall /qml-webos-framework/1.0.0-149-r30/git/tools/runner/sysbus/com.webos.app.qmlrunner.perm.json /qml-webos-framework/1.0.0-149-r30/image/usr/share/luna-service2/client-permissions.d/com.webos.app.qmlrunner.perm.json
/qml-webos-framework/1.0.0-149-r30/recipe-sysroot-native/usr/bin/qmake -install qinstall /qml-webos-framework/1.0.0-149-r30/build/tools/runner/sysbus/com.webos.app.qmlrunner.role.json /qml-webos-framework/1.0.0-149-r30/image/usr/share/luna-service2/roles.d/com.webos.app.qmlrunner.role.json
/qml-webos-framework/1.0.0-149-r30/recipe-sysroot-native/usr/bin/qmake -install qinstall /qml-webos-framework/1.0.0-149-r30/git/tools/runner/sysbus/com.webos.app.qmlrunner.perm.json /qml-webos-framework/1.0.0-149-r30/image/usr/share/luna-service2/client-permissions.d/com.webos.app.qmlrunner.perm.json
/qml-webos-framework/1.0.0-149-r30/recipe-sysroot-native/usr/bin/qmake -install qinstall -exe qml-runner-dev /qml-webos-framework/1.0.0-149-r30/image/usr/opt/webos/sdk/bin/qml-runner-dev
Cannot touch /qml-webos-framework/1.0.0-149-r30/image/usr/share/luna-service2/client-permissions.d/com.webos.app.qmlrunner.perm.json: No such file or directory.Makefile:662: recipe for target 'install_perm' failed
make[2]: [install_perm] Error 3 (ignored)
abort()ing pseudo client by server request. See https://wiki.yoctoproject.org/wiki/Pseudo_Abort for more details on this.
Makefile:656: recipe for target 'install_role' failed
make[2]: [install_role] Aborted (ignored)
echo /qml-webos-framework/1.0.0-149-r30/image/usr/bin/qml-runner
/qml-webos-framework/1.0.0-149-r30/image/usr/bin/qml-runner
make[2]: Leaving directory '/qml-webos-framework/1.0.0-149-r30/build/tools/runner'
echo /qml-webos-framework/1.0.0-149-r30/image/usr/opt/webos/sdk/bin/qml-runner-dev
/qml-webos-framework/1.0.0-149-r30/image/usr/opt/webos/sdk/bin/qml-runner-dev
make[2]: Leaving directory '/qml-webos-framework/1.0.0-149-r30/build/tools/runner-debug'

not only the perms are installed twice (possibly bug in webos-service.prf), but also
pseudo abort being ignored, because QINSTALL is called with leading dash

pseudo.log shows the issue:
path mismatch [1 link]: ino 119804779 db '/qml-webos-framework/1.0.0-149-r30/image/usr/share/luna-service2/client-permissions.d/com.webos.app.qmlrunner.perm.json' req '/qml-webos-framework/1.0.0-149-r30/image/usr/share/luna-service2/roles.d/qt_temp.EfLlOH'.
inode mismatch: '/qml-webos-framework/1.0.0-149-r30/image/usr/share/luna-service2/client-permissions.d/com.webos.app.qmlrunner.perm.json' ino 119804779 in db, 119804777 in request.

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-48507]  pseudo: random package_qa failures
[PLAT-122539] CCC: resolve host-user-contaminated QA issues in Qt

Change-Id: I85b88b4f34e9b0c5e94bcba500544cde11570cae