db8=r33
:Release Notes:
Fix typo in RDEPENDS.

:Detailed Notes:
There is no ${PN}-test package only ${PN}-tests.
Fixes:
http://caprica.lgsvl.com:8080/Errors/Details/1585691
ERROR: QA Issue: /usr/lib/db8/tests/volume/runtest.bash contained in
  package db8-tests requires /bin/bash, but no providers found in
  RDEPENDS_db8-tests? [file-rdeps]

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-84802] CCC: Fix missing runtime dependencies

Change-Id: I96f92203276ff9574b6b63ef36bf7b19d1467d1a