tflite-auto-delegation: add gpu-delegate to REQUIRED_DISTRO_FEATURES
:Release Notes:
There is gl-backend PACKAGECONFIG which respects gpu-delegate in DISTRO_FEATURES,
but still fails to build without gpu-delegate.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/582724
FAILED: test/auto_delegation_test
TOPDIR/BUILD/work/mach-distro-linux-gnueabi/tflite-auto-delegation/1.0.0-27-r1/..../11.3.0/ld: auto_delegation/libauto-delegation.so.1.0.0: undefined reference to `TfLiteGpuDelegateOptionsV2Default'
TOPDIR/BUILD/work/mach-distro-linux-gnueabi/tflite-auto-delegation/1.0.0-27-r1/..../11.3.0/ld: auto_delegation/libauto-delegation.so.1.0.0: undefined reference to `TfLiteGpuDelegateV2Create'

inherit features_check

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-12469] Bitbake world issues 2023-04-01
[WRP-13300] CCC: Various build fixes

Cherry-picked-from-commit: caec40e5e35f856045f28409afe7cdd39eedf42d
Cherry-picked-from-branch: