clang_cmake.bbclass: add explicit dependency on clang-native
:Release Notes:
It was transitively depending on llvm-native which with meta-clang happended to be
provided by clang-native instead of llvm-native and it build ok.

:Detailed Notes:
But after:
https://github.com/kraj/meta-clang/commit/384e8d169a2c408e2cef03ea2deb88fb82058011

llvm-native was provided by llvm-native and all *-clang.bb recipes failed to build with
errors like jsoncpp-clang:
http://gecko.lge.com:8000/Errors/Details/604196

CMake Error at CMakeLists.txt:67 (project):
  The CMAKE_CXX_COMPILER:

    clang++

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

more failed tasks in:
http://gecko.lge.com:8000/Builds/Details/1469131

To fix this add explict dependency on clang-native, but we also need to set common
provider for llvm-native, because when both clang-native and llvm-native tries to
install in the same RSS it fails with conflicts as shown in:
http://gecko.lge.com:8000/Errors/Details/604208

Exception: FileExistsError: [Errno 17] File exists:
'TOPDIR/BUILD/sysroots-components/x86_64/clang-native/usr/lib/libLLVMX86TargetMCA.a' ->
'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/jsoncpp-clang/1_1.9.5-r2/recipe-sysroot-native/usr/lib/libLLVMX86TargetMCA.a'

So set P_P as meta-clang commit message suggests, but in our case make it conditional
on WEBRUNTIME_TOOLCHAIN, because not all our DISTROs are using meta-clang.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-13301] Create GPVB with Yocto 4.3 Nanbield
[WRP-15099] CCC: Various build fixes

Cherry-picked-from-commit: c10f5781652b9aec7d2894f9563f6fe1966bf59b
Cherry-picked-from-branch: