webos: wpa-supplicant=webos8 (ignore implicit-function-declaration issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

caused by 0001-Add-p2p-changes.patch

http://gecko.lge.com:8000/Errors/Details/819468
notify.c:769:25: error: implicit declaration of function 'wpas_dbus_signal_p2p_peer_joined_with_ip'; did you mean 'wpas_dbus_signal_p2p_peer_joined'? [-Wimplicit-function-declaration]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19955] CCC: wpa-supplicant=webos8 (ignore implicit-function-declaration issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: 48c57d5e600b5a716c6a3c72c276a716d5630298
Cherry-picked-from-branch: