webos: pdm: Simplify how various implementations of pdm are included in images
:Release Notes:
Use VIRTUAL-RUNTIME_pdm everywhere and just set it once for each DISTRO.
Remove the old restriction which doesn't apply anymore, we have newer
toolchain and it builds fine for qemuarm and raspberrypi3 now.

:Detailed Notes:
Also fix:
ERROR: Nothing RPROVIDES 'lib32-pdm-plugin' (but virtual:multilib:lib32:meta-webos/recipes-webos/com.webos.service.pdm/com.webos.service.pdm.bb RDEPENDS on or otherwise requires it)
lib32-pdm-plugin was skipped: incompatible with machine qemux86 (not in COMPATIBLE_MACHINE)
lib32-pdm-plugin was skipped: incompatible with machine qemux86 (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'lib32-pdm-plugin' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-pdm-plugin']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'lib32-meta-world-pkgdata', 'lib32-com.webos.service.pdm', 'lib32-pdm-plugin']

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-81478] Sync meta-webos between meta-webosose and meta-lg-webos
             (Take 2: bidirectional sync)
[PLAT-84378] CCC: Various build fixes

Change-Id: Iea33a9edb9d9613193234c96fb7217a9eb59308e