mtd-utils: fix QA
:Release Notes:

:Detailed Notes:
ERROR: QA Issue: mtd-utils-tests rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-52479] Upgrade to Yocto 2.5 Sumo
[PLAT-78511] [OSE] CCC: Upgrade to Yocto 2.5 Sumo

Change-Id: I0ce9f5a43ce818316e16b3d10b987768cd8777c9