dropbear: package systemd_system_unitdir in PN
:Release Notes:
With multilib enabled the libdir is usr/lib64 instead of usr/lib.
Add PV as it's 4 commits after 1.0 tag.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/574301

ERROR: QA Issue: dropbear: Files/directories were installed but not shipped in any package:
  /lib/systemd/system
  /lib/systemd/system/dropbearkey.service
  /lib/systemd/system/dropbear@.service
  /lib/systemd/system/dropbear.socket
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
dropbear: 4 installed and not shipped files. [installed-vs-shipped]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-12446] CCC: Various build fixes
[WRP-12469] Bitbake world issues 2023-04-01

Cherry-picked-from-commit: b65e25a7bd2009087ebcdbf2c31a8235b61ff0c0
Cherry-picked-from-branch: