webos: com.webos.app.mediagallery=r4
:Release Notes:
Add ANY_OF_DISTRO_FEATURES restriction.

:Detailed Notes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'qml-webos-framework' (but
  meta-webos/recipes-webos/com.webos.app.mediagallery/com.webos.app.mediagallery.bb,
  RDEPENDS on or otherwise requires it)
qml-webos-framework was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-18608] CCC: com.webos.app.mediagallery=r4
[WRQ-7027] ...
[WRQ-8249] ...
[WRQ-7034] ...
[WRQ-17413] ...

Cherry-picked-from-commit: 97eb74a643716af6f54fa70460415cb88caa8b0d
Cherry-picked-from-branch: