webos: fluentbit=webos6
:Release Notes:
Drop incorrect installed-vs-shipped and fix it properly.

:Detailed Notes:
Backport a fix to respect libdir and systemd_system_unitdir (e.g. when
libdir is /usr/lib instead of just /lib with usrmerge in
DISTRO_FEATURES) instead of checking /lib/systemd/system existence on
build host and installing always to such directory.

Fixes:
http://gecko.lge.com:8000/Errors/Details/1000342

ERROR: QA Issue: lib32-fluentbit: Files/directories were installed but not shipped in any package:
  /lib
  /lib/systemd
  /lib/systemd/system
  /lib/systemd/system/fluent-bit.service
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
lib32-fluentbit: 4 installed and not shipped files. [installed-vs-shipped]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-8245] CCC: fluentbit=webos6
[WRR-8222] Fix webos4tv sync up

Cherry-picked-from-commit: 2d537b70160ba8833615457aae0389f0d80e9330
Cherry-picked-from-branch: