webos-backports-4.1: smack-test: backport changes to use python3
:Release Notes:
Backport 2 changes from langdale:
95f7abc smack-test: more py3 covertion
98df792 smack-test: switch to python3

:Detailed Notes:
Backport request sent upstream in:
https://lists.yoctoproject.org/g/yocto/message/61117
https://lists.yoctoproject.org/g/yocto/message/61118

Fixes:
ERROR: Nothing RPROVIDES 'lib32-python' (but virtual:multilib:lib32:meta-security/recipes-mac/smack/smack-test_1.0.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'lib32-python' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-python']
ERROR: Nothing RPROVIDES 'lib32-smack-test-dev' (but virtual:multilib:lib32:meta-security/recipes-mac/smack/smack-test_1.0.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lib32-smack-test-dev'
NOTE: Runtime target 'lib32-smack-test-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-smack-test-dev']
ERROR: Nothing RPROVIDES 'lib32-smack-test' (but virtual:multilib:lib32:meta-security/recipes-mac/smack/smack-test_1.0.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lib32-smack-test'
NOTE: Runtime target 'lib32-smack-test' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-smack-test']
ERROR: Nothing RPROVIDES 'python' (but meta-security/recipes-mac/smack/smack-test_1.0.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python']
NOTE: Runtime target 'smack-test' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['smack-test', 'python']
NOTE: Runtime target 'smack-test-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['smack-test-dev', 'python']

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-27901] CCC: Various build fixes

Cherry-picked-from-commit: 2d37116e4037dcaea2a6445a9dccf96d436c8549
Cherry-picked-from-branch: