qemu: resolve QA warnings about bash
:Release Notes:

:Detailed Notes:
ERROR: qemu-2.12.0-r0 do_package_qa: QA Issue: /usr/bin/qemu-mips contained in package qemu requires /bin/bash, but no providers found in RDEPENDS_qemu? [file-rdeps]
ERROR: qemu-2.12.0-r0 do_package_qa: QA Issue: /usr/lib/qemu/ptest/tests/qemu-iotests/check contained in package qemu-ptest requires /bin/bash, but no providers found in RDEPENDS_qemu-ptest? [file-rdeps]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-78082] Upgrade to Yocto 2.6 Thud
[PLAT-78507] [OSE] CCC: Upgrade to Yocto 2.6 Thud

Change-Id: I43c8972ccc1489242b58ed6c27c7b77d42b36dd1