packagegroup-{base,tools-bluetooth}: backport fixes preventing both bluez5 versions to the build
:Release Notes:
Backport changes from:
http://git.openembedded.org/openembedded-core/commit/?id=8b433f49c8ea153f75d986e5b9ad89dd3f625cba
http://git.openembedded.org/meta-openembedded/commit/?id=cf993a2c9e10dea286979850c4c5ecd751735ce8
necessary to build 5.48 correctly.

:Detailed Notes:
Fixes:
ERROR: Multiple versions of bluez5 are due to be built (
meta-webos-backports-2.5/recipes-connectivity/bluez5/bluez5_5.48.bb
oe-core/meta/recipes-connectivity/bluez5/bluez5_5.41.bb). Only one
version of a given PN should be built in any given build. You likely
need to set PREFERRED_VERSION_bluez5 to select the correct version or
don't depend on multiple versions.

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-62917] [OSE] CCC: rpi-config=webosrpi4
             Add bluetooth-sil-api=2,v1.0.0
             bluetooth-sil-bluez5=4,v0.1.0
             webos.service.bluetooth2=6,v1.0.0
[PLAT-51838] Upgrade bluez version from 5.41 to 5.48
[PLAT-52536] CCC: bluez5=v5.48