webos: qtbase=webos122
:Release Notes:
Respect DISTRO_FEATURES when setting PACKAGECONFIG and RRECOMMENDS.

:Detailed Notes:
ERROR: Nothing PROVIDES 'virtual/egl' (but
  meta-qt6/recipes-qt/qt6/qtbase_git.bb DEPENDS on or otherwise requires it)
vc-graphics PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics
vc-graphics-hardfp PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics-hardfp
ERROR: Nothing PROVIDES 'virtual/egl-native' (but
  virtual:native:meta-qt6/recipes-qt/qt6/qtbase_git.bb DEPENDS on or otherwise requires it). Close matches:
  virtual/libx11-native
  virtual/make-native
  virtual/mesa-native

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-22410] CCC: qtbase=webos122
[WRQ-7027] ...
[WRQ-8249] ...
[WRQ-7034] ...
[WRQ-17413] ...

Cherry-picked-from-commit: 30ed1d5ade81061bc2715b8e20f7494424951649
Cherry-picked-from-branch: