webos-smack: com.webos.app.test.smack.native=r7
:Release Notes:
Add ANY_OF_DISTRO_FEATURES restriction.

:Detailed Notes:
ERROR: Nothing RPROVIDES 'qml-webos-framework' (but
  meta-webos-smack/recipes-webos/com.webos.app.test.smack.native/com.webos.app.test.smack.native.bb
  RDEPENDS on or otherwise requires it)
qml-webos-framework was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-18608] CCC: com.webos.app.test.smack.native=r7
[WRQ-7027] ...
[WRQ-8249] ...
[WRQ-7034] ...
[WRQ-17413] ...

Cherry-picked-from-commit: 8e0590075f45353b225377175bed6bbdf666bfa5
Cherry-picked-from-branch: