iotivity: Remove @DEFINES@ and @LIBS@ from iotivity.pc
:Release Notes:

:Detailed Notes:
Fixes org.ocf.webossample.oc{client,server}basicops failing with:
scons: Building targets ...
scons: building associated VariantDir targets: out/webos/arm/release
scons: *** [out/webos/arm/release/resource/csdk/stack/samples/webos/secure/occlientbasicops/occlientbasicops] Implicit dependency `@DEFINES@' not found, needed by target `out/webos/arm/release/resource/csdk/stack/samples/webos/secure/occlientbasicops/occlientbasicops'.
scons: building terminated because of errors.
ERROR: scons build execution failed.

scons: Building targets ...
scons: building associated VariantDir targets: out/webos/arm/release
scons: *** [out/webos/arm/release/resource/csdk/stack/samples/webos/secure/occlientbasicops/occlientbasicops] Implicit dependency `@LIBS@' not found, needed by target `out/webos/arm/release/resource/csdk/stack/samples/webos/secure/occlientbasicops/occlientbasicops'.
scons: building terminated because of errors.
ERROR: scons build execution failed.

With scons upgraded in:
https://git.openembedded.org/openembedded-core/commit/?id=6fd0e96fca004ea7ec3441326ef0a601f36703c6

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12998] CCC: Upgrade to Yocto 3.4 Honister
[PLAT-141293] Create GPVB with Yocto 3.4 Honister

Change-Id: Iff77a2817506726369bfdaa324c8de6e87f60d98