lib{sm,xdamage,xext,xfixes,xmu,xpm,bsd}: drop unnecessary bbappends
:Release Notes:
All of this is already included in corresponding recipes.

:Detailed Notes:
libxext bbappend was actually breaking things, because it overrides
BBCLASSEXTEND and basically removes nativesdk from the recipe causing:

NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'nativesdk-libxext' (but
  virtual:nativesdk:libsdl_1.2.15.bb,
  virtual:nativesdk:libsdl2_2.0.5.bb DEPENDS on or otherwise requires
  it). Close matches:
  nativesdk-libxslt
  nativesdk-libevent
  nativesdk-libepoxy
NOTE: Runtime target 'nativesdk-qemu-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nativesdk-qemu-dev',
  'nativesdk-libsdl', 'nativesdk-libxext']

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-41150] Upgrade to Yocto 2.3 Pyro
[PLAT-41151] CCC: Upgrade to Yocto 2.3 Pyro
[PLAT-52479] Upgrade to Yocto 2.5 Sumo
[PLAT-78511] [OSE] CCC: Upgrade to Yocto 2.5 Sumo

Change-Id: I79b8f2b134e83b0a4c6c8513be6cd0e983dee088