meta-webos: add multimedia-layer to LAYERDEPENDS
:Release Notes:
Fix issues detected by yocto-check-layer.
The dependency was introduced with mediaindexer.

:Detailed Notes:
ERROR: Nothing PROVIDES 'libupnp' (but meta-webos/recipes-multimedia/com.webos.service.mediaindexer/com.webos.service.mediaindexer.bb DEPENDS on or otherwise requires it). Close matches:
  libndp
  libpcap
  libpng
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'com.webos.service.mediaindexer', 'libupnp']

:Testing Performed:
Build test done
CAT was passed

:QA Notes:
N/A

:Issues Addressed:
[PLAT-123586] CCC: ose: downgrade GPLv3 component
[PLAT-117224] Licenses GPL-3.0 and LGPL-3.0 found in OSE components
[PLAT-127791] Create meta-lg-gplv2 layer
[PLAT-128326] CCC: Introduce meta-lg-gplv2

Change-Id: Ib96861c1881f0b4452e887fc6d2194761ebf5ed7