com.webos.service.location: CMakeLists.txt: Fix hardcoded 'lib' installation path
:Release Notes:
With multilib enabled the libdir is usr/lib64 instead of usr/lib.

:Detailed Notes:
Respect WEBOS_INSTALL_LIBDIR to fix:
http://gecko.lge.com:8000/Errors/Details/574435

ERROR: QA Issue: com.webos.service.location: Files/directories were installed but not shipped in any package:
  /usr/lib/libdbutils.so
  /usr/lib/libdbutils.so.1.0.0
  /usr/lib/libdbutils.so.1
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
com.webos.service.location: 3 installed and not shipped files. [installed-vs-shipped]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-12446] CCC: Various build fixes
[WRP-12469] Bitbake world issues 2023-04-01

Cherry-picked-from-commit: 9eb5d7d71fb0891eb9cef72b6267ac8d7fc8e97d
Cherry-picked-from-branch: