mesa=webosrpi6 (update patch to apply on 20.3.1 version)
:Release Notes:

:Detailed Notes:
Update patch to apply to fix:
ERROR: mesa-2_20.3.1-r0 do_patch: Command Error: 'quilt --quiltrc /jenkins/mjansa/build/webos/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/mesa/2_20.3.1-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0001-implement-drm_create_linear_prime_buffer.patch
patching file include/GL/internal/dri_interface.h
Hunk #1 succeeded at 1585 (offset 6 lines).
patching file src/egl/drivers/dri2/egl_dri2.c
Hunk #1 succeeded at 3177 (offset -3 lines).
Hunk #2 succeeded at 3198 (offset -3 lines).
patching file src/egl/drivers/dri2/platform_android.c
Hunk #1 FAILED at 611.
1 out of 1 hunk FAILED -- rejects in file src/egl/drivers/dri2/platform_android.c
patching file src/egl/wayland/wayland-drm/meson.build
patching file src/egl/wayland/wayland-drm/wayland-drm.c
patching file src/egl/wayland/wayland-drm/wayland-drm.h
patching file src/egl/wayland/wayland-drm/wayland-drm.xml
patching file src/gallium/frontends/dri/dri2.c
Hunk #1 FAILED at 1357.
1 out of 1 hunk FAILED -- rejects in file src/gallium/frontends/dri/dri2.c
patching file src/gbm/backends/dri/gbm_dri.c
patching file src/loader/loader_dri3_helper.c
Hunk #1 succeeded at 1689 (offset 50 lines).
patching file src/mesa/drivers/dri/i915/intel_screen.c
patching file src/mesa/drivers/dri/i965/intel_screen.c
Hunk #1 succeeded at 1241 (offset 6 lines).
Patch 0001-implement-drm_create_linear_prime_buffer.patch does not apply (enforce with -f)
ERROR: Logfile of failure stored in: /jenkins/mjansa/build/webos/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/mesa/2_20.3.1-r0/temp/log.do_patch.72336
ERROR: Task (/jenkins/mjansa/build/webos/hardknott/oe-core/meta/recipes-graphics/mesa/mesa_20.3.1.bb:do_patch) failed with exit code '1'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12997] CCC: Upgrade to Yocto 3.3 Hardknott
[PLAT-124341] Create GPVB with Yocto 3.3 Hardknott

Change-Id: I612bc20c2e61b5b7693b4b69c5989225e79c6c05