webos_npm_env.bbclass: don't set 'dev' and 'strict-ssl', export NPM_ENV
:Release Notes:
Fix many warnings like:
npm WARN config dev Please use --include=dev instead.

:Detailed Notes:
It's repeated after each npm config call:

NOTE: webos_npm_env: set HOME to WORKDIR
NOTE: webos_npm_env: set npm cache
npm WARN config dev Please use --include=dev instead.
NOTE: webos_npm_env: clear npm cache and ${WORKDIR}/git/node_modules
npm WARN config dev Please use --include=dev instead.
npm WARN using --force Recommended protections disabled.
NOTE: webos_npm_env: config npm offline
npm WARN config dev Please use --include=dev instead.
NOTE: webos_npm_env: config npm package-lock
npm WARN config dev Please use --include=dev instead.
NOTE: webos_npm_env: config npm node-path
npm WARN config dev Please use --include=dev instead.
npm ERR! `scripts-prepend-node-path` is not a valid npm option

Also remove strict-ssl as it doesn't seem to do anything for a long
time.

Delete node-modules before clearing the cache, because that could fail with:
ERROR: nodejs-module-node-red-0.18.7-r3 do_compile: ExecutionError('/OE/lge/build/webos/mickledore/BUILD/work/qemux86_64-webos-linux/nodejs-module-node-red/0.18.7-r3/temp/run.do_compile.945566', 217, None, None)
ERROR: Logfile of failure stored in: /OE/lge/build/webos/mickledore/BUILD/work/qemux86_64-webos-linux/nodejs-module-node-red/0.18.7-r3/temp/log.do_compile.945566
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: webos_npm_env: set HOME to WORKDIR
| NOTE: webos_npm_env: set npm cache
| npm WARN config dev Please use --include=dev instead.
| NOTE: webos_npm_env: clear npm cache and /OE/lge/build/webos/mickledore/BUILD/work/qemux86_64-webos-linux/nodejs-module-node-red/0.18.7-r3/node-red-0.18.7/node_modules
| npm WARN config dev Please use --include=dev instead.
| npm WARN using --force Recommended protections disabled.
| npm ERR! code ENOTEMPTY
| npm ERR! syscall rmdir
| npm ERR! path /OE/lge/build/webos/mickledore/BUILD/work/qemux86_64-webos-linux/nodejs-module-node-red/0.18.7-r3/npm_cache/_cacache
| npm ERR! errno -39
| npm ERR! ENOTEMPTY: directory not empty, rmdir '/OE/lge/build/webos/mickledore/BUILD/work/qemux86_64-webos-linux/nodejs-module-node-red/0.18.7-r3/npm_cache/_cacache'
|
| npm ERR! A complete log of this run can be found in:
| npm ERR!     /OE/lge/build/webos/mickledore/BUILD/work/qemux86_64-webos-linux/nodejs-module-node-red/0.18.7-r3/npm_cache/_logs/2023-03-18T01_15_12_833Z-debug-0.log
| WARNING: exit code 217 from a shell command.
ERROR: Task (/OE/lge/build/webos/mickledore/meta-lg-webos/meta-webos/recipes-webos/nodejs-module-ext/nodejs-module-node-red_0.18.7.bb:do_compile) failed with exit code '1'

:Testing Performed:

:QA Notes:

:Issues Addressed:
[WRN-9458] NPM registry should be accessed over https now
[WRO-1567] WRN-9458 NPM registry should be accessed over https now
[WRP-10791] CCC: Various build fixes

Cherry-picked-from-commit: d28c6eba7ba192ddd95a155be1af8a0df35894b6
Cherry-picked-from-branch: