qemu: replace glx PACKAGECONFIG with epoxy
:Release Notes:
PACKAGECONFIG was renamed in:
https://git.openembedded.org/openembedded-core/commit/?id=0ded646a83768868a1cc4dceb962ee707348af1b

:Detailed Notes:
ERROR: nativesdk-qemu-6.2.0-r0 do_configure: QA Issue: nativesdk-qemu: invalid PACKAGECONFIG: glx [invalid-packageconfig]
ERROR: nativesdk-qemu-6.2.0-r0 do_configure: Fatal QA errors were found, failing task.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12999] CCC: Upgrade to Yocto 4.0 Kirkstone
[WRN-9820] Create GPVB with Yocto 4.0 Kirkstone

Change-Id: If4f62c2e1e9759d66c455a262ca56355c45622f5