webos_image.bbclass: let ostree to preserve /media and /opt
:Release Notes:
Drop strange mkdir in ${OSTREE_ROOTFS} directory (working directory of
IMAGE_CMD_ostree function - It doesn't seem to be needed and it causes
the failure when re-executed in the same dir. Instead copy the saved
.media directory to ${OSTREE_ROOTFS} in IMAGE_CMD_ostree instead of in
IMAGE_CMD_ota. Do the same with /opt (which is a symlink to /usr/opt).

:Detailed Notes:
Fixes:
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_image_ostree
| mkdir: cannot create directory 'media': File exists
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_image_ostree (log file is located at /jenkins/mjansa/build-webos-thud/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image/1.0-r3/temp/log.do_image_ostree.13722)
ERROR: Task (/jenkins/mjansa/build-webos-thud/meta-lg-webos/meta-webos/recipes-core/images/webos-image.bb:do_image_ostree) failed with exit code '1'

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-85669] CCC: Upgrade meta-updater to latest revision and fix it

Change-Id: Ibfdafc0034577595655ba678a277934a5835f84c