webos: qtwayland-webos=r21
:Release Notes:
Add ANY_OF_DISTRO_FEATURES restriction.

:Detailed Notes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'qtwayland' (but
  meta-webos/recipes-webos/qtwayland-webos/qtwayland-webos.bb
  DEPENDS on or otherwise requires it)
qtwayland was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'qtwayland-native' (but
  meta-webos/recipes-webos/qtwayland-webos/qtwayland-webos.bb
  DEPENDS on or otherwise requires it)
qtwayland-native was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-22410] CCC: qtwayland-webos=r21
[WRQ-7027] ...
[WRQ-8249] ...
[WRQ-7034] ...
[WRQ-17413] ...

Cherry-picked-from-commit: e687b8a37bc5cac6eb6c44e0654934fb380736c3
Cherry-picked-from-branch: