glibc: add LGPL-2.1-only & GPL-2.0-only to LICENSE
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: lib32-glibc-2.31+gitAUTOINC+3ef8be9b89-r0 do_package_qa: QA Issue:
  LICENSE_lib32-glibc-dev includes licenses (LGPL-2.1-only GPL-2.0-only)
  that are not listed in LICENSE [unlisted-pkg-lics]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-6542] CCC: Various build fixes

Change-Id: I1914d32a29793679ceacdbf5aca268acaaa20058