webos_enhanced_submissions.bbclass: assume name=main on first gitsm:// entry as well
:Release Notes:
In recipe which uses webos_enhanced_submissions.bbclass and has only 1
SRC_URI entry with gitsm:// it was triggering:
ERROR: foo-1.0 do_unpack: QA Issue: Recipe 'foo' (file 'meta-bar/recipes-foobar/foo/foo.bb')
  doesn't have git repository without 'name' parameter or with 'name=main' in SRC_URI,
  webos_enhanced_submission bbclass shouldn't be inherited here (it has nothing to do)
  [webos-enh-sub-warning]

:Detailed Notes:
Accept both git:// and gitsm://.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-14425] CCC: Various build fixes

Change-Id: Ib34beba71acd59bb48673f0db60998e8c401627a