qemux86: drop image-vm inherit and use wic.vmdk
:Release Notes:
image-vm.bbclass was dropped from oe-core and old vmdk support was
converted to CONVERSION_CMD, update image recipes accordingly.

:Detailed Notes:
Removed in oe-core commit:
  commit 929ba563f1bc7195c4981b8e139c432b2cc388ea
  Author: Tom Rini <trini@konsulko.com>
  Date:   Fri Jul 28 20:14:32 2017 -0400

    image: Convert vmdk/vdi/qcow2 to strict CONVERSION_CMD types

    The vmdk/vdi/qcow2 IMAGE_FSTYPEs predate wic.  As such, they provide
    some similar underlying functionality in order to produce a "disk" image
    that in turn can be converted into different formats that various
    hypervisor types work with.  They do not however provide the ability for
    other disk image types to be converted into these same output types.
    Furthermore, they are less flexible than what wic does provide.  This
    drops the old style vmdk/vdi/qcow2 types and re-introduces them under
    the CONVERSION_CMD framework.  The equivalent of vmdk is now wic.vmdk
    and so forth for the other types.

    Signed-off-by: Tom Rini <trini@konsulko.com>
    Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Also add dependency on do_deploy_fixup for image_wic, otherwise the task
will fail with:
INFO: Creating image(s)...

ERROR: _exec_cmd: install -m 0644 /home/jenkins/anaconda/
  build-foo-master/build/BUILD/deploy/images/qemux86/bzImage
  /home/jenkins/anaconda/build-foo-master/build/BUILD/work/
  qemux86-foo-linux/foo/1.0-r0.1.0/deploy-foo-image-complete
output: install: cannot stat /home/jenkins/anaconda/
  build-foo-master/build/BUILD/deploy/images/qemux86/bzImage: No
  such file or directory

as shown in http://caprica.lgsvl.com:8080/Errors/Details/824885

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-46229] Upgrade to Yocto 2.4 Rocko
[PLAT-78506] [OSE] CCC: Upgrade to Yocto 2.4 Rocko

Change-Id: Ied744646421ba0ef0fc880088c14411956c9e136