systemd=smack4 (update patch to apply on 249.1)
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: systemd-1_249.1-r0-lg1 do_patch: Fuzz detected:

Applying patch 0001-meson-add-smack-default-process-label-option.patch
patching file meson.build
Hunk #1 succeeded at 1017 with fuzz 2 (offset 145 lines).
patching file meson_options.txt
Hunk #1 succeeded at 332 (offset 91 lines).

The context lines in the patches can be updated with devtool:

    devtool modify systemd
    devtool finish --force-patch-refresh systemd <layer_path>

Don't forget to review changes done by devtool!

ERROR: systemd-1_249.1-r0-lg1 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

Adjust 0001-fileio.c-fix-build-with-smack-enabled.patch to include
src/shared, because after the cleanup from:
  commit 8d40961c3c64cbeebe8ca5b47693f277c6763e28
  Author: Yu Watanabe <watanabe.yu+github@gmail.com>
  Date:   Mon Jan 4 23:36:00 2021 +0900

    meson: slightly disentangle code dependencies

    But, still sd-id128 is used in src/basic.

the src/shared with smack-util.h is no longer included when
building src/basic.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-141293] Create GPVB with Yocto 3.4 Honister
[WRN-10062] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: Ia4ed473ef4e9c193ea15a1fd70fd9762f2b3f781