imemanager=r2 (add dependency on qtdeclarative-native)
:Release Notes:
Fixes:
http://caprica.lgsvl.com:8080/Builds/Details/4536049

:Detailed Notes:
| make[2]: *** No rule to make target '../../../recipe-sysroot-native/usr/bin/qmlcachegen', needed by 'qmlcache_loader.cpp'.  Stop.
| make[2]: *** Waiting for unfinished jobs....
| make[2]: Leaving directory '/jenkins/mjansa/build-webos-ose-master/BUILD/work/qemux86-webos-linux/imemanager/1.0.0-4-r0/build/maliit-plugin-global/plugin'
| Makefile:44: recipe for target 'sub-plugin-make_first' failed
| make[1]: *** [sub-plugin-make_first] Error 2
| make[1]: Leaving directory '/jenkins/mjansa/build-webos-ose-master/BUILD/work/qemux86-webos-linux/imemanager/1.0.0-4-r0/build/maliit-plugin-global'
| Makefile:44: recipe for target 'sub-maliit-plugin-global-make_first-ordered' failed
| make: *** [sub-maliit-plugin-global-make_first-ordered] Error 2
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /jenkins/mjansa/build-webos-ose-master/BUILD/work/qemux86-webos-linux/imemanager/1.0.0-4-r0/temp/log.do_compile.2690)
ERROR: Task (/jenkins/mjansa/build-webos-ose-master/meta-webosose/meta-webos/recipes-webos/imemanager/imemanager.bb:do_compile) failed with exit code '1'

:Testing Performed:
Only build tested.

:QA Notes:

:Build Notes:

:Issues Addressed:
[PLAT-67557] Upgrade to Qt 5.11.3
[PLAT-78100] CCC: Upgrade to Qt 5.12.3

Change-Id: Id323c9c1d29b21b9cbcb55c29db923615386c0bd