webos: luna-service2=r35
:Release Notes:
The changes from:
[WRR-3997] Integrate new API of luna service on webOS OSE
[WRR-6016] CCC: luna-service2=44
broke the build with gcc-14

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/984690
luna-service2/3.21.2-44/git/src/libluna-service2/transport_message.c:1249:12: error: implicit declaration of function '_LSTransportSendQueryPid'; did you mean '_LSTransportSendReply'? [-Wimplicit-function-declaration]
luna-service2/3.21.2-44/git/src/libluna-service2/transport_message.c:1265:12: error: implicit declaration of function '_LSTransportSendQueryUid'; did you mean '_LSTransportSendReply'? [-Wimplicit-function-declaration]
luna-service2/3.21.2-44/git/src/libluna-service2/transport_message.c:1281:12: error: implicit declaration of function '_LSTransportSendQueryGid'; did you mean '_LSTransportSendReply'? [-Wimplicit-function-declaration]
luna-service2/3.21.2-44/git/src/libluna-service2/transport_message.c:1300:12: error: implicit declaration of function '_LSTransportSendQueryProcessInfo'; did you mean 'LSTransportSendQueryServiceStatus'? [-Wimplicit-function-declaration]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-3681] CCC: luna-service2=r35
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead

Cherry-picked-from-commit: 4c04af5d7c1dfcd739350e5b227312a8413817a0
Cherry-picked-from-branch: