busybox=webos12 (disable w, fallocate, fsfreeze, mke2fs, nsenter, unshare, link applets)
:Release Notes:
Like it was disabled in default busybox defconfig in 1.27.2 upgrade:
http://git.openembedded.org/openembedded-core/diff/meta/recipes-core/busybox/busybox/defconfig?id=55740077a1f3bed5956fe02ef17ba1d99176ea24
but we have our own defconfig which was still enabling them

:Detailed Notes:
Fixes following issues in do_rootfs:
w causes conflict with procps:
update-alternatives: Error: not linking webos-image/1.0-r3/rootfs/usr/bin/w to /bin/busybox.nosuid since webos-image/1.0-r3/rootfs/usr/bin/w exists and is not a link

fallocate causes conflict with util-linux:
update-alternatives: Error: not linking webos-image/1.0-r3/rootfs/usr/bin/fallocate to /bin/busybox.nosuid since webos-image/1.0-r3/rootfs/usr/bin/fallocate exists and is not a link

fsfreeze causes conflict with util-linux:
update-alternatives: Error: not linking webos-image/1.0-r3/rootfs/usr/sbin/fsfreeze to /bin/busybox.nosuid since webos-image/1.0-r3/rootfs/usr/sbin/fsfreeze exists and is not a link

mke2fs causes conflict with e2fsprogs-mke2fs:
update-alternatives: Error: not linking webos-image/1.0-r3/rootfs/sbin/mke2fs to /bin/busybox.nosuid since webos-image/1.0-r3/rootfs/sbin/mke2fs exists and is not a link

nsenter causes conflict with util-linux:
update-alternatives: Error: not linking webos-image/1.0-r3/rootfs/usr/bin/nsenter to /bin/busybox.nosuid since webos-image/1.0-r3/rootfs/usr/bin/nsenter exists and is not a link

unshare causes conflict with util-linux:
update-alternatives: Error: not linking webos-image/1.0-r3/rootfs/usr/bin/unshare to /bin/busybox.nosuid since webos-image/1.0-r3/rootfs/usr/bin/unshare exists and is not a link

link causes conflict with coreutils (only in -devel images), because busybox installs it to /bin/link and coreutils to /usr/bin/link:
update-alternatives: renaming link link from /bin/link to /usr/bin/link
mv: cannot stat ?/bin/link?: No such file or directory

which for read-only image builds cause whole image to fail:
Details of the failure are in webos-image-devel/1.0-r0.4.1/temp/log.do_rootfs.
WARNING: webos-image-devel-1.0-r0.4.1 do_rootfs: busybox.postinst returned 1, marking as unpacked only, configuration required on target.
WARNING: webos-image-devel-1.0-r0.4.1 do_rootfs: coreutils.postinst returned 1, marking as unpacked only, configuration required on target.
WARNING: webos-image-devel-1.0-r0.4.1 do_rootfs: Intentionally failing postinstall scriptlets of ['busybox', 'coreutils'] to defer them to first boot is deprecated. Please place them into pkg_postinst_ontarget_${PN} ().
If deferring to first boot wasn't the intent, then scriptlet failure may mean an issue in the recipe, or a regression elsewhere.
Details of the failure are in webos-image-devel/1.0-r0.4.1/temp/log.do_rootfs.
ERROR: webos-image-devel-1.0-r0.4.1 do_rootfs: The following packages could not be configured offline and rootfs is read-only: ['busybox', 'coreutils']
ERROR: webos-image-devel-1.0-r0.4.1 do_rootfs: Function failed: do_rootfs
ERROR: Logfile of failure stored in: webos-image-devel/1.0-r0.4.1/temp/log.do_rootfs.4904
NOTE: recipe webos-image-devel-1.0-r0.4.1: task do_rootfs: Failed
ERROR: Task (webos-image-devel.bb:do_rootfs) failed with exit code '1'

CONFIG_FEATURE_BASH_IS_ASH was renamed to CONFIG_BASH_IS_ASH in busybox
1.27.0 with this commit:
https://git.busybox.net/busybox/commit/?id=0b8835861b2e43cb45becdb560877bcc89aea827
which got included with upgrade to 1.27.2 in Yocto 2.5 Sumo commit:
http://git.openembedded.org/openembedded-core/commit/?id=55740077a1f3bed5956fe02ef17ba1d99176ea24
fixes many file-rdeps errors about /bin/bash

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-52479] Upgrade to Yocto 2.5 Sumo
[PLAT-78511] [OSE] CCC: Upgrade to Yocto 2.5 Sumo

Change-Id: I3e6041cea93e250ebbf4a8b2fdf8954109337274