ls2-helpers: CMakeLists.txt: replace -std=c++11 with -std=c++14
:Release Notes:
c++11 isn't compatible with googletest currently in mickledore.

:Detailed Notes:
With googletest 1.13.0 from:
https://git.openembedded.org/meta-openembedded/commit/?id=46266e59ff36b38f46a67573528cee658960c764
it fails to build with:
http://gecko.lge.com:8000/Errors/Details/564314

FAILED: Imported/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++  -ITOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/git/src -ITOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/git/include/public/ls2-helpers -ITOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/git/include/public -isystem TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot/usr/src/gtest/include -isystem TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot/usr/src/gtest -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/git=/usr/src/debug/ls2-helpers/1.0.0-1-r3  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/git=/usr/src/debug/ls2-helpers/1.0.0-1-r3  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/build=/usr/src/debug/ls2-helpers/1.0.0-1-r3  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/build=/usr/src/debug/ls2-helpers/1.0.0-1-r3  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot-native=  -fvisibility-inlines-hidden  -std=c++11 -Wall -Wextra -fno-permissive -Wno-unused-parameter -Wno-type-limits, -Wno-missing-field-initializers -Werror=return-type -Werror=reorder -Werror=uninitialized -Wl,--no-undefined -ITOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot/usr/lib/glib-2.0/include -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot/usr/lib/glib-2.0/include -DNDEBUG -Wall -Wshadow -Wno-error=dangling-else -DGTEST_HAS_PTHREAD=1 -fexceptions -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -MD -MT Imported/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o -MF Imported/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o.d -o Imported/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o -c TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot/usr/src/gtest/src/gtest_main.cc
In file included from TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot/usr/include/gtest/gtest-message.h:57,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot/usr/include/gtest/gtest-assertion-result.h:46,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot/usr/include/gtest/gtest.h:64,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot/usr/src/gtest/src/gtest_main.cc:32:
TOPDIR/BUILD/work/qemux86_64-webos-linux/ls2-helpers/1.0.0-1-r3/recipe-sysroot/usr/include/gtest/internal/gtest-port.h:270:2: error: #error C++ versions less than C++14 are not supported.
  270 | #error C++ versions less than C++14 are not supported.
      |  ^~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-412] Create GPVB with Yocto 4.2 Mickledore
[WRP-12233] googletest-1.13.0 no longer supports -std=c++11 and older
[WRP-12449] CCC: Use C++ 2014 to support googletest-1.13.0

Cherry-picked-from-commit: 974eeb4be47882fe4487dc923e0f90999a8ed587
Cherry-picked-from-branch: