webos_oss_pkg_info.bbclass: Fix to the correct path to find license.manifest
:Release Notes:

:Detailed Notes:
license.manifest file is under IMAGE_NAME path not IMAGE_BASENAME path
When we use IMAGE_BASENAME path to find license.manifest, the production
builds which has MANUFACTURING_VERSION causes build error like

DEBUG: Executing python function do_write_oss_pkg_info
ERROR: There is no TOPDIR/BUILD/deploy/licenses/${IMAGE_BASENAME}/license.manifest
DEBUG: Python function do_write_oss_pkg_info finished

:Testing Performed:
Only build test

:QA Notes:
N/A

:Issues Addressed:
[WRN-17751] Fix build error when manufacturing version is set

Change-Id: I8dfd178ee3d4213699aab42b80c0057b06a63ea4