webos: node-red=r1 (fix symlink-to-sysroot and staticdev QA issues)
:Release Notes:
Fails in multilib builds where libdir != base_libdir.
Submitted upstream in:
https://github.com/intel-iot-devkit/meta-iot-cloud/pull/167

:Detailed Notes:
npm.bbclass copies the 'lib' into nonarch_libdir not regular libdir:
https://git.openembedded.org/openembedded-core/tree/meta/classes-recipe/npm.bbclass?h=scarthgap#n310

on builds where libdir != nonarch_libdir (e.g. with multilib) this
fails, because build-tmp-napi-v3 wasn't removed in do_install:

http://gecko.lge.com:8000/Errors/Details/792401

ERROR: QA Issue: Symlink /usr/lib/node_modules/node-red/node_modules/bcrypt/build-tmp-napi-v3/node_gyp_bins/python3 in node-red points to TMPDIR [symlink-to-sysroot]
ERROR: QA Issue: non -staticdev package contains static .a library: node-red path '/usr/lib/node_modules/node-red/node_modules/bcrypt/build-tmp-napi-v3/Release/nothing.a'
non -staticdev package contains static .a library: node-red path '/usr/lib/node_modules/node-red/node_modules/bcrypt/build-tmp-napi-v3/Release/node-addon-api/nothing.a' [staticdev]

add -v to show in the logs what is being removed

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-13879] CCC: node-red=r1 (fix symlink-to-sysroot and staticdev QA issues)

Cherry-picked-from-commit: f13a822112eaa8a76791dcb645f370db7a00b2e8
Cherry-picked-from-branch: