webos-recipe-blacklist.inc: blacklist ceph because of xfsprogs
:Release Notes:
Fix issues detected by yocto-check-layer.
ceph depends on already blacklisted xfsprogs.

:Detailed Notes:
ERROR: Nothing PROVIDES 'xfsprogs' (but meta-virtualization/recipes-extended/ceph/ceph_15.2.0.bb DEPENDS on or otherwise requires it)
xfsprogs was skipped: Recipe is blacklisted: ERROR: xfsprogs-4.18.0-r0 do_package: QA Issue: xfsprogs: Files/directories were installed but not shipped in any package:
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'ceph', 'xfsprogs']

:Testing Performed:
Build test done
CAT was passed

:QA Notes:
N/A

:Issues Addressed:
[PLAT-123586] CCC: ose: downgrade GPLv3 component
[PLAT-117224] Licenses GPL-3.0 and LGPL-3.0 found in OSE components
[PLAT-127791] Create meta-lg-gplv2 layer
[PLAT-128326] CCC: Introduce meta-lg-gplv2

Change-Id: I945e61c78f0a2b41ae7e8966bef0fd8470fcdf55