rpi: userland: refresh the patches for 20190724 version
:Release Notes:

:Detailed Notes:
ERROR: userland-20190724-r0 do_patch: Fuzz detected:

Applying patch 0002-Remove-EGL-dependency.patch
patching file CMakeLists.txt
patching file host_applications/linux/CMakeLists.txt
patching file interface/vmcs_host/CMakeLists.txt
Hunk #1 succeeded at 24 with fuzz 1 (offset -2 lines).
patching file makefiles/cmake/vmcs.cmake

The context lines in the patches can be updated with devtool:

    devtool modify userland
    devtool finish --force-patch-refresh userland <layer_path>

Don't forget to review changes done by devtool!

ERROR: userland-20190724-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-84805] Create GPVB with Yocto 3.0 Zeus
[PLAT-77937] Create GPVB with Yocto 2.7
[PLAT-80962] Upgrade linux-raspberrpi to 4.19
[PLAT-86843] CCC: Various build fixes

Change-Id: I87682d79931cdbdd8ba2767c6717906c67e016c1