webos: libcec=webosrpi5 omx-components=r3 g-media-pipeline=r20 media-codec-interface=r14 g-camera-pipeline=r18
:Release Notes:
Add ANY_OF_DISTRO_FEATURES restriction.

:Detailed Notes:
ERROR: Nothing PROVIDES 'virtual/libomxil' (but
  meta-oe/meta-oe/recipes-extended/libcec/libcec_6.0.2.bb,
  meta-webos/recipes-multimedia/media-codec-interface/media-codec-interface.bb,
  meta-webos/recipes-multimedia/g-media-pipeline/g-media-pipeline.bb,
  meta-webos/recipes-multimedia/media-codec-interface/media-codec-interface-clang.bb,
  meta-webos/recipes-multimedia/g-media-pipeline/g-media-pipeline-clang.bb,
  meta-webos-raspberrypi/recipes-multimedia/omx-components/omx-components.bb DEPENDS on or otherwise requires it)
libomxil PROVIDES virtual/libomxil but was skipped: PREFERRED_PROVIDER_virtual/libomxil set to userland, not libomxil
userland PROVIDES virtual/libomxil but was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'userland' (but
  meta-webos/recipes-webos/g-camera-pipeline/g-camera-pipeline.bb DEPENDS on or otherwise requires it)
userland was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-19081] CCC: libcec=webosrpi5 omx-components=r3 g-media-pipeline=r20 media-codec-interface=r14 g-camera-pipeline=r18
[WRQ-7027] ...
[WRQ-8249] ...
[WRQ-7034] ...
[WRQ-17413] ...

Cherry-picked-from-commit: 027e3ea83295e48c43caddc73e98ab6501d3bab6
Cherry-picked-from-branch: