solana-program-library: add openssl dependency and export OPENSSL_NO_VENDOR
:Release Notes:
Need to export OPENSSL_NO_VENDOR to avoid:
https://github.com/sfackler/rust-openssl/issues/1430

:Detailed Notes:
OPENSSL_NO_VENDOR fixes:
http://gecko.lge.com/Errors/Details/474955
error: failed to run custom build command for `openssl-sys v0.9.72`

Caused by:
  process didn't exit successfully: `TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/solana-program-library/2.1.1-r0/build/target/release/build/openssl-sys-b8a5ceb42f20f63e/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=AARCH64_WEBOS_LINUX_GNU_OPENSSL_NO_VENDOR
  AARCH64_WEBOS_LINUX_GNU_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset

  --- stderr
  thread 'main' panicked at 'don't know how to configure OpenSSL for aarch64-webos-linux-gnu', TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/solana-program-library/2.1.1-r0/cargo_home/bitbake/openssl-src-111.22.0+1.1.1q/src/lib.rs:294:18
  stack backtrace:

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12360] Prepare CCC for the solana NFT minting based on build-webos yocto 4.0
[WRO-14510] CCC: Various build fixes

Change-Id: I651afa868bb7fd584fa856d39f5b248bde3c3ed1