packagegroup-webos-extended: respect VIRTUAL-RUNTIME_bluetooth_service variable
:Release Note:
Fix changes from PLAT-83731. VIRTUAL-RUNTIME_bluetooth_service should
pull all necessary dependencies, e.g. in webos-qemux86 build it will be
webos.service.bluetooth2, bluetooth-sil-api, bluetooth-sil-bluez5
bluez5 was already included in the image as connman runtime dependency
bluez5-obex would be included if emulator has FTP in
WEBOS_BLUETOOTH_ENABLED_SERVICE_CLASSES:
meta-webos/recipes-webos/bluetooth/bluetooth-sil-bluez5.bb:
RDEPENDS_${PN} += "${@ bb.utils.contains('WEBOS_BLUETOOTH_ENABLED_SERVICE_CLASSES', 'FTP', 'bluez5-obex', '', d)}"

currently only rpi MACHINEs have FTP:
meta-webos-raspberrypi/conf/machine/include/webos-rpi.inc:WEBOS_BLUETOOTH_ENABLED_SERVICE_CLASSES = "SPP GATT FTP OPP A2DP"
meta-webos/recipes-webos/bluetooth/bluetooth-sil-bluez5.bb:WEBOS_BLUETOOTH_ENABLED_SERVICE_CLASSES ??= ""

:Detailed Notes:
In some DISTROs bluez5 is blacklisted, leading to following errors:
ERROR: Nothing RPROVIDES 'lib32-bluez5' (but virtual:multilib:lib32:meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb RDEPENDS on or otherwise requires it)
lib32-bluez5 was skipped: Recipe is blacklisted: <something-else> is preferred in <distro> builds
NOTE: Runtime target 'lib32-bluez5' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-bluez5']
NOTE: Runtime target 'lib32-packagegroup-webos-extended' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-packagegroup-webos-extended', 'lib32-bluez5']
ERROR: Nothing RPROVIDES 'lib32-bluez5-obex' (but virtual:multilib:lib32:meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'lib32-bluez5-obex' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-bluez5-obex']

:Testing Performed:

:QA Notes:
N/A

:Issues Addressed:
[PLAT-83731] CCC : Add {kernel-module-rfcomm kernel-module-btusb
             kernel-module-bluetooth kernel-module-btbcm
             kernel-module-hci-uart}=4.18.33 {bluez5 bluez5-obex}=5.50
             linux-yocto_4.18=9
[PLAT-84846] Implementation Bluetooth for OSE virtualbox emulator.
[PLAT-85555] CCC: Various build fixes

Change-Id: I29967ef7379efea715f692d73457bb2f7ff0e7c4