webos: webos-raspberrypi: nyx-modules=webosrpi8
:Release Notes:
Respect DISTRO_FEATURES when enabling NYXMOD_OW_CEC.

:Detailed Notes:
ERROR: Nothing RPROVIDES 'libcec-examples' (but
  meta-webos/recipes-webos/nyx-modules/nyx-modules.bb
  RDEPENDS on or otherwise requires it)
libcec RPROVIDES libcec-examples but was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES
NOTE: Runtime target 'libcec-examples' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libcec-examples']
NOTE: Runtime target 'nyx-modules' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nyx-modules', 'libcec-examples']
NOTE: Runtime target 'packagegroup-core-boot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-core-boot', 'nyx-modules', 'libcec-examples']
ERROR: Nothing RPROVIDES 'nyx-modules-dev' (but
  meta-webos/recipes-webos/nyx-modules/nyx-modules.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'nyx-modules-dev'
NOTE: Runtime target 'nyx-modules-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nyx-modules-dev']

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-19081] CCC: webos-raspberrypi: nyx-modules=webosrpi8
[WRQ-7027] ...
[WRQ-8249] ...
[WRQ-7034] ...
[WRQ-17413] ...

Cherry-picked-from-commit: cfd20803ac6743ec245fbf9e98d4b829318b6cfd
Cherry-picked-from-branch: