webos: gator-mod=r*.4 (gator_fs: Fix build with linux-6.10 and newer)
:Release Notes:
In linux commit 12cd44023651666bd44baa36a5c999698890debb:
https://github.com/torvalds/linux/commit/12cd44023651666bd44baa36a5c9996
98890debb

i_atime and i_mtime were renamed to avoid direct access

with additional changes in:
https://lore.kernel.org/all/20240517-amtime-v1-1-
7b804ca4be8f@kernel.org/

:Detailed Notes:
fixes:
http://gecko.lge.com:8000/Errors/Details/926806

../../../work/qemux86_64-webos-linux/gator-
mod/6.7+git/git/driver/gator_fs.c: In function 'gatorfs_get_inode':
../../../work/qemux86_64-webos-linux/gator-
mod/6.7+git/git/driver/gator_fs.c:48:16: error: 'struct inode' has no
member named 'i_atime'; did you mean '__i_atime'?
   48 |         inode->i_atime = inode->i_mtime = current_time(inode);
      |                ^~~~~~~
      |                __i_atime
../../../work/qemux86_64-webos-linux/gator-
mod/6.7+git/git/driver/gator_fs.c:48:33: error: 'struct inode' has no
member named 'i_mtime'; did you mean '__i_mtime'?
   48 |         inode->i_atime = inode->i_mtime = current_time(inode);
      |                                 ^~~~~~~
      |                                 __i_mtime
../../../work/qemux86_64-webos-linux/gator-
mod/6.7+git/git/driver/gator_fs.c:49:45: error: 'struct inode' has no
member named 'i_mtime'; did you mean '__i_mtime'?
   49 |         inode_set_ctime_to_ts(inode, inode->i_mtime);
      |                                             ^~~~~~~
      |                                             __i_mtime

And

strlcpy was finally removed in:
https://github.com/torvalds/linux/commit/d26270061ae66b915138af7cd73ca6f
8b85e6b44

fixes:
http://gecko.lge.com:8000/Errors/Details/926808

In file included from ../../../work/qemux86_64-webos-linux/gator-
mod/6.7+git/git/driver/gator_main.c:268:
../../../work/qemux86_64-webos-linux/gator-
mod/6.7+git/git/driver/gator_trace_sched.c: In function 'emit_pid_name':
../../../work/qemux86_64-webos-linux/gator-
mod/6.7+git/git/driver/gator_trace_sched.c:105:13: error: implicit
declaration of function 'strlcpy'; did you mean 'strncpy'? [-Wimplicit-
function-declaration]
  105 |         if (strlcpy(taskcomm, comm, TASK_COMM_LEN) ==
TASK_COMM_LEN - 1) {
      |             ^~~~~~~
      |             strncpy

after linux-libc-headers were updated to v6.10 in:
https://git.openembedded.org/openembedded-
core/commit/?id=3f852c2c958c80c652e902ab0532cefdc82e6549

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-33135] CCC: gator-mod=r*.4 (gator_fs: Fix build with linux-6.10 and
            newer)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRP-32155] Fix gator to build with 6.10 kernel

Cherry-picked-from-commit: f312c8b1f0e48612b10c7db1f823f204ac850d15
Cherry-picked-from-branch: