tensorflow-lite=r2 (dlopen libOpenCL.so.1)
Release Notes:
opencl-icd-loader creates libOpenCL.so.1 and libOpenCL.so is symlink to it, which is
correctly packaged in $PN-dev, not $PN, so it's not installed by default.

Then benchmark_model incorrectly tries to dlopen libOpenCL.so instead of
libOpenCL.so.1 which fails, instead of changing opencl-icd-loader packaging
fix the opencl_wrapper.

:Detailed Notes:
Fixes:
$ benchmark_model --graph=/usr/share/aif/model/pose_landmark_lit e.tflite --use_gpu=true
STARTING! Log parameter values verbosely: [0]
Graph: [/usr/share/aif/model/pose_landmark_lite.tflite]
Use gpu: [1]
Loaded model /usr/share/aif/model/pose_landmark_lite.tflite
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite delegate for GPU.
GPU delegate created. Going to apply 1 delegates one after another.
ERROR: Can not open OpenCL library on this device - libOpenCL.so: cannot open shared object file: No such file or directory
ERROR: Falling back to OpenGL
ERROR: TfLiteGpuDelegate Init: OpenGL-based API disabled
INFO: Created 0 GPU delegate kernels.
ERROR: TfLiteGpuDelegate Prepare: delegate is not initialized ERROR: Node number 305 (TfLiteGpuDelegateV2) failed to prepare.
ERROR: Restored original execution plan after delegate application failure. Failed to apply GPU delegate. Benchmarking failed.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-4984] CCC: Various build fixes

Change-Id: Iaf61314f927a45fb28ecbac553ff0e86e380afef