sed: rename bbappend to match new version
* oe-core/master now has 4.8 version (upgraded from 4.2.2)
  meta-gplv2 has 4.1.2 version, cannot use % wildcard to cover all
  versions, because 4.1.2 doesn't support --without-selinux
  ERROR: sed-4.1.2-r7 do_configure: QA Issue: sed: configure was passed unrecognised options: --without-selinux [unknown-configure-option]

[PLAT-115145] CCC: Upgrade to Yocto 3.1 Dunfell

Change-Id: Ie30f976279244b420854b69d8674c1799f76f43e