kernel-selftest=webos2 (resolve QA error)
:Release Notes:
Fix QA error which happens when bash is built before kernel-selftest.

:Detailed Notes:
Fixes:
ERROR: QA Issue: lib32-kernel-selftest rdepends on lib32-bash, but it
isn't a build dependency, missing lib32-bash in DEPENDS or
PACKAGECONFIG? [build-deps]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-78942] CCC: Various build fixes
[PLAT-81507] [OSE] CCC: Import few more changes

Change-Id: I0d77227e12169e3deefca22f85b622628df9b17c