webos: webos-recipe-blacklist.inc: skip dialog-lvgl
:Release Notes:
Not compatible with lvgl-9 from
meta-webos-backports-5.0/recipes-graphics/lvgl

:Detailed Notes:
The recipe was added in langdale with:
https://git.openembedded.org/meta-openembedded/commit/?id=8d75eff6af0fd6ccf8a45b5c98c4a0194e292a2f
and removed from meta-oe in scarthgap:
https://git.openembedded.org/meta-openembedded/commit/?id=e4865f3ee0df8ad9f789a9612f8cb7147992222b"

NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'lv-drivers' (but
  meta-oe/meta-oe/recipes-graphics/lvgl/dialog-lvgl_git.bb
  DEPENDS on or otherwise requires it)
lv-drivers was skipped: Recipe will be skipped because: not compatible with lvgl-9 from meta-webos-backports-5.0/recipes-graphics/lvgl, the recipe was removed from meta-oe in scarthgap http://gecko.lge.com:8000/Errors/Details/867539
ERROR: Nothing RPROVIDES 'dialog-lvgl' (but
  meta-oe/meta-oe/recipes-graphics/lvgl/dialog-lvgl_git.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dialog-lvgl'
NOTE: Runtime target 'dialog-lvgl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dialog-lvgl']
ERROR: Nothing RPROVIDES 'dialog-lvgl-dev' (but
  meta-oe/meta-oe/recipes-graphics/lvgl/dialog-lvgl_git.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'dialog-lvgl-dev'
NOTE: Runtime target 'dialog-lvgl-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dialog-lvgl-dev']

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-28942] CCC: webos-recipe-blacklist.inc: skip dialog-lvgl

Cherry-picked-from-commit: dd12beb1d4f5efe105277faf85ede3f041db6e60
Cherry-picked-from-branch: