qtbase, umediaserver: Fix parsing without webos as a DISTRO
:Release Notes:
Make sure that WEBOS_DISTRO_PRERELEASE is defined before being used.

:Detailed Notes:
Fixes:
ERROR: /jenkins/mjansa/build-webos-ose-thud/meta-qt5/recipes-qt/qt5/qtbase_git.bb: Error executing a python function in <code>:

The stack trace of python calls that resulted in this exception/failure was:
File: '<code>', lineno: 2, function: <module>
     0001:__anon_25__jenkins_mjansa_build_webos_ose_thud_oe_core_meta_classes_patch_bbclass(d)
 *** 0002:__anon_688__jenkins_mjansa_build_webos_ose_thud_oe_core_meta_classes_base_bbclass(d)
     0003:__anon_1186__jenkins_mjansa_build_webos_ose_thud_oe_core_meta_classes_insane_bbclass(d)
     0004:__anon_251__jenkins_mjansa_build_webos_ose_thud_oe_core_meta_classes_package_bbclass(d)
     0005:__anon_264__jenkins_mjansa_build_webos_ose_thud_oe_core_meta_classes_package_ipk_bbclass(d)
     0006:__anon_25__jenkins_mjansa_build_webos_ose_thud_oe_core_meta_classes_debian_bbclass(d)
File: '/jenkins/mjansa/build-webos-ose-thud/oe-core/meta/classes/base.bbclass', lineno: 585, function: __anon_688__jenkins_mjansa_build_webos_ose_thud_oe_core_meta_classes_base_bbclass
     0581:    needsrcrev = False
     0582:    srcuri = d.getVar('SRC_URI')
     0583:    for uri in srcuri.split():
     0584:        (scheme, _ , path) = bb.fetch.decodeurl(uri)[:3]
 *** 0585:
     0586:        # HTTP/FTP use the wget fetcher
     0587:        if scheme in ("http", "https", "ftp"):
     0588:            d.appendVarFlag('do_fetch', 'depends', ' wget-native:do_populate_sysroot')
     0589:
File: '/jenkins/mjansa/build-webos-ose-thud/bitbake/lib/bb/fetch2/__init__.py', lineno: 368, function: decodeurl
     0364:    """
     0365:
     0366:    m = re.compile('(?P<type>[^:]*)://((?P<user>[^/;]+)@)?(?P<location>[^;]+)(;(?P<parm>.*))?').match(url)
     0367:    if not m:
 *** 0368:        raise MalformedUrl(url)
     0369:
     0370:    type = m.group('type')
     0371:    location = m.group('location')
     0372:    if not location:
Exception: bb.fetch2.MalformedUrl: The URL: '${@''' is invalid and cannot be interpreted

ERROR: Failed to parse recipe: /jenkins/mjansa/build-webos-ose-thud/meta-qt5/recipes-qt/qt5/qtbase_git.bb

Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

ERROR: Nothing PROVIDES '${@''' (but /jenkins/mjansa/build-webos-ose-thud/meta-webosose/meta-webos/recipes-webos/umediaserver/umediaserver.bb DEPENDS on or otherwise requires it)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'g-media-pipeline', 'umediaserver', "${@''"]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-79498] [OSE] CCC: Fix metadata parsing without webos as a DISTRO

Change-Id: I0d05e3afdcec8c5560d496ee177f44ed5b94f86c