busybox: refresh patches to apply cleanly on 1.31.1
* Fixes:
ERROR: busybox-1.31.1-r0 do_patch: Fuzz detected:

Applying patch 0002-date-add-support-for-options-U-and-S.patch
patching file coreutils/date.c
Hunk #1 succeeded at 99 (offset -1 lines).
Hunk #2 succeeded at 141 (offset -1 lines).
Hunk #3 succeeded at 149 (offset -1 lines).
Hunk #4 succeeded at 195 (offset -1 lines).
Hunk #5 succeeded at 272 with fuzz 1 (offset -1 lines).
Hunk #7 succeeded at 347 (offset 1 line).

The context lines in the patches can be updated with devtool:

    devtool modify busybox
    devtool finish --force-patch-refresh busybox <layer_path>

Don't forget to review changes done by devtool!

[PLAT-115145] CCC: Upgrade to Yocto 3.1 Dunfell

Change-Id: Ib5e082325328d5ea5c305f13b65db4fc18e7279d