gst*: set PREFERRED_VERSION and use 1.16 from oe-core instead of 1.18 from meta-webos-backports-3.3
:Release Notes:
Now with meta-webos-backports-3.3 layer included in webos builds
it would build 1.18 by default, but e.g. g-media-pipeline fails
to build and needs to be updated by multimedia team first.

:Detailed Notes:
g-media-pipeline:
http://gecko.lge.com:8000/Errors/Details/419151

g-media-pipeline/1.0.0-21.gav.28-r10/git/src/player/BufferPlayer.cpp:269:19: error: 'gst_pipeline_get_base_time' was not declared in this scope; did you mean 'gst_element_get_base_time'?
  269 |     newBaseTime = gst_pipeline_get_base_time ((GstPipeline *) pipeline_, /*start-time*/0);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   gst_element_get_base_time

gstreamer1.0-plugins-good (with meta-qt5):
http://gecko.lge.com:8000/Errors/Details/419164
meson: error: unrecognized arguments: --disable-qt

gstreamer1.0-plugins-bad (with meta-gplv2):
http://gecko.lge.com:8000/Errors/Details/419163
ext/hls/meson.build:48:4: ERROR: Problem encountered: HLS plugin enabled with crypto, but crypto library "nettle" not found

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-6542] CCC: Various build fixes

Change-Id: I36f9dbc1f3d88a5b7f45cbf9236406df0fd86eaa