webos: bluetooth-sil-bluez5=r12
:Release Notes:
Remove SECURITY_STRINGFORMAT from meta-layer

:Detailed Notes:
Address below build issue with
http://gpro.lge.com/c/webosose/
bluetooth-sil-bluez5/+/211963/1/src/
bluez5advertise.cpp

bluez5advertise.cpp:191:41: error: format not a string
literal and no format arguments [-Werror=format-security]
bluez5advertise.cpp:192:46: error: format not a string
literal and no format arguments [-Werror=format-security]

So SECURITY_STRINGFORMAT flag no longer require and
remove from meta-layer

:Testing Performed:
Build Successful.Verified locally.

:QA Notes:
N/A

:Issues Addressed:
[WRR-10234] CCC: bluetooth-sil-bluez5=r12
[WRR-781] [Connectivity LGSI] Connectivity components
          cflags security errors fix

Cherry-picked-from-commit: 6624f670fda4cf7f5ec4f5895698b18d0cb03afb
Cherry-picked-from-branch: