webos: webos-image=r5 (use UNPACKDIR)
:Release Notes:
see:
https://lists.openembedded.org/g/openembedded-architecture/message/2007

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/850849

Exception: FileNotFoundError: [Errno 2] No such file or directory: 'webos-image/1.0/smack_labels_default'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-22934] CCC: webos-image=r5 (use UNPACKDIR)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead

Cherry-picked-from-commit: a24f8de613c33b95ef7571f6327d6210e932056c
Cherry-picked-from-branch: