webos: polkit=webos2
:Release Notes:
Fix polkit's PACKAGECONFIG introduced in WRQ-26952.

:Detailed Notes:
polkit=webos2
Makes sure to disable 'mozjs' when appending 'duktape' to PACKAGECONFIG.
They are mutually exclusive since 'duktape' PACKAGECONFIG was introduced
in langdale with:
https://git.openembedded.org/meta-openembedded/commit/?id=461ceffc48e28dc8f04b8a982b3a4a2db22b718b
and without this it fails to parse:

ERROR: meta-oe/recipes-extended/polkit/polkit_124.bb: polkit:
  PACKAGECONFIG[duktape] Conflict package config 'mozjs' set in
  PACKAGECONFIG.
ERROR: Parsing halted due to errors, see error messages above

:Testing Performed:
Only build tested.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-27223] CCC: polkit=webos2

Cherry-picked-from-commit: f97336c0d0326dc82622e99628c3b45278c72f72
Cherry-picked-from-branch: