webos-recipe-blacklist.inc: blacklist failing recipes caused by Qt upgrade
:Release Notes:
Blacklist recipes failing since the switch from meta-qt5 to meta-qt6.

:Detailed Notes:
Fixes:
ERROR: Nothing RPROVIDES 'qtopcua' (but /jenkins/home/workspace/jansa/webos-dashing-dunfell/meta-qt6/recipes-qt/packagegroups/packagegroup-qt6-addons.bb RDEPENDS on or otherwise requires it)
qtopcua was skipped: Recipe is blacklisted: requires widgets module enabled in qtbase, which was disabled in PLAT-18645 http://caprica.lgsvl.com:8080/Errors/Details/1509148
NOTE: Runtime target 'qtopcua' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtopcua']
NOTE: Runtime target 'packagegroup-qt6-addons' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-qt6-addons', 'qtopcua']
ERROR: Nothing RPROVIDES 'qtconnectivity-tools' (but /jenkins/home/workspace/jansa/webos-dashing-dunfell/meta-qt6/recipes-qt/packagegroups/packagegroup-qt6-addons.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'qtconnectivity-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtconnectivity-tools']
ERROR: Nothing RPROVIDES 'qtconnectivity' (but /jenkins/home/workspace/jansa/webos-dashing-dunfell/meta-qt6/recipes-qt/packagegroups/packagegroup-qt6-addons.bb RDEPENDS on or otherwise requires it)
qtconnectivity was skipped: Recipe is blacklisted: requires dbus module enabled in qtbase, which was disabled in PLAT-18268 ERROR: Feature 'bluez' was enabled, but the pre-condition 'libs.bluez && features.concurrent && features.dbus' failed. http://caprica.lgsvl.com:8080/Errors/Details/1509143
NOTE: Runtime target 'qtconnectivity' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtconnectivity']
ERROR: Nothing RPROVIDES 'qtmqtt' (but /jenkins/home/workspace/jansa/webos-dashing-dunfell/meta-qt6/recipes-qt/packagegroups/packagegroup-qt6-addons.bb RDEPENDS on or otherwise requires it)
qtmqtt was skipped: Recipe is blacklisted: requires widgets module enabled in qtbase, which was disabled in PLAT-18645 http://caprica.lgsvl.com:8080/Errors/Details/1509146
NOTE: Runtime target 'qtmqtt' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtmqtt']

And explicitly blacklists the failing recipes:
Summary: 4 tasks failed:
  /jenkins/home/workspace/jansa/webos-dashing-dunfell/meta-qt6/recipes-qt/qt6/qtdeviceutilities_git.bb:do_install
  /jenkins/home/workspace/jansa/webos-dashing-dunfell/meta-qt6/recipes-qt/qt6/qtcharts_git.bb:do_install
  /jenkins/home/workspace/jansa/webos-dashing-dunfell/meta-qt6/recipes-qt/qt6/qtdatavis3d_git.bb:do_install
  /jenkins/home/workspace/jansa/webos-dashing-dunfell/meta-qt6/recipes-qt/qt6/qtpositioning_git.bb:do_configure
Summary: There was 1 WARNING message shown.
Summary: There were 10 ERROR messages shown, returning a non-zero exit code.

:Testing Performed:
Only build tested.

:QA Notes:
N/A

:Issues Addressed:
[WRN-2515] CCC: Update meta-qt6 to v6.2.0-beta1

Change-Id: Ibefc0ae972c9506d8007690600c149ecbf409a31