org.ocf.webossample.ocserverbasicops=r1 (Fix missing return statement)
:Release Notes:
Add a return statement where missed.

:Detailed Notes:
Fixes:
http://caprica.lgsvl.com:8080/Errors/Details/1581276

resource/csdk/stack/samples/webos/secure/occlientbasicops/occlientbasicops.cpp:578:1: error: control reaches end of non-void function [-Werror=return-type]
resource/csdk/stack/samples/webos/secure/occlientbasicops/occlientbasicops.cpp:585:1: error: no return statement in function returning non-void [-Werror=return-type]
resource/csdk/stack/samples/webos/secure/ocserverbasicops/ocserverbasicops.cpp:591:1: error: no return statement in function returning non-void [-Werror=return-type]

:Testing Performed:
Build tested.

:QA Notes:

:Issues Addressed:
[PLAT-79213] Missing return statements from non-void functions
[PLAT-84440] CCC: Various build fixes

Change-Id: I5b1ee87f09e532cbe7a19391ca0c11ea325b641d