node-gyp-native=r1 (Fix build with python-3.11)
:Release Notes:
Remove usage of 'U' mode bit for opening files in python

The 'U' mode bit is removed in python 3.11. It has been
deprecated for a long time. The 'U' mode bit has no effect
so this change doesn't change any behavior.

See https://docs.python.org/3.11/whatsnew/3.11.html#changes-in-the-python-api

:Detailed Notes:
Fixes:
nodejs-module-webos-dynaload http://gecko.lge.com/Errors/Details/475741
nodejs-module-webos-sysbus http://gecko.lge.com/Errors/Details/475739
nodejs-module-webos-pmlog http://gecko.lge.com/Errors/Details/475742

gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@16.14.2 | linux | x64
gyp info find Python using Python version 3.11.0 found at "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/recipe-sysroot-native/usr/bin/python3-native/python3"
(node:137469) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/recipe-sysroot-native/usr/bin/python3-native/python3
gyp info spawn args [
gyp info spawn args   'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/recipe-sysroot-native/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/git/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/recipe-sysroot-native/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/node-v16.14.2/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/node-v16.14.2',
gyp info spawn args   '-Dnode_gyp_dir=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/recipe-sysroot-native/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/node-v16.14.2/$(Configuration)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/git',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/recipe-sysroot-native/usr/lib/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/recipe-sysroot-native/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/recipe-sysroot-native/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/recipe-sysroot-native/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/recipe-sysroot-native/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/recipe-sysroot-native/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/recipe-sysroot-native/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/recipe-sysroot-native/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/nodejs-module-webos-pmlog/3.0.1-7-r14/recipe-sysroot-native/usr/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 6.0.2-gentoo

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-4709] Create GPVB with Yocto 4.1 Langdale
[WRO-14425] CCC: Various build fixes

Change-Id: Iceb54344c1593afc3d32f5ab9b0e588665cff487