webos: webruntime=r78 (fix build with python-3.13)
:Release Notes:
On hosts with python-3.13 or with python-native upgraded to 3.13 in:
https://git.openembedded.org/openembedded-core/commit/?id=0b49c9aa31279ecda565cc66b63d1d61723b37b8

:Detailed Notes:
fixes:
http://gecko.lge.com:8000/Errors/Details/999925

BUILD_TARGETS are v8_snapshot_clang_x64/mksnapshot
Traceback (most recent call last):
  File "tmp/work/x86_64-linux/mksnapshot-cross-x86_64/108.0.5359.217-32/git/depot_tools/gn.py", line 17, in <module>
    import gclient_paths
  File "tmp/work/x86_64-linux/mksnapshot-cross-x86_64/108.0.5359.217-32/git/depot_tools/gclient_paths.py", line 13, in <module>
    import gclient_utils
  File "tmp/work/x86_64-linux/mksnapshot-cross-x86_64/108.0.5359.217-32/git/depot_tools/gclient_utils.py", line 19, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-8245] CCC: webruntime=r78 (fix build with python-3.13)
[WRR-7551] Apply backported patch to fix build with python-3.13
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Cherry-picked-from-commit: 1ff135eb07a656eedba7b2ae03aa37088a109d1c
Cherry-picked-from-branch: