webos_image.bbclass: use webos-qemux86-directdisk.wks WKS_FILE only for qemux86(-64)
:Release Notes:
Otherwise it is used also for raspberrypi and breaks the build.
meta-raspberrypi sets WKS_FILE in conf/machine/include/rpi-base.inc:
WKS_FILE ?= "sdimage-raspberrypi.wks"

:Detailed Notes:
Fixes:
NOTE: recipe webos-image-1.0-r5: task do_image_wic: Started
ERROR: webos-image-1.0-r5 do_image_wic: Execution of 'BUILD/work/raspberrypi4-webos-linux-gnueabi/webos-image/1.0-r5/temp/run.do_image_wic.16723'
failed with exit code 1:
INFO: Creating image(s)...

ERROR: Couldn't find correct bootimg_dir, exiting

WARNING: exit code 1 from a shell command.

ERROR: Logfile of failure stored in: BUILD/work/raspberrypi4-webos-linux-gnueabi/webos-image/1.0-r5/temp/log.do_image_wic.16723
NOTE: recipe webos-image-1.0-r5: task do_image_wic: Failed

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-109540] CCC: Various build fixes

Change-Id: I39bff467f8e6f85d33108f9e264399babe8e7fd3