lmsensors=webos2 scsirastools=webos2 (fix bash QA issue)
:Release Notes:

:Detailed Notes:
http://caprica.lgsvl.com:8080/Errors/Details/1587223
ERROR: QA Issue: scsirastools-raidmon rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]

http://caprica.lgsvl.com:8080/Errors/Details/1587217
ERROR: QA Issue: lmsensors-pwmconfig rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-84802] CCC: Fix missing runtime dependencies

Change-Id: I2f47a485aa4c04b24c12dc0bf0b511070f67f47a