rpi: gstreamer1.0-omx: update 0003-decrease-ranking-of-omxh264dec.patch to apply cleanly
:Release Notes:
Adjust after 0001-config-files-path.patch was dropped in meta-raspberrypi:
https://github.com/agherzan/meta-raspberrypi/commit/0a89fb8dac35d12fa94a6598e04847e06645fe76

:Detailed Notes:
Fixes:
ERROR: gstreamer1.0-omx-1.18.3-r0 do_patch: Fuzz detected:

Applying patch 0003-decrease-ranking-of-omxh264dec.patch
patching file config/rpi/gstomx.conf
Hunk #1 succeeded at 29 with fuzz 2.

The context lines in the patches can be updated with devtool:

    devtool modify gstreamer1.0-omx
    devtool finish --force-patch-refresh gstreamer1.0-omx <layer_path>

Don't forget to review changes done by devtool!

ERROR: gstreamer1.0-omx-1.18.3-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12997] CCC: Upgrade to Yocto 3.3 Hardknott
[PLAT-124341] Create GPVB with Yocto 3.3 Hardknott

Change-Id: Ie45d8fb00f6072e467b5ae0c258cee32640270df