webos: com.webos.service.camera=r16.* (fix unqualified-std-cast-call issue)
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1075914
camera-utils-clang/1.0.0-59/git/include/public/camera/hal/camera_hal_types.h:125:17: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-16196] CCC: Upgrade to Yocto 4.1 Langdale
[WRR-2120] Create GPVB with Yocto 5.1 Styhead

Cherry-picked-from-commit: 54c5a523dd0e434f1e00547e2dcbdca3eddecf57
Cherry-picked-from-branch: