docker-moby: remove seccomp from PACKAGECONFIG
:Release Notes:
We don't have seccomp in DISTRO_FEATURES

:Detailed Notes:
It got enabled by default in:
https://git.yoctoproject.org/meta-virtualization/commit/?id=3f45dc8e6944da89c3124871debec9ec5f443bd5

NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'libseccomp' (but /OE/lge/build/webos/mickledore/meta-virtualization/recipes-containers/docker/docker-moby_git.bb DEPENDS on or otherwise requires it)
libseccomp was skipped: missing required distro feature 'seccomp' (not in DISTRO_FEATURES)
NOTE: Runtime target 'docker-moby' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['docker-moby', 'libseccomp']
NOTE: Runtime target 'packagegroup-webos-extended' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-webos-extended', 'docker-moby', 'libseccomp']
NOTE: Runtime target 'webos-image-devel' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-devel', 'packagegroup-webos-extended', 'docker-moby', 'libseccomp']
ERROR: Nothing RPROVIDES 'docker-moby-cli' (but /OE/lge/build/webos/mickledore/meta-virtualization/recipes-containers/docker/docker-moby_git.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'docker-moby-cli'
NOTE: Runtime target 'docker-moby-cli' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['docker-moby-cli']
ERROR: Nothing RPROVIDES 'docker-moby-dev' (but /OE/lge/build/webos/mickledore/meta-virtualization/recipes-containers/docker/docker-moby_git.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'docker-moby-dev'
NOTE: Runtime target 'docker-moby-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['docker-moby-dev']

backported to kirkstone as well in:
https://git.yoctoproject.org/meta-virtualization/commit/?h=kirkstone&id=51833d0e131155aeae563c08b892854265bd9a10

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-14883] Create GPVB with Yocto 4.2 Mickedore
[WRP-5625] CCC: Various build fixes

Change-Id: Ic70eadd924c4e62337732f78ea71f9c3b75250b4