webos: webos-connman-adapter=r15 (ignore incompatible-pointer-types, int-conversion, implicit-function-declaration issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/821711
webos-connman-adapter/1.1.0-43/git/src/lunaservice_utils.c:244:59: error: passing argument 2 of 'json_convert_to_native_valist' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wan_service.c:587:14: error: implicit declaration of function 'cellular_technology_status_check_with_subscription'; did you mean 'p2p_technology_status_check_with_subscription'? [-Wimplicit-function-declaration]
webos-connman-adapter/1.1.0-43/git/src/connman_service.c:2021:49: error: passing argument 1 of 'g_dbus_proxy_set_default_timeout' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wifi_p2p_service.c:839:43: error: initialization of 'gboolean' {aka 'int'} from 'gpointer' {aka 'void *'} makes integer from pointer without a cast [-Wint-conversion]
webos-connman-adapter/1.1.0-43/git/src/wifi_p2p_service.c:994:73: error: passing argument 3 of 'g_timeout_add' makes pointer from integer without a cast [-Wint-conversion]
webos-connman-adapter/1.1.0-43/git/src/wifi_p2p_service.c:3313:70: error: passing argument 3 of 'jobject_get_exists' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wifi_p2p_service.c:3315:54: error: passing argument 1 of 'jstring_get' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wifi_p2p_service.c:4034:13: error: implicit declaration of function 'connman_technology_set_go_intent'; did you mean 'connman_technology_set_powered'? [-Wimplicit-function-declaration]
webos-connman-adapter/1.1.0-43/git/src/wifi_setting.c:892:44: error: passing argument 1 of 'g_strv_length' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wifi_setting.c:897:60: error: passing argument 1 of 'strlen' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wifi_setting.c:897:45: error: passing argument 2 of 'strncat' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/connman_manager.c:1769:33: error: assignment to 'gboolean *' {aka 'int *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
webos-connman-adapter/1.1.0-43/git/src/connman_manager.c:2031:76: error: passing argument 2 of 'connman_update_callbacks->services_changed' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/connman_manager.c:2063:25: error: passing argument 2 of 'connman_update_callbacks->saved_services_changed' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/connectionmanager_service.c:284:25: error: implicit declaration of function 'send_peer_information_to_subscribers'; did you mean 'send_tethering_state_to_subscribers'? [-Wimplicit-function-declaration]
webos-connman-adapter/1.1.0-43/git/src/connectionmanager_service.c:1410:74: error: passing argument 4 of 'change_network_ipv6' makes pointer from integer without a cast [-Wint-conversion]
webos-connman-adapter/1.1.0-43/git/src/connectionmanager_service.c:1563:93: error: passing argument 3 of 'change_network_dns' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/connectionmanager_service.c:2469:47: error: passing argument 1 of 'connman_counter_new' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wifi_scan.c:113:44: error: implicit declaration of function 'is_connected_peer' [-Wimplicit-function-declaration]
webos-connman-adapter/1.1.0-43/git/src/wifi_scan.c:160:18: error: implicit declaration of function 'is_wifi_tethering' [-Wimplicit-function-declaration]
webos-connman-adapter/1.1.0-43/git/src/wifi_scan.c:434:40: error: passing argument 1 of 'g_strv_length' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wifi_scan.c:444:64: error: passing argument 1 of 'strlen' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wifi_scan.c:444:48: error: passing argument 2 of 'strncat' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wifi_service.c:1841:33: error: implicit declaration of function 'setPropertyUpdateCallback' [-Wimplicit-function-declaration]
webos-connman-adapter/1.1.0-43/git/src/wifi_service.c:2723:48: error: passing argument 1 of 'wifi_scan_now_with_option' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wifi_service.c:2723:54: error: passing argument 2 of 'wifi_scan_now_with_option' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wifi_service.c:2896:72: error: passing argument 2 of 'check_service_security' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wifi_service.c:4153:56: error: passing argument 2 of 'LSSubscriptionSetCancelFunction' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wifi_service.c:4162:82: error: passing argument 5 of 'g_bus_watch_name' from incompatible pointer type [-Wincompatible-pointer-types]
webos-connman-adapter/1.1.0-43/git/src/wifi_tethering_service.c:752:42: error: passing argument 2 of 'jboolean_get' from incompatible pointer type [-Wincompatible-pointer-types]
CFLAGS += "-Wno-error=incompatible-pointer-types -Wno-error=int-conversion -Wno-error=implicit-function-declaration"

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19569] CCC: webos-connman-adapter=r15 (ignore incompatible-pointer-types, int-conversion, implicit-function-declaration issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: 39e3efd6cd5f02b9bf2e0e6e6608451532e27e78
Cherry-picked-from-branch: