bluez5 (refresh patches to apply on 5.59 version)
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: bluez5-5.59-r0 do_patch: Command Error: 'quilt --quiltrc /jenkins/mjansa/build/ros/webos-noetic-honister/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/bluez5/5.59-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
stdout: Applying patch 0012-Support-enabling-avdtp-delayReport.patch
patching file profiles/audio/a2dp.c
Hunk #1 succeeded at 2195 (offset 1 line).
patching file profiles/audio/a2dp.h
patching file profiles/audio/avdtp.c
Hunk #1 succeeded at 470 (offset 1 line).
patching file profiles/audio/avdtp.h
patching file profiles/audio/media.c
patching file profiles/audio/media.h
patching file src/adapter.c
Hunk #1 succeeded at 68 (offset 1 line).
Hunk #2 succeeded at 226 (offset 1 line).
Hunk #3 succeeded at 295 (offset 3 lines).
Hunk #4 succeeded at 501 (offset 3 lines).
Hunk #5 succeeded at 3254 (offset 11 lines).
Hunk #6 succeeded at 3551 (offset 11 lines).
Hunk #7 succeeded at 4880 (offset 12 lines).
Hunk #8 succeeded at 6332 (offset 12 lines).
Hunk #9 succeeded at 6373 (offset 12 lines).
Hunk #10 succeeded at 6381 (offset 12 lines).
patching file src/adapter.h
patching file src/btd.h
Hunk #1 FAILED at 105.
1 out of 1 hunk FAILED -- rejects in file src/btd.h
patching file src/main.c
Hunk #1 succeeded at 77 (offset 1 line).
Hunk #2 succeeded at 729 with fuzz 2 (offset 20 lines).
patching file src/main.conf
Patch 0012-Support-enabling-avdtp-delayReport.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12998] CCC: Upgrade to Yocto 3.4 Honister
[PLAT-141293] Create GPVB with Yocto 3.4 Honister

Change-Id: I92051ac5eb84b9c0e203f3446db5cc9ac8ed21b3