connman: update patches to apply on 1.41 version
:Release Notes:
WIP: drop failing patches, needs a bit more work to rebase properly for new version

:Detailed Notes:
Fixes:
ERROR: connman-1.41-r0 do_patch: Applying patch '0005-Support-additional-feature-for-tethering.patch' on target directory '/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/connman/1.41-r0/connman-1.41'
CmdError('quilt --quiltrc /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/connman/1.41-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0005-Support-additional-feature-for-tethering.patch
patching file gdhcp/server.c
patching file include/technology.h
Hunk #1 FAILED at 46.
1 out of 1 hunk FAILED -- rejects in file include/technology.h
patching file plugins/wifi.c
Hunk #1 FAILED at 3669.
1 out of 1 hunk FAILED -- rejects in file plugins/wifi.c
patching file src/connman.h
patching file src/technology.c
Hunk #1 FAILED at 66.
Hunk #2 succeeded at 200 with fuzz 2 (offset 8 lines).
Hunk #3 succeeded at 233 (offset 8 lines).
Hunk #4 succeeded at 278 (offset 8 lines).
Hunk #5 succeeded at 409 (offset 14 lines).
Hunk #6 FAILED at 470.
Hunk #7 succeeded at 603 with fuzz 2 (offset 22 lines).
Hunk #8 succeeded at 1011 (offset 22 lines).
Hunk #9 succeeded at 1057 with fuzz 2 (offset 43 lines).
Hunk #10 succeeded at 1375 (offset 43 lines).
2 out of 10 hunks FAILED -- rejects in file src/technology.c
patching file src/tethering.c
Patch 0005-Support-additional-feature-for-tethering.patch does not apply (enforce with -f)

stderr: ')
ERROR: Logfile of failure stored in: /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/connman/1.41-r0/temp/log.do_patch.2536046

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12999] CCC: Upgrade to Yocto 4.0 Kirkstone
[WRN-9820] Create GPVB with Yocto 4.0 Kirkstone

Change-Id: I4cee71733583aee3d4acb4ca968f2ea079fe87e4