openh264=webos1 (fix installed-vs-shared QA issue with multilib)
:Release Notes:
Now with commercial_openh264 in LICENSE_FLAGS_ACCEPTED for some our builds
this issue show up in world builds.

:Detailed Notes:
In some cases libdir is /usr/lib64 and then libraries installed in /usr/lib aren't packaged:

ERROR: QA Issue: openh264: Files/directories were installed but not shipped in any package:
  /usr/lib/libopenh264.a
  /usr/lib/libopenh264.so.2.1.1
  /usr/lib/libopenh264.so
  /usr/lib/libopenh264.so.6
  /usr/lib/pkgconfig
  /usr/lib/pkgconfig/openh264.pc
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
openh264: 6 installed and not shipped files. [installed-vs-shipped]

Backport:
https://git.openembedded.org/meta-openembedded/commit/?id=e89194c3aac90790544128c2ac428c73cbe5c8b5

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-24156] CCC: Various build fixes

Cherry-picked-from-commit: b8d9c44541603b8eefcee7abab329ec3b036739c
Cherry-picked-from-branch: