webos_cmake.bbclass: fix default WEBOS_TARGET_DISTRO_VARIANT value
:Release Notes:
Unfortunately having ' in the default value causes syntax issue when
parsing the layer with different order of layers in BBLAYERS.

:Detailed Notes:
As shown in:
https://layers.openembedded.org/layerindex/branch/master/layer/meta-webosose/
parsing still fails with:
bb.data_smart.ExpansionError: Failure expanding variable
  EXTRA_OECMAKE_DISTRO_VARIANT, expression was
  ${@ '-DWEBOS_TARGET_DISTRO_VARIANT:STRING=bitbake-conf-in-meta-webos-wasn't-parsed'
  if bb.data.inherits_class('webos_distro_variant_dep', d) and not
  bb.data.inherits_class('native', d) else     '' } which triggered
  exception SyntaxError: invalid syntax
  (Var <EXTRA_OECMAKE_DISTRO_VARIANT>, line 1)

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-79498] [OSE] CCC: Fix metadata parsing without webos as a DISTRO
[PLAT-80706] [OSE] CCC: Various build fixes 2019-06-20

Change-Id: Ibdc4abb91fd1f0bfbd8648f916f3cbe51923b546
Reviewed-on: http://gpro.lge.com/245411
Reviewed-by: Martin Jansa <martin.jansa@lge.com>
Tested-by: Martin Jansa <martin.jansa@lge.com>