webos: luna-prefs=r17 (ignore incompatible-pointer-types issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/821703
luna-prefs/3.0.0-17/git/luna-prefs-service/accesschecker.c:39:39: error: initialization of 'LSMessage *' from incompatible pointer type 'LSMessage **' [-Wincompatible-pointer-types]
luna-prefs/3.0.0-17/git/luna-prefs-service/accesschecker.c:85:24: error: assignment to 'LSMessage **' from incompatible pointer type 'LSMessage *' [-Wincompatible-pointer-types]
luna-prefs/3.0.0-17/git/luna-prefs-service/main.c:487:48: error: passing argument 4 of 'checkAccess' from incompatible pointer type [-Wincompatible-pointer-types]
luna-prefs/3.0.0-17/git/luna-prefs-service/main.c:766:48: error: passing argument 4 of 'checkAccess' from incompatible pointer type [-Wincompatible-pointer-types]
luna-prefs/3.0.0-17/git/luna-prefs-service/main.c:959:48: error: passing argument 4 of 'checkAccess' from incompatible pointer type [-Wincompatible-pointer-types]
luna-prefs/3.0.0-17/git/luna-prefs-service/main.c:1072:49: error: passing argument 4 of 'checkAccess' from incompatible pointer type [-Wincompatible-pointer-types]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19569] CCC: luna-prefs=r17 (ignore incompatible-pointer-types issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: 28bd8a9aa9c3ce67c1321ce1612dfcdfbf50cc1c
Cherry-picked-from-branch: