arm-compute-library=r3 (package examples and tests in separate package)
:Release Notes:
There is a PACKAGECONFIG for tests and examples, but all are then
packaged inside ${PN}-dev introduce ${PN}-tests and ${PN}-examples.

:Detailed Notes:
Fixes:
ERROR: arm-compute-library-21.11-r1 do_package_qa: QA Issue: /usr/bin/arm-compute-library-21.11/tests/arm_compute_validation contained in package arm-compute-library-dev requires libarm_compute.so()(64bit), but no providers found in RDEPENDS:arm-compute-library-dev? [file-rdeps]
ERROR: arm-compute-library-21.11-r1 do_package_qa: QA Issue: /usr/bin/arm-compute-library-21.11/tests/arm_compute_validation contained in package arm-compute-library-dev requires libarm_compute_graph.so()(64bit), but no providers found in RDEPENDS:arm-compute-library-dev? [file-rdeps]
ERROR: arm-compute-library-21.11-r1 do_package_qa: Fatal QA errors were found, failing task.

For latest oe-core which changed default RDEPENDS:${PN}-dev = ${PN} to
be just RRECOMMENDS:${PN}-dev in:
https://git.openembedded.org/openembedded-core/commit/?id=a5b381c0f45c590a762647a9956a8f41e2e2315e
https://git.openembedded.org/openembedded-core/commit/?id=6f28420ab0e8f2ab5eb06326024777a40aded0a6

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-4709] Create GPVB with Yocto 4.1 Langdale
[WRO-8076] CCC: Various build fixes

Change-Id: Iac6d2aef83f59467e60fbc49976030fd0b4650ed