webos: telegraf=r6 node-red=r4 (temporary skip textrel QA check)
:Release Notes:
fails only with 32bit MACHINEs it seems

:Detailed Notes:
http://gecko.lge.com:8000/Errors/Details/910073
ERROR: QA Issue: telegraf: ELF binary /usr/bin/telegraf has relocations
in .text [textrel]

http://gecko.lge.com:8000/Errors/Details/911532
ERROR: QA Issue: node-red: ELF binary /usr/lib/node_modules/node-
red/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node has
relocations in .text [textrel]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-33135] CCC: telegraf=r6 node-red=r4 (temporary skip textrel QA
            check)

Cherry-picked-from-commit: 696814b57c6c41855dfe35cc3d82f33ae9913f35
Cherry-picked-from-branch: