linux-raspberrypi=webosrpi34: update seed-voicecard for 6.1 kernel
:Release Notes:
The patch unfortunately isn't using #ifdefs to be backwards compatible with
older kernels, but we can easily use minver here to apply it only for
newer kernel as 6.1.20 from:
https://github.com/agherzan/meta-raspberrypi/commit/b5753bd2ac1289395064346ecbe4a895ecd7fc4f
https://github.com/agherzan/meta-raspberrypi/commit/12a1187b01644cb444106f7c8f498fbf519be276

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/560830

sound/soc/codecs/ac108.c:1332:10: error: 'struct snd_soc_component_driver' has no member named 'non_legacy_dai_naming'; did you mean 'legacy_dai_naming'?
 1332 |         .non_legacy_dai_naming  = 1,
      |          ^~~~~~~~~~~~~~~~~~~~~
      |          legacy_dai_naming

sound/soc/codecs/ac108.c:1551:21: error: initialization of 'void (*)(struct i2c_client *)' from incompatible pointer type 'int (*)(struct i2c_client *)' [-Werror=incompatible-pointer-types]
 1551 |         .remove =   ac108_i2c_remove,
      |                     ^~~~~~~~~~~~~~~~

I've reported it in:
https://github.com/respeaker/seeed-voicecard/pull/323#issuecomment-1483804868
and in reply I've learned bout HinTak's fork, please donate to him.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-11630] Add Upstream-Status to existing .patch files in meta-lg-webos
[WRP-11864] CCC: Various build fixes and .patch files cleanup

Cherry-picked-from-commit: 81d441818dd7b0625d369b60028f5296707d986a
Cherry-picked-from-branch: