PNBLACKLIST: blacklist ROS1 wxwidgets wxpython freeglut sound-play ...
:Release Notes:
Add few more meta-ros recipes which aren't compatible with webOS.

:Detailed Notes:
ERROR: Nothing PROVIDES 'libxi' (but <meta-ros/recipes-extended/libfreenect/libfreenect_0.5.2.bb,> <meta-ros/recipes-extended/freeglut/freeglut_2.8.1.bb> DEPENDS on or otherwise requires it)
ERROR: libxi was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'libfreenect', 'libxi']

Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
NOTE: Started PRServer with DBfile: <cache/prserv.sqlite3,> IP: 127.0.0.1, PORT: 57540, PID: 29678
Parsing recipes...done.
Parsing of 2664 .bb files complete (0 cached, 2664 parsed). 3477 targets, 524 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'libxinerama' (but <meta-ros/recipes-extended/wxwidgets/wxwidgets_2.9.5.bb> DEPENDS on or otherwise requires it)
ERROR: libxinerama was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'wxpython', 'wxwidgets', 'libxinerama']

Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
NOTE: Started PRServer with DBfile: <cache/prserv.sqlite3,> IP: 127.0.0.1, PORT: 43908, PID: 7933
Loading cache...done.
Loaded 3474 entries from dependency cache.
Parsing recipes...done.
Parsing of 2664 .bb files complete (2661 cached, 3 parsed). 3477 targets, 554 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'libglu' (but <meta-ros/recipes-extended/wxwidgets/wxwidgets_2.9.5.bb,> <meta-ros/recipes-extended/freeglut/freeglut_2.8.1.bb> DEPENDS on or otherwise requires it)
ERROR: libglu was skipped: Recipe is blacklisted: broken: we don't build libGL with mesa: cannot find -lGL
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'wxpython', 'wxwidgets', 'libglu']

ERROR: Nothing PROVIDES 'librealsense' (but <meta-ros/recipes-extended/realsense-camera/realsense-camera_1.8.0.bb> DEPENDS on or otherwise requires it)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'realsense-camera', 'librealsense']

ERROR: Nothing PROVIDES 'libxi' (but <meta-ros/recipes-extended/freeglut/freeglut_2.8.1.bb> DEPENDS on or otherwise requires it)
libxi was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'freeglut', 'libxi']

ERROR: Nothing PROVIDES 'libsdl-image' (but <meta-ros/recipes-ros/navigation/map-server_1.12.16.bb> DEPENDS on or otherwise requires it)
libsdl-image was skipped: Recipe is blacklisted: depends on broken libsdl
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'map-server', 'libsdl-image']

ERROR: Nothing PROVIDES 'libglu' (but <meta-ros/recipes-extended/freeglut/freeglut_2.8.1.bb> DEPENDS on or otherwise requires it)
ERROR: libglu was skipped: Recipe is blacklisted: broken: we don't build libGL with mesa: cannot find -lGL
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'freeglut', 'libglu']

...

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-64986] [OSE] CCC: Various build issues

Change-Id: I3b90987f1c4c38f8964f4ec68f0b418cbe005b56
Reviewed-on: http://gpro.lgsvl.com/213898
Reviewed-by: Martin Jansa <martin.jansa@lge.com>
Tested-by: Martin Jansa <martin.jansa@lge.com>
Reviewed-by: Minjae Kim <nate.kim@lge.com>