sp-memusage: Fix hardcoded 'lib' installation path
:Release Notes:
With multilib enabled the libdir is usr/lib64 instead of usr/lib.
Add PV as it's 4 commits after 1.0 tag.

:Detailed Notes:
Respect ${libdir} to fix:
http://gecko.lge.com:8000/Errors/Details/574302

ERROR: QA Issue: sp-memusage: Files/directories were installed but not shipped in any package:
  /usr/lib/libmallinfo.so
  /usr/lib/libmallinfo.so.0
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
sp-memusage: 2 installed and not shipped files. [installed-vs-shipped]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-12446] CCC: Various build fixes
[WRP-12469] Bitbake world issues 2023-04-01

Cherry-picked-from-commit: 420a784a40d387a9476ad11608516662e98b3ad4
Cherry-picked-from-branch: