webos: xnnpack=r3 (ignore incompatible-pointer-types issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

many cases of:
git/src/f16-dwconv2d-chw/gen/5x5s2p2-minmax-neonfp16arith-3x4.c:37:41: error: passing argument 1 of 'vld1_dup_f16' from incompatible pointer type [-Wincompatible-pointer-types]
http://gecko.lge.com:8000/Errors/Details/821678

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19569] CCC: xnnpack=r3 (ignore incompatible-pointer-types issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: 9ab84d3b94495014cbd482e0f3017099e5aa1329
Cherry-picked-from-branch: