image_types_wic.bbclass: import from oe-core with a fix for multilib
:Release Notes:
Backport a fix:
https://git.openembedded.org/openembedded-core/commit/meta/classes/image_types_wic.bbclass?id=958ee0eede859bdba659e3343856b1c226207854
backport request sent:
https://lists.openembedded.org/g/openembedded-core/message/171505

:Detailed Notes:
Fixes:
ERROR: Nothing PROVIDES 'virtual/i686-distromllib32-linux-binutils' (but virtual:multilib:lib32:/OE/lge/build/distro/kirkstone/meta-lg-webos/meta-distro/recipes-core/images/distro-atsc-devel.bb DEPENDS on or otherwise requires it). Close matches:
  virtual/lib32-i686-distromllib32-linux-binutils
  virtual/lib32-i686-distromllib32-linux-rust
  virtual/x86_64-distro-linux-binutils

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12690] Remove unused metadata
[WRO-13280] CCC: Various build fixes

Change-Id: I608763e8b47aa9fb88c89536074c8a5dc7d54f6a