cpushareholder-stub=r3 (inherit webos_arch_indep before webos_cmake)
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: cpushareholder-stub different signature for task do_package_write_ipk.sigdata between qemux86 and qemuarm
Hash for dependent task cpushareholder-stub/cpushareholder-stub.bb.do_package changed from ccae0b4bb7a1ac4e3ccd5fa6a9e64ea96ca1f5a9d5f6b9263becea602e2034a8 to f5271f0ce62b258c52a653095016423c96e37f94b2510b5abb9145e12568549e

bitbake-diffsigs BUILD/sstate-diff/1557599893/qemu???/*/cpushareholder-stub/*do_generate_toolchain_file.sigdata*
NOTE: Starting bitbake server...
basehash changed from d1ce51d389efd0c701560ec2c3385f1f7a0053aeae1bdf96e1ee4db9f5329a3d to 72746fc03534f07a47263deda117c9e8173210e1f88359867e96b116aff5fd26
Variable OECMAKE_CXX_COMPILER value changed from 'arm-webos-linux-gnueabi-g++' to 'i586-webos-linux-g++'
Variable OECMAKE_C_COMPILER value changed from 'arm-webos-linux-gnueabi-gcc' to 'i586-webos-linux-gcc'

:Testing Performed:
oe-core/scripts/sstate-diff-machines.sh --tmpdir=BUILD --machines="qemux86 qemux86copy qemuarm" --targets="cpushareholder-stub" --analyze

:QA Notes:

:Issues Addressed:
[PLAT-78082] Upgrade to Yocto 2.6 Thud
[PLAT-78507] [OSE] CCC: Upgrade to Yocto 2.6 Thud

Change-Id: I8aafd7c4d5708edb2b6aef7141635f5f21281cf6