openssl=webos22 (fix QA issue bash and cleanup the recipe)
:Release Notes:
Update the u-a configuration, remove outdated comments and fix QA issue.

:Detailed Notes:
Fixes:
ERROR: QA Issue: /usr/lib/openssl/ptest/test/certs/mkcert.sh contained
in package openssl-ptest requires /bin/bash, but no providers found in
RDEPENDS_openssl-ptest? [file-rdeps]

http://caprica.lgsvl.com:8080/Errors/Details/1116426

:Testing Performed:
See CCC.

:QA Notes:

:Issues Addressed:
[PLAT-66331] openssl=v1.1.1
[PLAT-80700] CCC: openssl=v1.1.1b

Change-Id: I19908ba6e8d2e6de616433cf91aa798be0f19e11