webos: refresh patches to apply cleanly on bluez5 version 5.54
:Release Notes:

:Detailed Notes:
Fix following error occured that when appling patch files to bluez5 version 5.54.

ERROR: bluez5-5.54-r0 do_patch: Fuzz detected:
Applying patch 0016-Support-enabling-avdtp-delayReport.patch
patching file profiles/audio/a2dp.c
Hunk #1 succeeded at 2127 (offset 689 lines).
patching file profiles/audio/a2dp.h
Hunk #1 succeeded at 93 with fuzz 2 (offset 2 lines).
patching file profiles/audio/avdtp.c
Hunk #1 succeeded at 477 (offset 2 lines).
patching file profiles/audio/avdtp.h
Hunk #1 succeeded at 310 (offset 10 lines).
patching file profiles/audio/media.c
Hunk #1 succeeded at 132 (offset 15 lines).
Hunk #2 succeeded at 445 (offset 16 lines).
Hunk #3 succeeded at 766 (offset 25 lines).
Hunk #4 succeeded at 784 (offset 25 lines).
Hunk #5 succeeded at 2416 (offset 489 lines).
patching file profiles/audio/media.h
patching file src/adapter.c
Hunk #1 succeeded at 78 (offset 1 line).
patching file src/adapter.h
patching file src/hcid.h
Hunk #1 succeeded at 53 (offset 7 lines).
patching file src/main.c
Hunk #1 succeeded at 92 with fuzz 2 (offset 3 lines).
Hunk #2 succeeded at 442 with fuzz 1 (offset 42 lines).
patching file src/main.conf

ERROR: bluez5-5.54-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:
Only build tested.

:QA Notes:
None.

:Issues Addressed:
[PLAT-111903] Create GPVB with Yocto 3.1 dunfell
[PLAT-115145] CCC: Upgrade to Yocto 3.1 Dunfell

Change-Id: I07e862b3c8ff131eab0e7eb0dfe46790e1d680b9