webos: g-camera-pipeline=r19 (ignore incompatible-pointer-types and implicit-function-declaration issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

g-camera-pipeline/1.0.0-gav.44/git/camsrc/gstcamsrc.c:168:36: error: assignment to 'GstStateChangeReturn (*)(GstElement *, GstStateChange)' {aka 'GstStateChangeReturn (*)(struct _GstElement *, GstStateChange)'} from incompatible pointer type 'GstStateChangeReturn (*)(GstPushSrc *, GstStateChange)' {aka 'GstStateChangeReturn (*)(struct _GstPushSrc *, GstStateChange)'} [-Wincompatible-pointer-types]
g-camera-pipeline/1.0.0-gav.44/git/camsrc/gstcamsrc.c:389:73: error: passing argument 2 of 'camera_hal_if_get_buffer_fd' from incompatible pointer type [-Wincompatible-pointer-types]
g-camera-pipeline/1.0.0-gav.44/git/camsrc/gstcamsrc.c:515:30: error: implicit declaration of function 'camera_hal_if_destroy_dmafd'; did you mean 'camera_hal_if_destroy_buffer'? [-Wimplicit-function-declaration]
g-camera-pipeline/1.0.0-gav.44/git/camsrc/gstcamsrc.c:523:59: error: passing argument 1 of '((GstElementClass *)parent_class)->change_state' from incompatible pointer type [-Wincompatible-pointer-types]

http://gecko.lge.com:8000/Errors/Details/821695

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19569] CCC: g-camera-pipeline=r19 (ignore incompatible-pointer-types and implicit-function-declaration issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: 329229bb14a26cd1f638c3c6dd3c29dac08c7476
Cherry-picked-from-branch: