webos.inc: Update CONNECTIVITY_CHECK_URIS
:Release Notes:
Fix check for yoctoproject URL and add 2 URLs for our own sites so that
we don't generate so much traffic on upstream sites and also to catch
connectivity issues to our own sources earlier in the build.

:Detailed Notes:
rev=HEAD doesn't work for very long time, but nobody noticed, because
this whole test wasn't properly executed, now it fails with:

ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    Fetcher failure: Unable to resolve 'HEAD' in upstream git repository in git ls-remote output for git.yoctoproject.org/yocto-firewall-test.
    Please ensure your host's network is configured correctly,
    or set BB_NO_NETWORK = "1" to disable network access if
    all required sources are on local disk.

The example was fixed in meta-poky long time ago with:
  commit fab7da4f8030a4067db0522f77eaa6d3b501c68f
  Author: Mariano Lopez <mariano.lopez@linux.intel.com>
  Date:   Wed May 13 12:05:24 2015 +0000

    poky.conf: Fix git URL example

    The git URL example fails because bitbake fetch checks references (refs/heads, refs/tags).
    It is not able to search for HEAD alone.

    This search mode was implemented on 2014-01-21

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-41150] Upgrade to Yocto 2.3 Pyro
[PLAT-78505] [OSE] CCC: Upgrade to Yocto 2.3 Pyro

Change-Id: Ie7cae51abe6925c911a6cc68c1f24d41707d219d