loc-utils: CMakeLists.txt: Fix hardcoded 'lib' installation path
:Release Notes:
With multilib enabled the libdir is usr/lib64 instead of usr/lib.

:Detailed Notes:
Respect WEBOS_INSTALL_LIBDIR to fix:
http://gecko.lge.com:8000/Errors/Details/574288

ERROR: QA Issue: loc-utils: Files/directories were installed but not shipped in any package:
  /usr/lib/libloc_utils.so.1
  /usr/lib/libloc_utils.so.1.0.0
  /usr/lib/libloc_utils.so
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
loc-utils: 3 installed and not shipped files. [installed-vs-shipped]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-12446] CCC: Various build fixes
[WRP-12469] Bitbake world issues 2023-04-01

Cherry-picked-from-commit: cde0f141eb72f459f8676a2a1f79e687b3073c7e
Cherry-picked-from-branch: