perf: fix build-deps QA issue with bash
:Release Notes:

:Detailed Notes:
bash added to another perf package for v5.12-rc5+ kernels:
https://git.openembedded.org/openembedded-core/commit/?h=hardknott&id=159cdb159ad0e9d3ed73cfc07f9acd5c0b608e7b
ERROR: QA Issue: perf-tests rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]

now backported to dunfell as well in:
https://git.openembedded.org/openembedded-core/commit/?h=dunfell&id=0cfc604b48155ed4129bcc056610f32caf1a93b4

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-124341] Create GPVB with Yocto 3.3 Hardknott
[WRN-16369] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: Ic7e7b7af5edb622331854a122fe25d13c48aea99