webos: opkg=webos12 (update 0008-Allow-multiple-f-flags.patch to apply on v0.6.1)
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: opkg-1_0.6.1-r0 do_patch: Fuzz detected:

Applying patch 0008-Allow-multiple-f-flags.patch
patching file libopkg/opkg_conf.c
Hunk #1 succeeded at 593 (offset 1 line).
Hunk #2 succeeded at 685 (offset 1 line).
Hunk #3 succeeded at 722 (offset 1 line).
Hunk #4 succeeded at 906 (offset 4 lines).
Hunk #5 succeeded at 929 (offset 4 lines).
patching file libopkg/opkg_conf.h
Hunk #1 succeeded at 70 (offset 1 line).
patching file src/opkg.c
Hunk #1 succeeded at 152 (offset 2 lines).
Hunk #2 succeeded at 343 (offset 5 lines).
patching file tests/Makefile
Hunk #1 succeeded at 101 with fuzz 1 (offset 5 lines).
patching file tests/misc/print_architecture.py

The context lines in the patches can be updated with devtool:

    devtool modify opkg
    devtool finish --force-patch-refresh opkg <layer_path>

Don't forget to review changes done by devtool!

ERROR: opkg-1_0.6.1-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-16196] CCC: Upgrade to Yocto 4.1 Langdale
[WRR-2115] Create GPVB with Yocto 4.1 Langdale

Cherry-picked-from-commit: e12b2eecd609729f2157440fa9f494ff6d444f22
Cherry-picked-from-branch: