webos: python3-pyyaml-include=webos1 (temporarily remove the runtime ptest dependency)
:Release Notes:
On python3-unittest-automake-output as reported in:
https://lists.openembedded.org/g/openembedded-devel/message/110191
This was now merged to meta-oe kirkstone, but the
python3-unittest-automake-output isn't available in oe-core kirkstone,
causing:
ERROR: Nothing RPROVIDES 'python3-unittest-automake-output' (but
meta-oe/meta-python/recipes-devtools/python/python3-pyyaml-include_1.4.1.bb
RDEPENDS on or otherwise requires it)

:Detailed Notes:
python3-unittest-automake-output was added to oe-core in mickledore:

openembedded-core $ git log --oneline -- ./meta/recipes-devtools/python/python3-unittest-automake-output_0.1.bb
db0e82135c python3-unittest-automake-output: upgrade to 0.2
961e4f3fc7 python3-unittest-automake-output: add new recipe for ptest integration

python3-unittest-automake-output addition to oe-core/kirkstone was rejected in:
https://lore.kernel.org/all/20240327072236.2221619-1-mingli.yu@windriver.com/T/#mda91919809cf156aba24f099bef65142067cd318

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-18930] CCC: Various build fixes

Cherry-picked-from-commit: d2696a0511b6a7af741439f47104587f0b767148
Cherry-picked-from-branch: