webos-recipe-blacklist.inc: unblacklist many recipes from meta-oe
:Release Notes:
mongodb, xfsdump, xfsprogs, glmark2, hplip, poppler, cups-filters, wireshark, yad, xmlsec1, dlt-daemon, netplan, mosquitto, dvb-apps, tvheadend
gst-plugins-gl, netkit-rusers, android-tools, paho-mqtt-c, packagegroup-meta-oe, x264, mpeg2dec, usb-modeswitch, systemd-bootchart, usb-modeswitch-data
were already fixed in meta-openembedded dunfell.

:Detailed Notes:
Add a bbappend to fix:
ERROR: cups-filters-1.27.2-r0 do_package_qa: QA Issue: cups-filters rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]

Update comments with links to fixes I've sent upstream.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-139325] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: I5e9fa2f7912f10977bea45a7e820d325b9144adc