wayland: refresh patches to apply on 1.17.0 version
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: wayland-1.17.0-r0 do_patch: Command Error: 'quilt --quiltrc raspberrypi4-webos-linux-gnueabi/wayland/1.17.0-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0003-Enhance-Wayland-debug-print.patch
patching file Makefile.am
patching file configure.ac
patching file src/connection.c
Hunk #2 succeeded at 1295 (offset 8 lines).
Hunk #3 FAILED at 1330.
1 out of 3 hunks FAILED -- rejects in file src/connection.c
patching file src/wayland-client.c
Hunk #1 succeeded at 751 (offset 3 lines).
Hunk #2 succeeded at 1426 (offset 3 lines).
patching file src/wayland-private.h
patching file src/wayland-server.c
Hunk #3 succeeded at 1029 (offset 33 lines).
Hunk #4 succeeded at 1139 (offset 33 lines).
Hunk #5 succeeded at 1210 (offset 33 lines).
patching file src/wayland-util.c
Patch 0003-Enhance-Wayland-debug-print.patch does not apply (enforce with -f)
ERROR: wayland-1.17.0-r0 do_patch:
ERROR: wayland-1.17.0-r0 do_patch: Function failed: patch_do_patch

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-77937] Create GPVB with Yocto 2.7
[PLAT-115142] CCC: Upgrade to Yocto 2.7 Warrior

Change-Id: I19cf84fddd7b06cb4111a8b092259fecc031e5ee