webos: iotivity=r9 (fix build with inheritted ccache)
:Release Notes:
Without WITH_ENV build_common/SConscript does:
        CC = os.environ['CC']
        target_prefix = CC.split()[0]
        target_prefix = target_prefix[:-3]
        tools = {
            "CC": target_prefix + "gcc",
            "CXX": target_prefix + "g++"
so with ccache enabled it doesn't find right target_prefix from:
env.iotivity.ccache:export CC="ccache aarch64-webos-linux-gcc  -mcpu=cortex-a72 -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong    -Werror=return-type --sysroot=/OE/lge/build/webos/nanbield/BUILD/work/raspberrypi4_64-webos-linux/iotivity/1.3.99+git/recipe-sysroot"
env.iotivity.noccache:export CC="aarch64-webos-linux-gcc  -mcpu=cortex-a72 -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong    -Werror=return-type --sysroot=/OE/lge/build/webos/nanbield/BUILD/work/raspberrypi4_64-webos-linux/iotivity/1.3.99+git/recipe-sysroot"

:Detailed Notes:
Fixes:
http://gecko.lge.com/jenkins/job/clean-engineering-webos-raspberrypi4-64-build/21992/console
http://gecko.lge.com:8000/Errors/Details/703841

Checking for C library curl... resource/csdk/logger/src/logger.c:59:10: fatal error: PmLogLib.h: No such file or directory
   59 | #include <PmLogLib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
no

*********************************** Error *************************************
* Cannot build hue sample. Please install libcurl.
* Example (Ubuntu):
*   sudo apt-get install libcurl4-openssl-dev
*   sudo ldconfig
* Hint: check with pkg-config --libs libcurl and clear scons cache.
* Skipping hue sample build.
*******************************************************************************
...
gcc -o resource/csdk/connectivity/lib/libcoap-4.1.1/libcoap_async.o -c -std=gnu99 -fPIC -Wall -ffunction-sections -fdata-sections -fno-exceptions -g -Wall -Wextra -fPIC -DWITH_POSIX -DSECURED -D__WITH_DTLS__ -DROUTING_EP -DWITH_BWT -DNO_EDR_ADAPTER -DNO_LE_ADAPTER -DIP_ADAPTER -DNO_TCP_ADAPTER -DNO_NFC_ADAPTER -DOC_LOG_LEVEL=INFO -DTB_LOG -DRD_CLIENT -DRD_SERVER -DNDEBUG -D__linux__ -D_GNU_SOURCE -Ideps/linux/include -Iextlibs/tinycbor/tinycbor/src -Iout/webos/aarch64/release/resource/c_common -Iresource/c_common -Iout/webos/aarch64/release/resource/c_common/oic_malloc/include -Iresource/c_common/oic_malloc/include -Iout/webos/aarch64/release/resource/c_common/oic_string/include -Iresource/c_common/oic_string/include -Iout/webos/aarch64/release/resource/c_common/oic_time/include -Iresource/c_common/oic_time/include -Iout/webos/aarch64/release/resource/c_common/ocatomic/include -Iresource/c_common/ocatomic/include -Iout/webos/aarch64/release/resource/c_common/ocrandom/include -Iresource/c_common/ocrandom/include -Iout/webos/aarch64/release/resource/c_common/octhread/include -Iresource/c_common/octhread/include -Iout/webos/aarch64/release/resource/c_common/ocevent/include -Iresource/c_common/ocevent/include -Iout/webos/aarch64/release/resource/c_common/oic_platform/include -Iresource/c_common/oic_platform/include -Iout/webos/aarch64/release/resource/c_common/octimer/include -Iresource/c_common/octimer/include -Iout/webos/aarch64/release/resource/c_common/oc_refcounter/include -Iresource/c_common/oc_refcounter/include -Iextlibs/mbedtls/mbedtls/include resource/csdk/connectivity/lib/libcoap-4.1.1/async.c
In file included from resource/oc_logger/include/oc_logger.hpp:26,
                 from resource/include/OCApi.h:40,
                 from resource/include/OCPlatform.h:30,
                 from examples/OICMiddle/OICMiddle.h:26,
                 from examples/OICMiddle/OICMiddle.cpp:27:
resource/oc_logger/include/oc_log_stream.hpp:29:10: fatal error: boost/config.hpp: No such file or directory
   29 | #include <boost/config.hpp>
      |          ^~~~~~~~~~~~~~~~~~
...
gcc -o out/webos/aarch64/release/resource/csdk/connectivity/common/src/cathreadpool_pthreads.o -c -std=gnu99 -g -Wall -Wextra -fPIC -DWITH_POSIX -DSECURED -D__WITH_DTLS__ -DROUTING_EP -DWITH_BWT -DNO_EDR_ADAPTER -DNO_LE_ADAPTER -DIP_ADAPTER -DNO_TCP_ADAPTER -DNO_NFC_ADAPTER -DOC_LOG_LEVEL=INFO -DTB_LOG -DRD_CLIENT -DRD_SERVER -DNDEBUG -D__linux__ -D_GNU_SOURCE -D__webos__ -DUSE_PMLOG_DECLARATION -DUSE_PMLOG_DECLARATION -Iout/webos/aarch64/release/resource/csdk/connectivity/api -Iresource/csdk/connectivity/api -Ideps/linux/include -Iextlibs/tinycbor/tinycbor/src -Iout/webos/aarch64/release/resource/c_common -Iresource/c_common -Iout/webos/aarch64/release/resource/c_common/oic_malloc/include -Iresource/c_common/oic_malloc/include -Iout/webos/aarch64/release/resource/c_common/oic_string/include -Iresource/c_common/oic_string/include -Iout/webos/aarch64/release/resource/c_common/oic_time/include -Iresource/c_common/oic_time/include -Iout/webos/aarch64/release/resource/c_common/ocatomic/include -Iresource/c_common/ocatomic/include -Iout/webos/aarch64/release/resource/c_common/ocrandom/include -Iresource/c_common/ocrandom/include -Iout/webos/aarch64/release/resource/c_common/octhread/include -Iresource/c_common/octhread/include -Iout/webos/aarch64/release/resource/c_common/ocevent/include -Iresource/c_common/ocevent/include -Iout/webos/aarch64/release/resource/c_common/oic_platform/include -Iresource/c_common/oic_platform/include -Iout/webos/aarch64/release/resource/c_common/octimer/include -Iresource/c_common/octimer/include -Iout/webos/aarch64/release/resource/c_common/oc_refcounter/include -Iresource/c_common/oc_refcounter/include -Iextlibs/mbedtls/mbedtls/include -Iout/webos/aarch64/release/resource/csdk/logger/include -Iresource/csdk/logger/include -Iresource/c_common -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/iotivity/1.3.99+gitAUTOINC+255060695e-r8/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/iotivity/1.3.99+gitAUTOINC+255060695e-r8/recipe-sysroot/usr/lib/glib-2.0/include -Iresource/csdk/connectivity/lib/libcoap-4.1.1/include -Iout/webos/aarch64/release/resource/csdk/connectivity/inc -Iresource/csdk/connectivity/inc -Iresource/csdk/logger/include -Iout/webos/aarch64/release/resource/csdk/connectivity/common/inc -Iresource/csdk/connectivity/common/inc -Iout/webos/aarch64/release/resource/csdk/connectivity/util/inc -Iresource/csdk/connectivity/util/inc -Iresource/c_common/octhread/include -Iresource/csdk/connectivity/common/inc -Iresource/csdk/logger/include -Iextlibs/mbedtls/mbedtls/include -Iresource/c_common/octimer/include -Iresource/csdk/security/include -Iout/webos/aarch64/release/resource/csdk/connectivity/external/inc -Iresource/csdk/connectivity/external/inc resource/csdk/connectivity/common/src/cathreadpool_pthreads.c
In file included from resource/csdk/connectivity/common/src/ulinklist.c:25:
resource/csdk/connectivity/inc/caadapterutils.h:56:10: fatal error: luna-service2/lunaservice.h: No such file or directory
   56 | #include <luna-service2/lunaservice.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-27705] Introduce ccache to meta-layer
[WRP-27901] CCC: Various build fixes

Cherry-picked-from-commit: 087262122ee83fb7b244d74f155f043bdf105916
Cherry-picked-from-branch: