bats, unbound, e2fsprogs, dnf-plugin-tui, opkg-utils: fix bash runtime dependency
:Release Notes:

:Detailed Notes:
http://caprica.lgsvl.com:8080/Errors/Details/1587222
ERROR: QA Issue: dnf-plugin-tui rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]

e2fsprogs-e2scrub package was added in oe-core commit:
  commit e5f8c1facfc3507710d7111951fe075e01c58e4e (origin/master, origin/HEAD, andre/master)
  Author: Kai Kang <kai.kang@windriver.com>
  Date:   Thu Aug 8 11:45:13 2019 -0400

    e2fsprogs: 1.44.5 -> 1.45.3

    Update e2fsprogs from 1.44.5 to 1.45.3:
    * rebase ptest.patch
    * remove 0001-create_inode-fix-copying-large-files.patch which merged by upstream
    * add new sub-package e2fsprogs-e2scrub and disable cron support

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-84805] Create GPVB with Yocto 3.0 Zeus
[PLAT-115144] CCC: Upgrade to Yocto 3.0 Zeus

Change-Id: I153b322e28ec12584b36a14c8b39cb8dcf5377ee