nmeaparser: CMakeLists.txt: Fix hardcoded 'lib' installation path
:Release Notes:
With multilib enabled the libdir is usr/lib64 instead of usr/lib.
Add PV as it's 4 commits after 1.0 tag.

:Detailed Notes:
Respect ${CMAKE_INSTALL_LIBDIR}) to fix:
http://gecko.lge.com:8000/Errors/Details/574290

ERROR: QA Issue: nmeaparser: Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/libNMEAParserLib.a
  /usr/lib/pkgconfig
  /usr/lib/pkgconfig/nmeaparser.pc
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
nmeaparser: 4 installed and not shipped files. [installed-vs-shipped]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-12446] CCC: Various build fixes
[WRP-12469] Bitbake world issues 2023-04-01

Cherry-picked-from-commit: 567e813041f2b463c798e53e45c26269a04dde8d
Cherry-picked-from-branch: