libnsbmp: respect ${CMAKE_INSTALL_LIBDIR}
:Release Notes:
With multilib enabled the libdir is usr/lib64 instead of usr/lib.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/568633

ERROR: QA Issue: libnsbmp: Files/directories were installed but not shipped in any package:
  /usr/lib/libnsbmp.so
  /usr/lib/libnsbmp.so.0.1.0
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
libnsbmp: 2 installed and not shipped files. [installed-vs-shipped]

http://gecko.lge.com:8000/Errors/Details/576717

ERROR: QA Issue: libnsbmp-dbg: found library in wrong location: /usr/lib/.debug/libnsbmp.so.0.1.0 [libdir]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-12446] CCC: Various build fixes
[WRP-12469] Bitbake world issues 2023-04-01

Cherry-picked-from-commit: 10f27b519399157c228f878d9a3aa88f0218ff3c
Cherry-picked-from-branch: