packagegroup-webos-extended: remove com.webos.service.ai from arm builds except rpi
:Release Notes:
Fix regression from WRN-9168.

:Detailed Notes:
Fixes:
ERROR: Nothing RPROVIDES 'com.webos.service.ai' (but /jenkins/mjansa/build/ose-github/kirkstone/meta-webosose/meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb RDEPENDS on or otherwise requires it)
com.webos.service.ai was skipped: incompatible with machine qemuarm (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'com.webos.service.ai' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.service.ai']
NOTE: Runtime target 'packagegroup-webos-extended' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-webos-extended', 'com.webos.service.ai']
NOTE: Runtime target 'webos-image-devel' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-devel', 'packagegroup-webos-extended', 'com.webos.service.ai']

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRN-9168] CCC: Switch official OSE image to raspberrypi4 64bit
[WRN-7408] Port AI service on rpi-64bit system
[WRN-16369] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: Icbc54c42e8ca2cfc7a82c7f1bfac7000e913c3e3