rpi: u-boot: update patches to apply on 2020.10 version
:Release Notes:
Merge the patches for rpi3 and rpi4 and update to apply on u-boot version
currently in oe-core.

:Detailed Notes:
Fixes:
ERROR: u-boot-1_2020.10-r0 do_patch: Command Error: 'quilt --quiltrc /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/u-boot/1_2020.10-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0001-Speed-up-boot-by-disable-usb-and-enable-bootcount.patch
patching file configs/rpi_3_32b_defconfig
Hunk #1 FAILED at 7.
Hunk #2 succeeded at 45 (offset 1 line).
1 out of 2 hunks FAILED -- rejects in file configs/rpi_3_32b_defconfig
patching file include/configs/rpi.h
Hunk #1 succeeded at 106 (offset 20 lines).
Patch 0001-Speed-up-boot-by-disable-usb-and-enable-bootcount.patch does not apply (enforce with -f)
ERROR: Logfile of failure stored in: /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/u-boot/1_2020.10-r0/temp/log.do_patch.5506
ERROR: Task (/jenkins/mjansa/build/ose-github/hardknott/oe-core/meta/recipes-bsp/u-boot/u-boot_2020.10.bb:do_patch) failed with exit code '1'

It's not clear why we remove
CONFIG_USE_PREBOOT=y
only from rpi_3_32b_defconfig but not from rpi_4_32b_defconfig.

CONFIG_PREBOOT was removed from both in upstream commit:
  commit 44758771eefb8e600144e2e0a13cf87b9df64276
  Author: Jonas Smedegaard <dr@jones.dk>
  Date:   Tue Jul 21 09:32:20 2020 +0200
  Subject: arm: move CONFIG_PREBOOT="usb start" to KConfig

    This commit moves CONFIG_PREBOOT="usb start" to common/KConfig
    for all boards also declaring USB_KEYBOARD.

    Besides simplifying defconfig files, this also enables support for
    board-specific CONFIG_PREBOOT for sunxi boards:
    commit 37304aaf60bf ("Convert CONFIG_USE_PREBOOT and CONFIG_PREBOOT to
    Kconfig") intended to support CONFIG_PREBOOT, but
    include/configs/sunxi-common.h hardcodes preboot as part of internally
    defined CONSOLE_STDIN_SETTINGS, silently ignoring any board-specific
    CONFIG_PREBOOT.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12997] CCC: Upgrade to Yocto 3.3 Hardknott
[PLAT-124341] Create GPVB with Yocto 3.3 Hardknott

Change-Id: I6623f73225692a693b285dc4c9b167baeb0f733c