com.webos.service.flowmanager=r2 (fix systemd service file installation)
:Release Notes:
With multilib it installs the service file in wrong location causing:
ERROR: com.webos.service.flowmanager-1.0.0-5-r1 do_package: SYSTEMD_SERVICE_com.webos.service.flowmanager value flowmgr.service does not exist
ERROR: com.webos.service.flowmanager-1.0.0-5-r1 do_package: Function failed: systemd_populate_packages
ERROR: Logfile of failure stored in: com.webos.service.flowmanager/1.0.0-5-r1/temp/log.do_package.40884
ERROR: Task (meta-webos/recipes-webos/com.webos.service.flowmanager/com.webos.service.flowmanager.bb:do_package) failed with exit code '1'

:Detailed Notes:
The file is in:
com.webos.service.flowmanager/1.0.0-5-r1/image/lib64/systemd/system/flowmgr.service
use sysconfdir like all other recipes do.

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-81478] Sync meta-webos between meta-webosose and meta-lg-webos
             (Take 2: bidirectional sync)
[PLAT-84378] CCC: Various build fixes

Change-Id: I1ef3e4da5a40379165d4e4f28e95e37fd1ad1143