webos.inc: make packagegroup-core-tools-debug MACHINE_ARCH
* fixes:
ERROR: packagegroup-core-tools-debug different signature for task do_package_write_ipk.sigdata between qemux86 and qemux86copy
NOTE: Starting bitbake server...
NOTE: Started PRServer with DBfile: /jenkins/home/anaconda/build-webos-zeus/build/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 39067, PID: 51344
Hash for dependent task strace/strace_5.3.bb:do_packagedata changed from dbfe4b9371f98eabe2801b765c928fc73a1ca42908f531c31a6683420b58605c to 6e56977c51421a9126329991835bea8f755bbab810f479f58172ddefa4d49485
Unable to find matching sigdata for /jenkins/home/anaconda/build-webos-zeus/build/oe-core/meta/recipes-devtools/strace/strace_5.3.bb:do_packagedata with hash 6e56977c51421a9126329991835bea8f755bbab810f479f58172ddefa4d49485

[PLAT-115144] CCC: Upgrade to Yocto 3.0 Zeus

Change-Id: Icf8115ed735fac1af6989c6eb2433b2b3a7a8fef