umediaserver: update 0001-waitForStop-API-is-added-for-cleanup-message-handler.patch to apply
:Release Notes:
Fix do_patch failure, but this and other .patch files should have
been integrated in source repository by component owners long time
ago.

:Detailed Notes:
Fixes:
http://gecko.lge.com/jenkins/job/webos-master-verify-raspberrypi4/13272/consoleFull

ERROR: umediaserver-1.0.0-24.gav.28-r20 do_patch: Fuzz detected:

Applying patch 0001-waitForStop-API-is-added-for-cleanup-message-handler.patch
patching file include/public/uMediaClient.h
Hunk #1 succeeded at 414 (offset -17 lines).
patching file src/media_client/uMediaClient.cpp
Hunk #1 succeeded at 1441 with fuzz 1 (offset -1094 lines).

The context lines in the patches can be updated with devtool:

    devtool modify umediaserver
    devtool finish --force-patch-refresh umediaserver <layer_path>

Don't forget to review changes done by devtool!
ERROR: umediaserver-1.0.0-24.gav.28-r20 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-310] Apply .patch files for hot-fix to corresponding repositories
[WRP-5625] CCC: Various build fixes

Change-Id: I4ecc30aaeb68f684b4239188ac44f580f296a39b