ostree-initrd: update patch file to apply
:Release Notes:
init.sh was reformatted to use spaces instead of tabs in:
https://github.com/uptane/meta-updater/commit/73bc63028975d59050642302783619b2e46de373#diff-7cae258240070d65ea6b836645076b63575190f4215eba4f6afb22c7d0e87f8c
adjust patch to apply.

:Detailed Notes:
Fixes:
ERROR: ostree-initrd-4-r0 do_patch: Applying patch '0001-Speed-up-mount-when-rather-than-just-wait.patch' on target directory '/data001/jenkins/gecko/webos_raspberrypi4-64/build/BUILD/work/all-webos-linux/ostree-initrd/4-r0'
Command Error: 'quilt --quiltrc /data001/jenkins/gecko/webos_raspberrypi4-64/build/BUILD/work/all-webos-linux/ostree-initrd/4-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0001-Speed-up-mount-when-rather-than-just-wait.patch
patching file init.sh
Hunk #1 FAILED at 55.
1 out of 1 hunk FAILED -- rejects in file init.sh
Patch 0001-Speed-up-mount-when-rather-than-just-wait.patch does not apply (enforce with -f)
ERROR: Logfile of failure stored in: /data001/jenkins/gecko/webos_raspberrypi4-64/build/BUILD/work/all-webos-linux/ostree-initrd/4-r0/temp/log.do_patch.28670
NOTE: recipe ostree-initrd-4-r0: task do_patch: Failed
ERROR: Task (/data001/jenkins/gecko/webos_raspberrypi4-64/build/meta-updater/recipes-sota/ostree-initrd/ostree-initrd.bb:do_patch) failed with exit code '1'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRN-16369] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: I9d65a144ccc1bc96e1fd2e446c69a1e817886158