mesa=webos2 (re-enable gallium-llvm)
:Release Notes:
It was disabled during upgrade to mesa-17*, because it requires newer
llvm, but then I had to backport newer llvm as well, so we can re-enable
it again.

:Detailed Notes:
This should be enabled also in Yocto 2.2 Morty based builds, but
currently it fails to build there:
| /jenkins/mjansa/build-webos-morty-mcf/BUILD/sysroots/x86_64-linux/usr/bin/i586-webos-linux/../../libexec/i586-webos-li
x/gcc/i586-webos-linux/6.2.0/ld: error: /jenkins/mjansa/build-webos-morty-mcf/BUILD/sysroots/x86_64-linux/usr/lib/libexpat.
: incompatible target
| /jenkins/mjansa/build-webos-morty-mcf/BUILD/sysroots/x86_64-linux/usr/bin/i586-webos-linux/../../libexec/i586-webos-li
x/gcc/i586-webos-linux/6.2.0/ld: error: /jenkins/mjansa/build-webos-morty-mcf/BUILD/sysroots/x86_64-linux/usr/lib/libdrm.so
incompatible target
| /jenkins/mjansa/build-webos-morty-mcf/BUILD/sysroots/x86_64-linux/usr/bin/i586-webos-linux/../../libexec/i586-webos-li
x/gcc/i586-webos-linux/6.2.0/ld: warning: skipping incompatible /jenkins/mjansa/build-webos-morty-mcf/BUILD/sysroots/x86_64
inux/usr/lib/libz.so while searching for z
| /usr/include/llvm5.0/llvm/ExecutionEngine/RTDyldMemoryManager.h:84: error: undefined reference to 'llvm::RTDyldMemoryManager::g
SymbolAddressInProcess(std::string const&)'
| /usr/include/llvm5.0/llvm/ExecutionEngine/RTDyldMemoryManager.h:84: error: undefined reference to 'llvm::RTDyldMemoryManager::g
SymbolAddressInProcess(std::string const&)'
| collect2: error: ld returned 1 exit status
| ERROR: oe_runmake failed
| make[4]: *** [gallium_dri.la] Error 1

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-44224] Include virglrenderer module in oe-core build
[PLAT-46229] Upgrade to Yocto 2.4 Rocko
[PLAT-78506] [OSE] CCC: Upgrade to Yocto 2.4 Rocko

Change-Id: Ie398a5038169df3838b9aa8eb18df6f7fb4df6e3