webos-raspberrypi: raspberrypi3-64.conf: add SDIMG_KERNELIMAGE
:Release Notes:

:Detailed Notes:
In previous commit I've imported following changes from upstream meta-raspberrypi:
1440ac8 sdcard_image-rpi.bbclass: Move SDIMG_KERNELIMAGE definitions to their machines
...

the top commit is actually only in langdale and newer, but we can import
it in advance, because it's already set in MACHINE.conf in kirkstone:
conf/machine/raspberrypi-armv8.conf:SDIMG_KERNELIMAGE ?= "kernel8.img"
conf/machine/raspberrypi-cm3.conf:SDIMG_KERNELIMAGE ?= "kernel7.img"
conf/machine/raspberrypi0-wifi.conf:SDIMG_KERNELIMAGE ?= "kernel.img"
conf/machine/raspberrypi3.conf:SDIMG_KERNELIMAGE ?= "kernel7.img"
conf/machine/raspberrypi4-64.conf:SDIMG_KERNELIMAGE ?= "kernel8.img"
conf/machine/raspberrypi4.conf:SDIMG_KERNELIMAGE ?= "kernel7l.img"
conf/machine/raspberrypi5.conf:SDIMG_KERNELIMAGE ?= "kernel_2712.img"

as well as in our meta-webos-raspberrypi copies:
meta-webos-raspberrypi/conf/machine/raspberrypi3.conf:SDIMG_KERNELIMAGE ?= "kernel7.img"
meta-webos-raspberrypi/conf/machine/raspberrypi4-64.conf:SDIMG_KERNELIMAGE ?= "kernel8.img"
meta-webos-raspberrypi/conf/machine/raspberrypi4.conf:SDIMG_KERNELIMAGE ?= "kernel7l.img"

The only missing MACHINE was raspberrypi3-64 which we don't regularly
build, but after this update the build was failing with:
http://gecko.lge.com:8000/Errors/Details/784121

ERROR: Malformed boot file entry: u-boot.bin;

bitbake-getvar shows why (see unexpanded SDIMG_KERNELIMAGE):
webos/kirkstone $ bitbake-getvar -r webos-image IMAGE_BOOT_FILES --value
bootfiles/*                  ${@make_dtb_boot_files(d)}                  ${@bb.utils.contains('RPI_USE_U_BOOT', '1',                     'Image u-boot.bin;${SDIMG_KERNELIMAGE} boot.scr',                     'Image;${SDIMG_KERNELIMAGE}', d)}

So refresh raspberrypi3-64.conf from:
https://github.com/agherzan/meta-raspberrypi/commit/1440ac858979f06ad8f2a73a5de8d25f672cc4e8

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-12001] CCC: raspberrypi3-64.conf: add SDIMG_KERNELIMAGE

Cherry-picked-from-commit: 57b72bbca1ef525c4855cd4ab1c640870ca99d47
Cherry-picked-from-branch: