mksnapshot-cross=91-r1 (inherit pkgconfig)
:Release Notes:
Newer oe-core doesn't pull many default dependencies anymore:
https://lists.openembedded.org/g/openembedded-core/message/156185
add explicit dependency on pkgconfig through pkgconfig.bbclass as
we're using it here.

:Detailed Notes:
This needs pkgconfig inherit, just like the verions 87 in:
commit dba580d2175fdfb71dfc4347d0c4a45299844c39
Author: Martin Jansa <martin.jansa@lge.com>
Date:   Tue Sep 21 06:51:54 2021 -0700

    mksnaphost-cross=r2 (inherit pkgconfig)

Fixes:
http://gecko.lge.com/Errors/Details/241331
BUILD_TARGETS are v8_snapshot_clang_x86/mksnapshot
ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: TOPDIR/BUILD/work/x86_64-linux/mksnapshot-cross-i686/87.0.4280.88-8-r1/build/Release/
Command: python TOPDIR/BUILD/work/x86_64-linux/mksnapshot-cross-i686/87.0.4280.88-8-r1/git/src/build/config/linux/pkg-config.py -s TOPDIR/BUILD/work/x86_64-linux/mksnapshot-cross-i686/87.0.4280.88-8-r1/recipe-sysroot-native -a x86 --system_libdir lib glib-2.0 gmodule-2.0 gobject-2.0 gthread-2.0
Returned 1.
stderr:

Traceback (most recent call last):
  File "TOPDIR/BUILD/work/x86_64-linux/mksnapshot-cross-i686/87.0.4280.88-8-r1/git/src/build/config/linux/pkg-config.py", line 253, in <module>
    sys.exit(main())
  File "TOPDIR/BUILD/work/x86_64-linux/mksnapshot-cross-i686/87.0.4280.88-8-r1/git/src/build/config/linux/pkg-config.py", line 148, in main
    prefix = GetPkgConfigPrefixToStrip(options, args)
  File "TOPDIR/BUILD/work/x86_64-linux/mksnapshot-cross-i686/87.0.4280.88-8-r1/git/src/build/config/linux/pkg-config.py", line 87, in GetPkgConfigPrefixToStrip
    "--variable=prefix"] + args, env=os.environ).decode('utf-8')
  File "TOPDIR/BUILD/work/x86_64-linux/mksnapshot-cross-i686/87.0.4280.88-8-r1/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "TOPDIR/BUILD/work/x86_64-linux/mksnapshot-cross-i686/87.0.4280.88-8-r1/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "TOPDIR/BUILD/work/x86_64-linux/mksnapshot-cross-i686/87.0.4280.88-8-r1/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

See //build/config/linux/BUILD.gn:55:3: whence it was called.
  pkg_config("glib") {
  ^-------------------
See //build/config/compiler/BUILD.gn:250:18: which caused the file to be included.
    configs += [ "//build/config/linux:compiler" ]
                 ^------------------------------

:Testing Performed:
Only build tested.

:QA Notes:
No change to the image.

:Issues Addressed:
[WRN-7597] CCC: Various build fixes
[WRN-3095] Create RP fork of neva 1.5 release
[WRN-6489] Prepare OSE build with chromium91
[WRN-10062] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: If97c2f3309933fa0d22f9f560c2b84fc66743ee5