python3-vcversioner: Backport a fix for ZIP file format limitation
:Release Notes:
Backport this change from warrior:
commit ac179bc18eddaa2e10191908e5518c9f94346d81
Author: Stefan Agner <stefan.agner@toradex.com>
Date:   Tue Jan 29 13:12:41 2019 +0100

    python3-vcversioner: remove egg generation

    Remove egg file build. This got introduced with commit fb1696372ff9
    ("python-vcversioner: Error Fix for recipes depend on
    python-vcversioner"). However, it seems that this was actually not
    related to the missing egg file, but to the back then missing depends
    on python-vcversioner-native. This got fixed in commit 12d09665bbee
    ("python-jsonschema, python3-jsonschema: add vcversioner-native
    dependency").

    It also causes issue when trying to build a reproducible build with a
    timestamp of 0 due to limitations of the ZIP file format used by the
    Python egg packaging.

to fix:
  File "TOPDIR/BUILD/work/qemux86-webos-linux/python3-vcversioner/2.16.0.0-r0/recipe-sysroot-native/usr/lib/python3.5/zipfile.py", line 338, in __init__
    raise ValueError('ZIP does not support timestamps before 1980')
ValueError: ZIP does not support timestamps before 1980
WARNING: exit code 1 from a shell command.

:Detailed Notes:

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-109540] CCC: Various build fixes

Change-Id: Ia5b08547eda1fe2c67530549dc34e3f7dc181c06