luna-prefs-data=r2 (fix parsing without webos as a DISTRO)
:Release Notes:
Don't assume that every DISTRO_NAME will always have at least 2 space
separated words (like 'webOS OSE') the default OE config has
'OpenEmbedded' DISTRO_NAME which causes luna-prefs-data to fail
parsing.

:Detailed Notes:
Fixes:
Parsing recipes...
WARNING: meta-webosose/meta-webos/recipes-webos/luna-prefs/luna-prefs-data.bb: Exception during build_dependencies for do_install
WARNING: meta-webosose/meta-webos/recipes-webos/luna-prefs/luna-prefs-data.bb: Error during finalise of meta-webosose/meta-webos/recipes-webos/luna-prefs/luna-prefs-data.bb
ERROR: ExpansionError during parsing meta-webosose/meta-webos/recipes-webos/luna-prefs/luna-prefs-data.bb
Traceback (most recent call last):
  File "Var <PRODUCT_DEVICE_NAME_SHORT>", line 1, in <module>
bb.data_smart.ExpansionError: Failure expanding variable PRODUCT_DEVICE_NAME_SHORT, expression was ${@ 'OpenEmbedded'.split()[1]} Device which triggered exception IndexError: list index out of range

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-79498] [OSE] CCC: Fix metadata parsing without webos as a DISTRO

Change-Id: I7fd580f08748856c113017fcdae5378458b32176