nodejs-module-usocket=r2
:Release Notes:
Fix random do_populate_lic failures.

:Detailed Notes:
Using S = "${WORKDIR}/package" is really bad idea as the same directory
is used by do_package task.

This was causing:
NOTE: recipe lib32-nodejs-module-usocket-0.0.4-r1: task do_populate_lic: Started
WARNING: lib32-nodejs-module-usocket-0.0.4-r1 do_populate_lic: Could not copy license file nodejs-module-usocket/0.0.4-r1/package/LICENSE to nodejs-module-usocket/0.0.4-r1/license-destdir/lib32-nodejs-module-usocket/LICENSE: [Errno 2] No such file or directory: 'nodejs-module-usocket/0.0.4-r1/package/LICENSE'
ERROR: lib32-nodejs-module-usocket-0.0.4-r1 do_populate_lic: QA Issue: lib32-nodejs-module-usocket: LIC_FILES_CHKSUM points to an invalid file: nodejs-module-usocket/0.0.4-r1/package/LICENSE [license-checksum]
NOTE: recipe lib32-nodejs-module-usocket-0.0.4-r1: task do_populate_lic: Succeeded

can happen whenever do_populate_lic task is executed after do_package
task already replaced the component source in ${WORKDIR}/package with the
packaged files.

:Testing Performed:
Only build tested.

:QA Notes:
N/A

:Issues Addressed:
[PLAT-77762] lib32-nodejs-module-usocket fails to build
[PLAT-67935] Issues caused by sync
[PLAT-77764] CCC: nodejs-module-usocket=r2
[PLAT-81507] [OSE] CCC: Import few more changes

Change-Id: I1309fb4815a19a37c2780fea467ba9b9fb5e2a2c