rpi: fix build for raspberrypi3*
:Release Notes:
Previous commit added SAFSERVICE variable to RDEPENDS_append_rpi, but defined
it only for raspberrypi4 and raspberrypi4-64 (to empty), causing:
  ERROR: Nothing RPROVIDES '${SAFSERVICE}' (but
  meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb
  RDEPENDS on or otherwise requires it)

:Detailed Notes:
Set it to empty for other MACHINEs.

:Testing Performed:

:QA Notes:
NA

:Issues Addressed:
[PLAT-134812] CCC: packagegroup-webos-extended=webosrpi8 Add com.webos.service.storageaccess=1-r0,v1.0.0
[PLAT-135561] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: Id2206f6f899bb20f797decdc3d81a9597986f651