meta-webos-virtualization: blacklist some recipes from meta-virtualization
:Release Notes:
Fix signature issues introduced with meta-virtualization layer.

:Detailed Notes:
Fixes:
NOTE: Started PRServer with DBfile: /home/jenkins/anaconda/build-webos-thud/build/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 39979, PID: 17428
Loading cache...done.
Loaded 3611 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'apache2' (but /home/jenkins/anaconda/build-webos-thud/build/meta-virtualization/recipes-extended/nagios/nagios-core_4.4.2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'apache2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['apache2']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'nagios-plugins', 'nagios-core', 'apache2']

Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
NOTE: Started PRServer with DBfile: /home/jenkins/anaconda/build-webos-thud/build/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 40339, PID: 17481
Loading cache...done.
Loaded 3610 entries from dependency cache.
Parsing recipes...done.
Parsing of 2596 .bb files complete (2560 cached, 36 parsed). 3611 targets, 367 skipped, 44 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'apache2' (but /home/jenkins/anaconda/build-webos-thud/build/meta-virtualization/recipes-extended/nagios/nagios-core_4.4.2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'apache2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['apache2']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'nagios-plugins', 'nagios-core', 'apache2']

Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
NOTE: Started PRServer with DBfile: /home/jenkins/anaconda/build-webos-thud/build/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 40033, PID: 17630
Loading cache...done.
Loaded 3611 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'syslinux' (but /home/jenkins/anaconda/build-webos-thud/build/meta-virtualization/recipes-extended/ipxe/ipxe_git.bb DEPENDS on or otherwise requires it)
syslinux was skipped: incompatible with host arm-webos-linux-gnueabi (not in COMPATIBLE_HOST)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'ipxe', 'syslinux']

Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

ERROR: Nothing PROVIDES 'nagios-core' (but /home/jenkins/anaconda/build-webos-thud/build/meta-virtualization/recipes-extended/nagios/nagios-nrpe_3.2.1.bb DEPENDS on or otherwise requires it)
nagios-core was skipped: Recipe is blacklisted: Depends on apache2 from meta-webserver layer which we don't include
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'nagios-nrpe', 'nagios-core']

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-94390] Fix signature issues introduced with meta-updater and
             meta-virtualization
[PLAT-98534] CCC: Various build fixes

Change-Id: I0397006caee85c65faedace00b2f75314868927d