tensorflow-lite, armnn, armnn-tensorflow, arm-compute-library: fix various issues
:Release Notes:
Use SUMMARY instead of DESCRIPTION.

:Detailed Notes:
Use protocol=https to fix:
WARNING: lib32-tensorflow-lite-2.6.2-r0 do_fetch: URL: git://github.com/tensorflow/tensorflow.git;branch=r2.6 uses git protocol which is no longer supported by github. Please change to ;protocol=https in the url.
WARNING: lib32-armnn-tensorflow-2.6.2-r0 do_fetch: URL: git://github.com/tensorflow/tensorflow.git;branch=r2.6;name=tensorflow uses git protocol which is no longer supported by github. Please change to ;protocol=https in the url.

Use sha instead of tag name in SRCREV to prevent accessing network
every time the recipe is parsed and to fix:

ERROR: lib32-tensorflow-lite-2.6.2-r0 do_fetch: Bitbake Fetcher Error: FetchError("Recipe uses a floating tag/branch without a fixed SRCREV yet doesn't call bb.fetch2.get_srcrev() (use SRCPV in PV for OE).", None)
ERROR: Logfile of failure stored in: lib32-tensorflow-lite/2.6.2-r0/temp/log.do_fetch.2398611
ERROR: Task (virtual:multilib:lib32:meta-webos/recipes-upstreamable/tensorflow-lite/tensorflow-lite_2.6.2.bb:do_fetch) failed with exit code '1'

ERROR: lib32-arm-compute-library-21.11-r0 do_fetch: Bitbake Fetcher Error: FetchError("Recipe uses a floating tag/branch without a fixed SRCREV yet doesn't call bb.fetch2.get_srcrev() (use SRCPV in PV for OE).", None)
ERROR: Logfile of failure stored in: lib32-arm-compute-library/21.11-r0/temp/log.do_fetch.2398860
ERROR: Task (virtual:multilib:lib32:meta-webos/recipes-upstreamable/arm-compute-library/arm-compute-library_21.11.bb:do_fetch) failed with exit code '1'

ERROR: lib32-armnn-21.11-r0 do_fetch: Bitbake Fetcher Error: FetchError("Recipe uses a floating tag/branch without a fixed SRCREV yet doesn't call bb.fetch2.get_srcrev() (use SRCPV in PV for OE).", None)
ERROR: Logfile of failure stored in: lib32-armnn/21.11-r0/temp/log.do_fetch.2398954
ERROR: Task (virtual:multilib:lib32:meta-webos/recipes-upstreamable/armnn/armnn_21.11.bb:do_fetch) failed with exit code '1'

ERROR: lib32-armnn-tensorflow-2.6.2-r0 do_fetch: Bitbake Fetcher Error: FetchError("Recipe uses a floating tag/branch without a fixed SRCREV yet doesn't call bb.fetch2.get_srcrev() (use SRCPV in PV for OE).", None)
ERROR: Logfile of failure stored in: lib32-armnn-tensorflow/2.6.2-r0/temp/log.do_fetch.2399243
ERROR: Task (virtual:multilib:lib32:meta-webos/recipes-upstreamable/armnn/armnn-tensorflow_2.6.2.bb:do_fetch) failed with exit code '1'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-4984] CCC: Various build fixes

Change-Id: I89b5d6e18e5313b57e2597265c0f39ce97f29fe5