webos: webos_deploy.bbclass: inherit image-artifact-names
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: When reparsing virtual:multilib:lib32:foo.bb:do_webos_deploy_fixup, the basehash value changed from 4034380ed75210556fd312e9a6c97d2ab26719a4a956f5a496437993dba19683 to d2ceb3201365a264cf0d17a0ea7315ad4012c322ed62e9668f17fafecd0e3137. The metadata is not deterministic and this needs to be fixed.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-16196] CCC: Upgrade to Yocto 4.1 Langdale
[WRR-2115] Create GPVB with Yocto 4.1 Langdale

Cherry-picked-from-commit: 6dcccae2cec70811855a6fe45ba379e445840e5c
Cherry-picked-from-branch: