webos: webos-recipe-blacklist.inc: add SKIP_RECIPE for qtdoc from Qt 6.7
:Release Notes:
It was added in 6.7 and it's not usable in our builds.

:Detailed Notes:
Fixes:
ERROR: Nothing PROVIDES 'qtpdf' (but
  meta-qt6/recipes-qt/qt6/qtdoc_git.bb
  DEPENDS on or otherwise requires it)
qtpdf was skipped: Recipe will be skipped because: fails to build with widgets disabled in qtbase: Failed to find required Qt component Widgets. http://gecko.lge.com:8000/Errors/Details/565740
ERROR: Nothing PROVIDES 'qtmultimedia' (but
  meta-qt6/recipes-qt/qt6/qtdoc_git.bb
  DEPENDS on or otherwise requires it)
qtmultimedia was skipped: Recipe will be skipped because: fails to build: qtmultimedia/6.0.0-r1/git/src/qtmultimediaquicktools/qsgvideonode_texture.cpp:56:30: error: 'class QSGRhiSupport' has no member named 'isRhiEnabled'. http://gecko.lge.com:8000/Errors/Details/565741
qtmultimedia was skipped: Recipe will be skipped because: fails to build: qtmultimedia/6.0.0-r1/git/src/qtmultimediaquicktools/qsgvideonode_texture.cpp:56:30: error: 'class QSGRhiSupport' has no member named 'isRhiEnabled'. http://gecko.lge.com:8000/Errors/Details/565741
ERROR: Nothing PROVIDES 'qtgraphs' (but
  meta-qt6/recipes-qt/qt6/qtdoc_git.bb
  DEPENDS on or otherwise requires it)
qtgraphs was skipped: Recipe will be skipped because: fails to build with ninja: error: unknown target 'install' http://gecko.lge.com:8000/Errors/Details/728937
ERROR: Nothing PROVIDES 'qtcharts' (but
  meta-qt6/recipes-qt/qt6/qtdoc_git.bb
  DEPENDS on or otherwise requires it)
qtcharts was skipped: Recipe will be skipped because: fails to build with ninja: error: unknown target 'install' http://gecko.lge.com:8000/Errors/Details/565734
ERROR: Nothing RPROVIDES 'qtdoc-plugins' (but
  meta-qt6/recipes-qt/qt6/qtdoc_git.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'qtdoc-plugins'
NOTE: Runtime target 'qtdoc-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtdoc-plugins']
ERROR: Nothing RPROVIDES 'qtdoc-dev' (but
  meta-qt6/recipes-qt/qt6/qtdoc_git.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'qtdoc-dev'
NOTE: Runtime target 'qtdoc-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtdoc-dev']
ERROR: Nothing RPROVIDES 'qtdoc-staticdev' (but
  meta-qt6/recipes-qt/qt6/qtdoc_git.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'qtdoc-staticdev'
NOTE: Runtime target 'qtdoc-staticdev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtdoc-staticdev']
ERROR: Nothing RPROVIDES 'qtdoc' (but
  meta-qt6/recipes-qt/qt6/qtdoc_git.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'qtdoc'
NOTE: Runtime target 'qtdoc' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtdoc']
ERROR: Nothing RPROVIDES 'qtdoc-qmlplugins' (but
  meta-qt6/recipes-qt/qt6/qtdoc_git.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'qtdoc-qmlplugins'
NOTE: Runtime target 'qtdoc-qmlplugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtdoc-qmlplugins']

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-27223] CCC: webos-recipe-blacklist.inc: add SKIP_RECIPE for qtdoc from Qt 6.7

Cherry-picked-from-commit: ed7b4a74891952ca0f234820ca40b42b9de06e64
Cherry-picked-from-branch: