gator=r3,v6.9
:Release Notes:
Cleanup recipe and upgrade to slightly newer version, otherwise
gator fails to build with x86 kernel even after enabling profiling
in qemux86 kernel.

:Detailed Notes:
Nobody will probably use ARM gator on x86, but there is no COMPATIBLE_MACHINE
restriction in gator recipe and currently it fails for qemux86 with:
work/qemux86-webos-linux/gator/6.7+gitAUTOINC+3ff46fedd4-r2/git/driver/gator_main.c:1399:41: error: initialization of 'struct tracepoint * const*' from incompatible pointer type 'const tracepoint_ptr_t *' {aka 'const int *'} [-Werror=incompatible-pointer-types]
 1399 |     struct tracepoint * const * begin = tp_mod->mod->tracepoints_ptrs;
      |                                         ^~~~~~
work/qemux86-webos-linux/gator/6.7+gitAUTOINC+3ff46fedd4-r2/git/driver/gator_main.c:1400:39: error: initialization of 'struct tracepoint * const*' from incompatible pointer type 'const tracepoint_ptr_t *' {aka 'const int *'} [-Werror=incompatible-pointer-types]
 1400 |     struct tracepoint * const * end = tp_mod->mod->tracepoints_ptrs + tp_mod->mod->num_tracepoints;
      |                                       ^~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-121806] CCC: various build issues

Change-Id: I4b5e88ac8ad83546b30242694bdaa21b97872fa8