webos: features: enable IMAGE_FEATURES only for recipes which inherit webos_image
:Release Notes:
These entries are added to IMAGE_FEATURES[validitems] only in
webos_image.bbclass, so don't add them unless the recipe inherits it.

:Detailed Notes:
Fixes building core-image-minimal which was failing with:
ERROR: Nothing PROVIDES 'core-image-minimal'
core-image-minimal was skipped: 'webos-minimal' in IMAGE_FEATURES is not a valid image feature. Valid features: allow-empty-password allow-root-login bash-completion-pkgs dbg-pkgs debug-tweaks dev-pkgs doc doc-pkgs eclipse-debug empty-root-password hwcodecs lic-pkgs nfs-client nfs-server overlayfs-etc package-management post-install-logging ptest-pkgs qtcreator-debug read-only-rootfs read-only-rootfs-delayed-postinsts splash src-pkgs ssh-server-dropbear ssh-server-openssh stateless-rootfs staticdev-pkgs tools-debug tools-profile tools-sdk tools-testapps weston x11 x11-base x11-sato

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-10951] CCC: features: enable IMAGE_FEATURES only for recipes which
            inherit webos_image
[WRR-2117] Create GPVB with Yocto 5.0 Scarthgap

Cherry-picked-from-commit: e141c450d5954c92ef53af26c4a523a8ed383249
Cherry-picked-from-branch: