webos: nodejs-module-webos-sysbus=r18 (fix build with nodejs-20)
:Release Notes:
Since nodejs-v19 with V8 10.7.193.13 update in:
https://github.com/nodejs/node/commit/6bd756d7c6dfb7dc25daee329ad70df68c14223e#diff-cd657bc27f0b2d10cdad8e5ab9a494141566941d3ce08e4755d90a95478f1ff9
we need C++17 for is_lvalue_reference_v

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/713433

gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory 'TOPDIR/BUILD/work/qemux86_64-webos-linux/nodejs-module-webos-sysbus/3.0.1-15/git/build'
  ACTION Generating trusted scripts list src/trusted_scripts.inc
  CXX(target) Release/obj.target/webos-sysbus/src/node_ls2.o
In file included from ../../node-v20.5.1/deps/v8/include/v8-object.h:9,
                 from ../../node-v20.5.1/deps/v8/include/v8-array-buffer.h:13,
                 from ../../node-v20.5.1/deps/v8/include/v8.h:24,
                 from ../../node-v20.5.1/src/node.h:73,
                 from ../src/node_ls2.cpp:19:
../../node-v20.5.1/deps/v8/include/v8-maybe.h:106:45: error: 'is_lvalue_reference_v' is not a member of 'std'; did you mean 'is_lvalue_reference'?
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                                             ^~~~~~~~~~~~~~~~~~~~~
      |                                             is_lvalue_reference
../../node-v20.5.1/deps/v8/include/v8-maybe.h:106:66: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                                                                  ^
../../node-v20.5.1/deps/v8/include/v8-maybe.h:106:67: error: template argument 1 is invalid
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                                                                   ^
../../node-v20.5.1/deps/v8/include/v8-maybe.h:106:71: error: expected unqualified-id before '>' token
  106 |   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
      |                                                                       ^
../../node-v20.5.1/deps/v8/include/v8-maybe.h:123:43: error: 'is_lvalue_reference_v' is not a member of 'std'; did you mean 'is_lvalue_reference'?
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                                           ^~~~~~~~~~~~~~~~~~~~~
      |                                           is_lvalue_reference
../../node-v20.5.1/deps/v8/include/v8-maybe.h:123:64: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                                                                ^
../../node-v20.5.1/deps/v8/include/v8-maybe.h:123:65: error: template argument 1 is invalid
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                                                                 ^
../../node-v20.5.1/deps/v8/include/v8-maybe.h:123:70: error: expected unqualified-id before '=' token
  123 | template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
      |                                                                      ^
../../node-v20.5.1/src/node.h:705:28: error: 'std::string_view' has not been declared
  705 |     Environment* env, std::string_view main_script_source_utf8);
      |                            ^~~~~~~~~~~
make: *** [webos-sysbus.target.mk:136: Release/obj.target/webos-sysbus/src/node_ls2.o] Error 1
make: Leaving directory 'TOPDIR/BUILD/work/qemux86_64-webos-linux/nodejs-module-webos-sysbus/3.0.1-15/git/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (TOPDIR/BUILD/work/qemux86_64-webos-linux/nodejs-module-webos-sysbus/3.0.1-15/recipe-sysroot-native/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 6.5.6-gentoo
gyp ERR! command "TOPDIR/BUILD/work/qemux86_64-webos-linux/nodejs-module-webos-sysbus/3.0.1-15/recipe-sysroot-native/usr/bin/node" "TOPDIR/BUILD/work/qemux86_64-webos-linux/nodejs-module-webos-sysbus/3.0.1-15/recipe-sysroot-native/usr/bin/node-gyp" "--arch" "x86_64" "--nodedir" "TOPDIR/BUILD/work/qemux86_64-webos-linux/nodejs-module-webos-sysbus/3.0.1-15/node-v20.5.1" "build"
gyp ERR! cwd TOPDIR/BUILD/work/qemux86_64-webos-linux/nodejs-module-webos-sysbus/3.0.1-15/git
gyp ERR! node -v v20.5.1
gyp ERR! node-gyp -v v6.1.0

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-29491] Create GPVB with Yocto 5.0 Scarthgap
[WRP-29200] CCC: Various build fixes

Cherry-picked-from-commit: 4e42ec1293ec0050d6aa8b044fe1a11299979a19
Cherry-picked-from-branch: