libgdrive=r2 (fix various issues)
:Release Notes:
Fix LICENSE, LIC_FILES_CHKSUM.
Add PV (instead of default 1.0).
Drop incorrect and unnecessary inherits.
Re-enable do_package_qa task ans fix:
  ERROR: libgdrive-1.0-r1 do_package_qa: QA Issue: FILES in libgdrive
  recipe should not contain the ${D} variable as it references
  the local build directory not the target filesystem, best
  solution is to remove the ${D} reference [expanded-d]
Drop FILES_${PN} because it doesn't do anything (static libs are still
packaged in ${PN}-staticlib.

:Detailed Notes:

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-141296] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: Ie84223fae64886bf7ac35023b7d8a1f08c5e512d