webos: webos.conf: add synaptics-killswitch to LICENSE_FLAGS_ACCEPTED
:Release Notes:
Add it to unblock builds after:
https://github.com/agherzan/meta-raspberrypi/commit/7c31b9b4b595c3e0f932391e07a5258a9f966e4c
but the upstream issue should be carefully monitored in:
https://github.com/RPi-Distro/firmware-nonfree/issues/29
and someone from license team should review this.

:Detailed Notes:
Also use single append and sort the entries in alphabetical order.

Fixes:
ERROR: Nothing RPROVIDES 'linux-firmware-rpidistro-bcm43455' (but /OE/lge/build/webos/langdale/meta-lg-webos/meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb RDEPENDS on or otherwise requires it)
linux-firmware-rpidistro RPROVIDES linux-firmware-rpidistro-bcm43455 but was skipped: because it has a restricted license 'synaptics-killswitch'. Which is not listed in LICENSE_FLAGS_ACCEPTED
NOTE: Runtime target 'linux-firmware-rpidistro-bcm43455' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['linux-firmware-rpidistro-bcm43455']
NOTE: Runtime target 'packagegroup-webos-extended' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-webos-extended', 'linux-firmware-rpidistro-bcm43455']
NOTE: Runtime target 'webos-image' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image', 'packagegroup-webos-extended', 'linux-firmware-rpidistro-bcm43455']

linux-firmware-rpidistro-bcm43455 is pulled through MACHINE_EXTRA_RRECOMMENDS
in MACHINE.conf for rpi3, rpi3-64, rpi4, rpi4-64.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-16196] CCC: Upgrade to Yocto 4.1 Langdale
[WRR-2115] Create GPVB with Yocto 4.1 Langdale

Cherry-picked-from-commit: b515f9401c018d007b5a65aa6d3dc36ebccfdcac
Cherry-picked-from-branch: