systemd=webos8 (update patches to apply on 249.3 version)
:Release Notes:
Also add proper .patch headers and use BPN in FILESEXTRAPATHS.

:Detailed Notes:
Fixes:
ERROR: systemd-1_249.3-r0 do_patch: Applying patch '0002-add-webos-interface.patch' on target directory '/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/systemd/1_249.3-r0/git'
Command Error: 'quilt --quiltrc /jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/systemd/1_249.3-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
stdout: Applying patch 0002-add-webos-interface.patch
patching file src/oom/com.webos.MemoryManager1.conf
patching file src/oom/meson.build
patching file src/oom/oomd-manager.c
Hunk #3 succeeded at 473 (offset -4 lines).
patching file src/oom/oomd.c
patching file src/oom/webos-manager-bus.c
patching file src/oom/webos-manager-bus.h
patching file src/oom/webos-manager.c
patching file src/oom/webos-manager.h
patching file units/systemd-oomd.service.in
Hunk #1 FAILED at 22.
1 out of 1 hunk FAILED -- rejects in file units/systemd-oomd.service.in
Patch 0002-add-webos-interface.patch does not apply (enforce with -f)

stderr:
ERROR: Logfile of failure stored in: /jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/systemd/1_249.3-r0/temp/log.do_patch.1987716
ERROR: Task (/jenkins/mjansa/build/webos/honister/oe-core/meta/recipes-core/systemd/systemd_249.3.bb:do_patch) failed with exit code '1'

:Testing Performed:
Only build tested.

:QA Notes:
None.

:Issues Addressed:
[WRN-10062] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: I549e0ffb796e88fe6c1221ff84f3c7dc5638ba29