webos: sleepd=r12 (ignore incompatible-pointer-types issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/821709
sleepd/2.0.0-17/git/src/pwrevents/shutdown.c:912:45: error: passing argument 3 of 'get_json_string' from incompatible pointer type [-Wincompatible-pointer-types]
sleepd/2.0.0-17/git/src/pwrevents/shutdown.c:964:45: error: passing argument 3 of 'get_json_string' from incompatible pointer type [-Wincompatible-pointer-types]
sleepd/2.0.0-17/git/src/pwrevents/shutdown.c:1020:47: error: passing argument 3 of 'get_json_string' from incompatible pointer type [-Wincompatible-pointer-types]
sleepd/2.0.0-17/git/src/pwrevents/shutdown.c:1095:47: error: passing argument 3 of 'get_json_string' from incompatible pointer type [-Wincompatible-pointer-types]
sleepd/2.0.0-17/git/src/pwrevents/shutdown.c:1151:43: error: passing argument 3 of 'get_json_string' from incompatible pointer type [-Wincompatible-pointer-types]
sleepd/2.0.0-17/git/src/pwrevents/shutdown.c:1192:43: error: passing argument 3 of 'get_json_string' from incompatible pointer type [-Wincompatible-pointer-types]
sleepd/2.0.0-17/git/src/pwrevents/suspend_ipc.c:83:47: error: passing argument 3 of 'get_json_string' from incompatible pointer type [-Wincompatible-pointer-types]
sleepd/2.0.0-17/git/src/pwrevents/suspend_ipc.c:145:39: error: passing argument 3 of 'get_json_string' from incompatible pointer type [-Wincompatible-pointer-types]
sleepd/2.0.0-17/git/src/pwrevents/suspend_ipc.c:214:39: error: passing argument 3 of 'get_json_string' from incompatible pointer type [-Wincompatible-pointer-types]
sleepd/2.0.0-17/git/src/pwrevents/suspend_ipc.c:269:47: error: passing argument 3 of 'get_json_string' from incompatible pointer type [-Wincompatible-pointer-types]
sleepd/2.0.0-17/git/src/pwrevents/suspend_ipc.c:578:45: error: passing argument 3 of 'get_json_string' from incompatible pointer type [-Wincompatible-pointer-types]
sleepd/2.0.0-17/git/src/pwrevents/suspend_ipc.c:630:45: error: passing argument 3 of 'get_json_string' from incompatible pointer type [-Wincompatible-pointer-types]
sleepd/2.0.0-17/git/src/pwrevents/suspend_ipc.c:698:45: error: passing argument 3 of 'get_json_string' from incompatible pointer type [-Wincompatible-pointer-types]
sleepd/2.0.0-17/git/src/pwrevents/suspend_ipc.c:752:45: error: passing argument 3 of 'get_json_string' from incompatible pointer type [-Wincompatible-pointer-types]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19569] CCC: sleepd=r12 (ignore incompatible-pointer-types issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: b11db05a615176543168902646c082840d2cdcc3
Cherry-picked-from-branch: