tensorflow-lite: use system abseil-cpp and don't install libabsl*.so libraries
:Release Notes:
Prevent installing another copy of libabsl*.so* libraries it causes
conflict with abseil-cpp for e.g. com.webos.service.ai.

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/464636

DEBUG: Executing python function extend_recipe_sysroot
NOTE: Direct dependencies are ['TOPDIR/meta-lg-webos/meta-webos/recipes-webos/cmake-modules-webos/cmake-modules-webos-native.bb:do_populate_sysroot', 'TOPDIR/meta-lg-webos/meta-webos/recipes-webos/libgoogleassistant/libgoogleassistant.bb:do_populate_sysroot', 'TOPDIR/meta-lg-webos/meta-webos/recipes-webos/luna-service2/luna-service2.bb:do_populate_sysroot', 'TOPDIR/meta-lg-webos/meta-webos/recipes-webos/pmloglib/pmloglib.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-core/glib-2.0/glib-2.0_2.72.3.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-core/glibc/glibc_2.35.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-core/systemd/systemd-systemctl-native.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-devtools/cmake/cmake-native_3.22.3.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-devtools/gcc/gcc-cross_11.3.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-devtools/gcc/gcc-runtime_11.3.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-devtools/json-c/json-c_0.15.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/icecc-create-env/icecc-create-env_0.1.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/ninja/ninja_1.10.2.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/pkgconfig/pkgconfig_git.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot']
ERROR: The file /usr/lib/libabsl_strings.so is installed by both tensorflow-lite and abseil-cpp, aborting
DEBUG: Python function extend_recipe_sysroot finished

This was introduced by
[WRO-12665] CCC: pulseaudio=39 audiod=45
which added tensorflow-lite into dependency tree of
com.webos.service.ai which was already depending on abseil-cpp as:
libgoogleassistant -> grpc -> abseil-cpp

For runtime I was able to work around this by backporting
abseil-cpp-20210324.2 which uses SOVERSION 0, so abseil-cpp
was installing libabsl_*.so.0 and tensorflow-lite libabsl_*.so,
but now with build time dependency on both they will conflict
on /usr/lib/libabsl_strings.so in sysroot (unversioned library
from tensorflow-lite and devel symlink from abseil-cpp).

I've also tried to set ABSL_ENABLE_INSTALL in the bundled version
in tensorflow-lite, but it cannot be set explicitly, because:
  if(NOT DEFINED CMAKE_INSTALL_PREFIX OR CMAKE_INSTALL_PREFIX IN_LIST SYSTEM_INSTALL_DIRS)
    message(WARNING "\
  The default and system-level install directories are unsupported except in LTS \
  releases of Abseil.  Please set CMAKE_INSTALL_PREFIX to install Abseil in your \
  source or build tree directly.\
    ")
  endif()

And just dropping libabsl_*.so installation and adding dependency
on abseil-cpp fails as well with:
ERROR: tensorflow-lite-2.6.2-r4 do_package_qa: QA Issue: /usr/share/aif/benchmark_model contained in package tensorflow-lite requires libabsl_strings.so()(64bit), but no providers found in RDEPENDS:tensorflow-lite? [file-rdeps]
because abseil-cpp package will provide libabsl_strings.so.0
libabsl_strings.so symlink is in abseil-cpp-dev.

The only way to enforce using system abseil-cpp seems to be
removal of Findabsl.cmake (to let CMake find abslConfig.cmake
from system abseil-cpp).

To make things worse tflite has another bundled abseil-cpp
with different version.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12997] CCC: Upgrade to Yocto 3.3 Hardknott
[PLAT-124341] Create GPVB with Yocto 3.3 Hardknott

Change-Id: I22732ce8a0346b102d5f38ffad65dae393247286