{kirkstone-start} webos: PNBLACKLIST: update for Yocto 4.0 Kirkstone
:Release Notes:
unblacklist libgusb, libpeas and packagegroup-meta-multimedia

:Detailed Notes:
libpeas was fixed in:
  commit 87ce97805e48d0a0f0321c117545caf80458c3ec
  Author: Andreas Müller <schnitzeltony@gmail.com>
  Date:   Mon Aug 10 22:24:10 2020 +0200

    libpeas: disable tests when introspection is not enabled/available

    This fixes introspection-less build. Sent upstream so hope they either
    agree or come up with something better next release.

    Tested before and after adding the patch by setting GI_DATA_ENABLED = 'False'

I've sent fix for libgusb now and will be included in kirkstone.
Fixes also newly added fwupd which depended on blacklisted libgusb:
ERROR: Nothing PROVIDES 'libgusb' (but /jenkins/home/anaconda/webos-rolling-kirkstone/meta-openembedded/meta-oe/recipes-bsp/fwupd/fwupd_1.7.1.bb DEPENDS on or otherwise requires it)
libgusb was skipped: Recipe is blacklisted: ERROR: libgusb-0.3.0+gitAUTOINC+636efc0624-r0 do_configure: meson failed: gusb/meson.build:128:6: ERROR: Unknown variable libgusb_girtarget.
ERROR: Nothing RPROVIDES 'fwupd' (but /jenkins/home/anaconda/webos-rolling-kirkstone/meta-openembedded/meta-oe/recipes-bsp/fwupd/fwupd_1.7.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'fwupd'
NOTE: Runtime target 'fwupd' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fwupd']
ERROR: Nothing RPROVIDES 'fwupd-dev' (but /jenkins/home/anaconda/webos-rolling-kirkstone/meta-openembedded/meta-oe/recipes-bsp/fwupd/fwupd_1.7.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'fwupd-dev'
NOTE: Runtime target 'fwupd-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fwupd-dev']

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12999] CCC: Upgrade to Yocto 4.0 Kirkstone
[WRN-9820] Create GPVB with Yocto 4.0 Kirkstone

Change-Id: I49f17fec3d203f5aabfb33fa0cbe2a04c379f235