webos: gator-mod=r5.3 (gator_fs: Fix build with linux-6.6 and newer)
:Release Notes:
In Linux commit 13bc24457850583a2e7203ded05b7209ab4bc5ef, direct access
to the i_ctime member of struct inode was removed. The new approach is
to use accessor methods that exclusively handle passing the timestamp
around by value.

:Detailed Notes:
More details in e.g.:
https://github.com/darkbasic/zfs/commit/0769c0050e073ffdf58f37d4bdc0771db4aa9c4a

Fixes:
http://gecko.lge.com:8000/Errors/Details/758170

In file included from TOPDIR/BUILD/work/qemux86_64-webos-linux/gator-mod/6.7+git/git/driver/gator_main.c:260:
TOPDIR/BUILD/work/qemux86_64-webos-linux/gator-mod/6.7+git/git/driver/gator_fs.c: In function 'gatorfs_get_inode':
TOPDIR/BUILD/work/qemux86_64-webos-linux/gator-mod/6.7+git/git/driver/gator_fs.c:46:50: error: 'struct inode' has no member named 'i_ctime'; did you mean 'i_atime'?
   46 |         inode->i_atime = inode->i_mtime = inode->i_ctime = current_time(inode);
      |                                                  ^~~~~~~
      |                                                  i_atime

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-8231] CCC: gator-mod=r5.3 (gator_fs: Fix build with linux-6.6 and newer)
[WRP-29491] Create GPVB with Yocto 5.0 Scarthgap

Cherry-picked-from-commit: e2e96c1bc0d4a1f27520b2632c0f36092d2cc753
Cherry-picked-from-branch: