webos: packagegroup-webos-extended=r51 packagegroup-webos-devel=r2
:Release Notes:
Respect DISTRO_FEATURES when adding packages to packagegroups.

:Detailed Notes:
ERROR: Nothing RPROVIDES 'com.webos.app.mediagallery' (but
  meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb
  RDEPENDS on or otherwise requires it)
com.webos.app.mediagallery was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES
NOTE: Runtime target 'com.webos.app.mediagallery' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.app.mediagallery']
ERROR: Nothing RPROVIDES 'packagegroup-webos-extended' (but
  meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-webos-extended'
NOTE: Runtime target 'packagegroup-webos-extended' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-webos-extended']
ERROR: Nothing RPROVIDES 'g-media-pipeline' (but
  meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb
  RDEPENDS on or otherwise requires it)
g-media-pipeline was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES
NOTE: Runtime target 'g-media-pipeline' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['g-media-pipeline']
ERROR: Nothing RPROVIDES 'luna-surfacemanager-base-tests' (but
  meta-webos/recipes-core/packagegroups/packagegroup-webos-test.bb
  RDEPENDS on or otherwise requires it)
luna-surfacemanager RPROVIDES luna-surfacemanager-base-tests but was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES
NOTE: Runtime target 'luna-surfacemanager-base-tests' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['luna-surfacemanager-base-tests']
NOTE: Runtime target 'packagegroup-webos-test' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-webos-test', 'luna-surfacemanager-base-tests']
ERROR: Nothing RPROVIDES 'qml-webos-framework-tools' (but
  meta-webos/recipes-core/packagegroups/packagegroup-webos-devel.bb
  RDEPENDS on or otherwise requires it)
qml-webos-framework RPROVIDES qml-webos-framework-tools but was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES
NOTE: Runtime target 'qml-webos-framework-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qml-webos-framework-tools']
ERROR: Nothing RPROVIDES 'packagegroup-webos-devel' (but
  meta-webos/recipes-core/packagegroups/packagegroup-webos-devel.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-webos-devel'
NOTE: Runtime target 'packagegroup-webos-devel' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-webos-devel']

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-19081] CCC: packagegroup-webos-extended=r51 packagegroup-webos-devel=r2
[WRQ-7027] ...
[WRQ-8249] ...
[WRQ-7034] ...
[WRQ-17413] ...

Cherry-picked-from-commit: f7ee15020b5413a94dcdfb032f80d18867e1714c
Cherry-picked-from-branch: