rt-tests, ettercap, igt-gpu-tools, iptables, fuse3, sshfs-fuse, expat, bzip2, libssh2: fix build-deps QA issue with bash
:Release Notes:

:Detailed Notes:
ERROR: iptables-1.8.5-r0 do_package_qa: QA Issue: iptables-apply rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]
added in oe-core commit:
9a2386443a iptables: split iptables-apply to its own package

ERROR: igt-gpu-tools-1.25+gitAUTOINC+d16ad07e7f-r0 do_package_qa: QA Issue: igt-gpu-tools rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]
ERROR: igt-gpu-tools-1.25+gitAUTOINC+d16ad07e7f-r0 do_package_qa: QA Issue: igt-gpu-tools-tests rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]
ERROR: igt-gpu-tools-1.25+gitAUTOINC+d16ad07e7f-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12996] CCC: Upgrade to Yocto 3.2 Gatesgarth
[PLAT-122546] Create GPVB with Yocto 3.2 Gatesgarth

Change-Id: If7b7c1b92dcc5ae119414a38869b0548820ca747