webos-sota: inherit image-artifact-names for IMAGE_BASENAME
:Release Notes:

:Detailed Notes:
Otherwise all builds with meta-updater layer and sota enabled
  fail with:

ERROR: Sota's config sanity checker detected a potential misconfiguration.
Please fix the cause of this error then you can continue to build.
Following is the list of potential problems / advisories:

OSTREE_BRANCHNAME Should only contain characters from the character set [a-zA-Z0-9._-].

because OSTREE_BRANCHNAME will contain unexpanded '${IMAGE_BASENAME}' like this:
OSTREE_BRANCHNAME = "${IMAGE_BASENAME}-master"

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12996] CCC: Upgrade to Yocto 3.2 Gatesgarth
[PLAT-122546] Create GPVB with Yocto 3.2 Gatesgarth

Change-Id: Id2ffb061dee9014c6c180b9ddbc0fc3b2118dcc3