webos: db8=r41 (CMakeLists.txt: replace -std=c++14 with -std=c++17 for icu-75-1)
:Release Notes:
icu-75 now requires C++17 (up from C++11) and C11 (up from C99).
https://icu.unicode.org/download/75

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/854464

FAILED: src/db/CMakeFiles/mojodb.dir/MojDbTextCollator.cpp.o
ccache TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/db8/3.2.0-32/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/db8/3.2.0-32/recipe-sysroot -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -Dmojodb_EXPORTS -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/db8/3.2.0-32/git/inc -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/db8/3.2.0-32/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/db8/3.2.0-32/recipe-sysroot/usr/lib/glib-2.0/include -mcpu=cortex-a72+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/db8/3.2.0-32/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/db8/3.2.0-32/git=/usr/src/debug/db8/3.2.0-32  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/db8/3.2.0-32/git=/usr/src/debug/db8/3.2.0-32  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/db8/3.2.0-32/build=/usr/src/debug/db8/3.2.0-32  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/db8/3.2.0-32/build=/usr/src/debug/db8/3.2.0-32  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/db8/3.2.0-32/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/db8/3.2.0-32/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/db8/3.2.0-32/recipe-sysroot-native=  -fvisibility-inlines-hidden -pthread -DUSE_PMLOG -DWITH_SNAPPY_COMPRESSION -Wall -Wextra -fPIC -Wconversion -std=c++14 -Wno-unused-but-set-variable -Wno-unused-variable -fno-exceptions -frename-registers -DMOJ_LINUX -fno-strict-aliasing -Wno-psabi -DMOJ_INTERNAL -D_REENTRANT -Werror=return-type -Wno-unused-parameter -Wno-empty-body -Wl,--no-undefined -DWITH_SEARCH_QUERY_CACHE -DNDEBUG -fPIC -MD -MT src/db/CMakeFiles/mojodb.dir/MojDbTextCollator.cpp.o -MF src/db/CMakeFiles/mojodb.dir/MojDbTextCollator.cpp.o.d -o src/db/CMakeFiles/mojodb.dir/MojDbTextCollator.cpp.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/db8/3.2.0-32/git/src/db/MojDbTextCollator.cpp
In file included from ../recipe-sysroot/usr/include/unicode/uset.h:36,
                 from ../recipe-sysroot/usr/include/unicode/unorm2.h:35,
                 from ../recipe-sysroot/usr/include/unicode/unorm.h:25,
                 from ../recipe-sysroot/usr/include/unicode/ucol.h:17,
                 from ../git/src/db/MojDbTextCollator.cpp:22:
../recipe-sysroot/usr/include/unicode/localpointer.h:561:26: error: 'auto' parameter not permitted in this context
  561 | template <typename Type, auto closeFunction>
      |                          ^~~~
...

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-23876] CCC: db8=r41 (CMakeLists.txt: replace -std=c++14 with -std=c++17 for icu-75-1)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead

Cherry-picked-from-commit: 2fb4ca529ef1983dafe83d863930a1d4d8348b4a
Cherry-picked-from-branch: