webos: report-error.bbclass: Fix build with undefined PREMIRROR
:Release Notes:
Fix previous change to work when PREMIRROR isn't set at all.

:Detailed Notes:
ERROR: Command execution failed: Traceback (most recent call last):
  File "/home/user/2482_build/tv/bitbake/lib/bb/command.py", line 126, in runAsyncCommand
    commandmethod(self.cmds_async, self, options)
  File "/home/user/2482_build/tv/bitbake/lib/bb/command.py", line 607, in buildTargets
    command.cooker.buildTargets(pkgs_to_build, task)
  File "/home/user/2482_build/tv/bitbake/lib/bb/cooker.py", line 1578, in buildTargets
    bb.event.fire(bb.event.BuildStarted(buildname, ntargets), self.databuilder.mcdata[mc])
  File "/home/user/2482_build/tv/bitbake/lib/bb/event.py", line 222, in fire
    fire_class_handlers(event, d)
  File "/home/user/2482_build/tv/bitbake/lib/bb/event.py", line 123, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/user/2482_build/tv/bitbake/lib/bb/event.py", line 93, in execute_handler
    ret = handler(event)
  File "/home/user/2482_build/tv/meta-lg-webos/meta-webos/classes/report-error.bbclass", line 331, in defaulterrorreport_handler
    jsondata['premirror'] = errorreport_get_premirror(e)
  File "/home/user/2482_build/tv/meta-lg-webos/meta-webos/classes/report-error.bbclass", line 179, in errorreport_get_premirror
    premirror = e.data.getVar("PREMIRRORS").replace("\\n", "\\n\n")
AttributeError: 'NoneType' object has no attribute 'replace'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-13541] CCC: report-error.bbclass: Fix build with undefined PREMIRROR
[WRQ-13775] Apply Build Fix for none PREMIRROR set

Cherry-picked-from-commit: f7582b221180004c5de1a5fc5098899fbd6a0b19
Cherry-picked-from-branch: