webos: raspberrypi: linux-raspberrypi=webosrpi35: update seed-voicecard for 6.6 kernel
:Release Notes:
The patch unfortunately isn't using #ifdefs to be backwards compatible with
older kernels, but we can easily use minver here to apply it only for
newer kernel as 6.6.21 from:
https://github.com/agherzan/meta-raspberrypi/commit/e9a1940bab9d634779c8bcb054163dd81ba328d8

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/800291

../../../../../work-shared/raspberrypi4-64/kernel-source/sound/soc/codecs/ac101.c: In function 'ac101_hw_params':
../../../../../work-shared/raspberrypi4-64/kernel-source/sound/soc/codecs/ac101.c:1083:38: error: 'struct snd_soc_dai' has no member named 'stream_active'
 1083 |                         if (codec_dai->stream_active[SNDRV_PCM_STREAM_CAPTURE] && dmic_used && codec_aif1_fs[i].samp_rate == 44100) {
      |                                      ^~
make[5]: *** [TOPDIR/BUILD/work-shared/raspberrypi4-64/kernel-source/scripts/Makefile.build:243: sound/soc/codecs/ac101.o] Error 1
make[5]: *** Waiting for unfinished jobs....

In file included from ../../../../../work-shared/raspberrypi4-64/kernel-source/include/linux/device.h:15,
                 from ../../../../../work-shared/raspberrypi4-64/kernel-source/include/linux/acpi.h:14,
                 from ../../../../../work-shared/raspberrypi4-64/kernel-source/include/linux/i2c.h:13,
                 from ../../../../../work-shared/raspberrypi4-64/kernel-source/sound/soc/codecs/ac108.c:21:
../../../../../work-shared/raspberrypi4-64/kernel-source/sound/soc/codecs/ac108.c: In function 'ac108_hw_params':
../../../../../work-shared/raspberrypi4-64/kernel-source/sound/soc/codecs/ac108.c:656:28: error: 'struct snd_soc_dai' has no member named 'stream_active'
  656 |                         dai->stream_active[SNDRV_PCM_STREAM_PLAYBACK], dai->stream_active[SNDRV_PCM_STREAM_CAPTURE]);
      |                            ^~
../../../../../work-shared/raspberrypi4-64/kernel-source/include/linux/dev_printk.h:129:48: note: in definition of macro 'dev_printk'
  129 |                 _dev_printk(level, dev, fmt, ##__VA_ARGS__);            \
      |                                                ^~~~~~~~~~~
../../../../../work-shared/raspberrypi4-64/kernel-source/sound/soc/codecs/ac108.c:654:9: note: in expansion of macro 'dev_dbg'
  654 |         dev_dbg(dai->dev, "%s() stream=%s play:%d capt:%d +++\n", __func__,
      |         ^~~~~~~
../../../../../work-shared/raspberrypi4-64/kernel-source/sound/soc/codecs/ac108.c:656:75: error: 'struct snd_soc_dai' has no member named 'stream_active'
  656 |                         dai->stream_active[SNDRV_PCM_STREAM_PLAYBACK], dai->stream_active[SNDRV_PCM_STREAM_CAPTURE]);
      |                                                                           ^~
../../../../../work-shared/raspberrypi4-64/kernel-source/include/linux/dev_printk.h:129:48: note: in definition of macro 'dev_printk'
  129 |                 _dev_printk(level, dev, fmt, ##__VA_ARGS__);            \
      |                                                ^~~~~~~~~~~
../../../../../work-shared/raspberrypi4-64/kernel-source/sound/soc/codecs/ac108.c:654:9: note: in expansion of macro 'dev_dbg'
  654 |         dev_dbg(dai->dev, "%s() stream=%s play:%d capt:%d +++\n", __func__,
      |         ^~~~~~~
../../../../../work-shared/raspberrypi4-64/kernel-source/sound/soc/codecs/ac108.c:667:66: error: 'struct snd_soc_dai' has no member named 'stream_active'
  667 |         if ((substream->stream == SNDRV_PCM_STREAM_CAPTURE && dai->stream_active[SNDRV_PCM_STREAM_PLAYBACK])
      |                                                                  ^~
../../../../../work-shared/raspberrypi4-64/kernel-source/sound/soc/codecs/ac108.c:668:67: error: 'struct snd_soc_dai' has no member named 'stream_active'
  668 |          || (substream->stream == SNDRV_PCM_STREAM_PLAYBACK && dai->stream_active[SNDRV_PCM_STREAM_CAPTURE])) {
      |                                                                   ^~
../../../../../work-shared/raspberrypi4-64/kernel-source/sound/soc/codecs/ac108.c: At top level:
../../../../../work-shared/raspberrypi4-64/kernel-source/sound/soc/codecs/ac108.c:1548:21: error: initialization of 'int (*)(struct i2c_client *)' from incompatible pointer type 'int (*)(struct i2c_client *, const struct i2c_device_id *)' [-Werror=incompatible-pointer-types]
 1548 |         .probe =    ac108_i2c_probe,
      |                     ^~~~~~~~~~~~~~~
../../../../../work-shared/raspberrypi4-64/kernel-source/sound/soc/codecs/ac108.c:1548:21: note: (near initialization for 'ac108_i2c_driver.probe')
cc1: some warnings being treated as errors
make[5]: *** [TOPDIR/BUILD/work-shared/raspberrypi4-64/kernel-source/scripts/Makefile.build:243: sound/soc/codecs/ac108.o] Error 1
make[4]: *** [TOPDIR/BUILD/work-shared/raspberrypi4-64/kernel-source/scripts/Makefile.build:480: sound/soc/codecs] Error 2
make[3]: *** [TOPDIR/BUILD/work-shared/raspberrypi4-64/kernel-source/scripts/Makefile.build:480: sound/soc] Error 2
make[2]: *** [TOPDIR/BUILD/work-shared/raspberrypi4-64/kernel-source/scripts/Makefile.build:480: sound] Error 2
make[2]: *** Waiting for unfinished jobs....

This fix is again generated from HinTak's fork, please donate to him.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-14874] CCC: raspberrypi: linux-raspberrypi=webosrpi35: update seed-voicecard for 6.6 kernel
[WRQ-504] Create GPVB with Yocto 5.0 Scarthgap

Cherry-picked-from-commit: d40b8543b53e41f82ae2eabb1b94f39af092e580
Cherry-picked-from-branch: