com.webos.service.mediaindexer=r4 (fix parsing without webos DISTRO)
:Release Notes:
Fix issues detected by yocto-check-layer.
All VIRTUAL-RUNTIME assignments should have weak assignment before use!

:Detailed Notes:
Fixes error reported by yocto-check-layer:
ERROR: Nothing RPROVIDES '${VIRTUAL-RUNTIME_pdm}' (but meta-webos/recipes-multimedia/com.webos.service.mediaindexer/com.webos.service.mediaindexer.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target '${VIRTUAL-RUNTIME_pdm}' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['${VIRTUAL-RUNTIME_pdm}']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'com.webos.service.mediaindexer', '${VIRTUAL-RUNTIME_pdm}']

:Testing Performed:
Build test done
CAT was passed

:QA Notes:
N/A

:Issues Addressed:
[PLAT-123586] CCC: ose: downgrade GPLv3 component
[PLAT-117224] Licenses GPL-3.0 and LGPL-3.0 found in OSE components
[PLAT-127791] Create meta-lg-gplv2 layer
[PLAT-128326] CCC: Introduce meta-lg-gplv2

Change-Id: Ic80ff2270ee7e8fcb3fd5d8b8c63f907b34ca64f