pmtrace=r10
:Release Notes:
Add runtime dependency on python-core to fix QA error.

:Detailed Notes:
Fixes:
http://caprica.lgsvl.com:8080/Errors/Details/1585692
ERROR: QA Issue: /usr/bin/perf_log_viewer.py contained in package
  pmtrace requires /usr/bin/python, but no providers found in
  RDEPENDS_pmtrace? [file-rdeps]

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-84802] CCC: Fix missing runtime dependencies

Change-Id: I7174dc0e981a7d6809f8676dc42616df763eaa9f