webos: pulseaudio=webos14 (ignore incompatible-pointer-types, int-conversion, implicit-function-declaration issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/822524
src/pulsecore/resampler.c:1744:26: error: assignment to 'unsigned int (*)(pa_resampler *, const pa_memchunk *, unsigned int,  pa_memchunk *, unsigned int *)' from incompatible pointer type 'void (*)(pa_resampler *, const pa_memchunk *, unsigned int,  pa_memchunk *, unsigned int *)' [-Wincompatible-pointer-types]
src/pulsecore/resampler.c:1824:23: error: passing argument 1 of 'palm_free' from incompatible pointer type [-Wincompatible-pointer-types]
src/pulsecore/resampler.c:1846:19: error: passing argument 1 of 'palm_free' from incompatible pointer type [-Wincompatible-pointer-types]
src/pulsecore/resampler.c:2154:27: error: implicit declaration of function 'fabsf' [-Wimplicit-function-declaration]
src/pulsecore/resampler.c:2289:34: error: implicit declaration of function 'av_resample'; did you mean 'palm_resample'? [-Wimplicit-function-declaration]
src/pulsecore/resampler.c:2326:9: error: implicit declaration of function 'av_resample_close' [-Wimplicit-function-declaration]
src/pulsecore/resampler.c:2343:30: error: assignment to 'struct AVResampleContext *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
src/pulsecore/resampler.c:2343:32: error: implicit declaration of function 'av_resample_init'; did you mean 'speex_resample_int'? [-Wimplicit-function-declaration]
src/pulse/simple.c:390:41: error: passing argument 3 of 'pa_stream_cork' from incompatible pointer type [-Wincompatible-pointer-types]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19569] CCC: pulseaudio=webos14 (ignore incompatible-pointer-types, int-conversion, implicit-function-declaration issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: e4f742daafae50b93e41791e1ad3d74d2286a0b8
Cherry-picked-from-branch: