bootchart2=r10
:Release Notes:
Update runtime dependency on python3.

:Detailed Notes:
Fixes:
http://caprica.lgsvl.com:8080/Errors/Details/1587025
ERROR: QA Issue: /usr/bin/pybootchartgui contained in package bootchart2
  requires /usr/bin/python3, but no providers found in
  RDEPENDS_bootchart2? [file-rdeps]

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-84802] CCC: Fix missing runtime dependencies

Change-Id: If15506fdf6c4c775230837ae4c5b393b203ee0b2