webos: tflite-auto-delegation=r6 (respect DISTRO_FEATURES)
:Release Notes:
gl-backend checks only MACHINE_FEATURES, but doesn't respect DISTRO_FEATURES

:Detailed Notes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'virtual/egl' (but
  meta-webos/recipes-webos/tflite-auto-delegation/tflite-auto-delegation.bb
  DEPENDS on or otherwise requires it)
vc-graphics PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics
vc-graphics-hardfp PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics-hardfp
ERROR: Nothing PROVIDES 'virtual/libgles2' (but
  meta-webos/recipes-webos/tflite-auto-delegation/tflite-auto-delegation.bb
  DEPENDS on or otherwise requires it)
vc-graphics PROVIDES virtual/libgles2 but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics
vc-graphics-hardfp PROVIDES virtual/libgles2 but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics-hardfp
ERROR: Nothing PROVIDES 'virtual/lib32-libgles2' (but
  virtual:multilib:lib32:meta-webos/recipes-webos/tflite-auto-delegation/tflite-auto-delegation.bb
  DEPENDS on or otherwise requires it)
lib32-vc-graphics PROVIDES virtual/lib32-libgles2 but was skipped: PREFERRED_PROVIDER_virtual/lib32-libgles2 set to lib32-mesa, not lib32-vc-graphics
lib32-vc-graphics-hardfp PROVIDES virtual/lib32-libgles2 but was skipped: PREFERRED_PROVIDER_virtual/lib32-libgles2 set to lib32-mesa, not lib32-vc-graphics-hardfp
ERROR: Nothing PROVIDES 'virtual/lib32-egl' (but
  virtual:multilib:lib32:meta-webos/recipes-webos/tflite-auto-delegation/tflite-auto-delegation.bb
  DEPENDS on or otherwise requires it)
lib32-vc-graphics PROVIDES virtual/lib32-egl but was skipped: PREFERRED_PROVIDER_virtual/lib32-libgles2 set to lib32-mesa, not lib32-vc-graphics
lib32-vc-graphics-hardfp PROVIDES virtual/lib32-egl but was skipped: PREFERRED_PROVIDER_virtual/lib32-libgles2 set to lib32-mesa, not lib32-vc-graphics-hardfp
ERROR: Nothing RPROVIDES 'tflite-auto-delegation-dev' (but
  meta-webos/recipes-webos/tflite-auto-delegation/tflite-auto-delegation.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'tflite-auto-delegation-dev'
NOTE: Runtime target 'tflite-auto-delegation-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tflite-auto-delegation-dev']
ERROR: Nothing RPROVIDES 'tflite-auto-delegation' (but
  meta-webos/recipes-webos/tflite-auto-delegation/tflite-auto-delegation.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'tflite-auto-delegation'
NOTE: Runtime target 'tflite-auto-delegation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tflite-auto-delegation']
ERROR: Nothing RPROVIDES 'lib32-tflite-auto-delegation-dev' (but
  virtual:multilib:lib32:meta-webos/recipes-webos/tflite-auto-delegation/tflite-auto-delegation.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lib32-tflite-auto-delegation-dev'
NOTE: Runtime target 'lib32-tflite-auto-delegation-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-tflite-auto-delegation-dev']
ERROR: Nothing RPROVIDES 'lib32-tflite-auto-delegation' (but
  virtual:multilib:lib32:meta-webos/recipes-webos/tflite-auto-delegation/tflite-auto-delegation.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lib32-tflite-auto-delegation'
NOTE: Runtime target 'lib32-tflite-auto-delegation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-tflite-auto-delegation']

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19569] CCC: tflite-auto-delegation=r6 (respect DISTRO_FEATURES)

Cherry-picked-from-commit: 2ef003396ec17f68e61020507ec5a7025eca8b05
Cherry-picked-from-branch: