nss: refresh do_compile from upstream recipe
* import fix from:
  https://patchwork.openembedded.org/patch/169417/

* otherwise nss fails as shown here:
  http://caprica.lgsvl.com:8080/Errors/Details/1818735
  gcm.c:112: error: undefined reference to 'gcm_HashInit_hw'
  gcm.c:467: error: undefined reference to 'gcm_HashWrite_hw'
  gcm.c:338: error: undefined reference to 'gcm_HashZeroX_hw'
  collect2: error: ld returned 1 exit status

[PLAT-115145] CCC: Upgrade to Yocto 3.1 Dunfell

Change-Id: Id2c22e2351bacbcaf9fc4de1d7e96cb36812bab7