wpa-supplicant: refresh patches to apply on 2.9 version
:Release Notes:
It doesn't apply since last CVE patch for 2.9:
https://git.openembedded.org/openembedded-core/commit/?id=81e4260b83c52558c320fd7d1c1eafcb312ad6be

:Detailed Notes:
Fixes:
ERROR: wpa-supplicant-2.9-r0 do_patch: Fuzz detected:

Applying patch 0001-Add-p2p-changes.patch
patching file src/ap/drv_callbacks.c
patching file src/ap/hostapd.c
patching file src/ap/hostapd.h
patching file src/ap/sta_info.c
patching file src/ap/wpa_auth.c
patching file src/common/ieee802_11_defs.h
patching file src/p2p/p2p.c
Hunk #1 succeeded at 1314 (offset 2 lines).
Hunk #2 succeeded at 1322 (offset 2 lines).
Hunk #3 succeeded at 1631 (offset 2 lines).
Hunk #4 succeeded at 1742 (offset 2 lines).
Hunk #5 succeeded at 1781 (offset 2 lines).
Hunk #6 succeeded at 2981 (offset 2 lines).
Hunk #7 succeeded at 3256 (offset 2 lines).
Hunk #8 succeeded at 4606 (offset 2 lines).
Hunk #9 succeeded at 4625 (offset 2 lines).
Hunk #10 succeeded at 4660 (offset 2 lines).
Hunk #11 succeeded at 4771 (offset 2 lines).
patching file src/p2p/p2p.h
patching file src/p2p/p2p_build.c
patching file src/p2p/p2p_go_neg.c
patching file src/p2p/p2p_group.c
patching file src/p2p/p2p_invitation.c
patching file src/p2p/p2p_pd.c
Hunk #1 succeeded at 602 with fuzz 2 (offset -2 lines).
patching file src/wps/wps_attr_build.c
patching file src/wps/wps_defs.h
patching file src/wps/wps_i.h
patching file wpa_supplicant/ap.c
patching file wpa_supplicant/dbus/dbus_new.c
patching file wpa_supplicant/dbus/dbus_new.h
patching file wpa_supplicant/dbus/dbus_new_handlers.c
patching file wpa_supplicant/dbus/dbus_new_handlers.h
patching file wpa_supplicant/dbus/dbus_new_handlers_p2p.c
patching file wpa_supplicant/dbus/dbus_new_handlers_p2p.h
patching file wpa_supplicant/notify.c
patching file wpa_supplicant/notify.h
patching file wpa_supplicant/p2p_supplicant.c
patching file wpa_supplicant/p2p_supplicant.h
patching file wpa_supplicant/wpa_supplicant.c

The context lines in the patches can be updated with devtool:

    devtool modify wpa-supplicant
    devtool finish --force-patch-refresh wpa-supplicant <layer_path>

Don't forget to review changes done by devtool!

ERROR: wpa-supplicant-2.9-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-122546] Create GPVB with Yocto 3.2 Gatesgarth
[PLAT-138245] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: I162cd574bf1e0f49674008ef97c990e7ae3954ec