rpm=webos3 (fix QA issues)
:Release Notes:
Fixes:
ERROR: QA Issue: rpm rdepends on bash, but it isn't a build
dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]

:Detailed Notes:
bash was added to RDEPENDS in upstream.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-41150] Upgrade to Yocto 2.3 Pyro
[PLAT-78505] [OSE] CCC: Upgrade to Yocto 2.3 Pyro

Change-Id: I40bce2c613b1137326f40b8606928bab19e725a2