webos: libgphoto2=webos2 (ignore incompatible-pointer-types issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/823101
libgphoto2-2.5.31/camlibs/ptp2/chdk.c:1187:41: error: passing argument 3 of 'jpeg_mem_dest' from incompatible pointer type [-Wincompatible-pointer-types]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19569] CCC: libgphoto2=webos2 (ignore incompatible-pointer-types issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: b93626b0eaaf8d7af84ea31444a550068e8f8e18
Cherry-picked-from-branch: