bluez5 (refresh patches to apply on 5.65 version)
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/448721
NOTE: Applying patch '0001-Fix-advertise-time-out-when-default-is-set-to-zero.patch' (meta-lg-webos/meta-webos/recipes-connectivity/bluez5/bluez5/0001-Fix-advertise-time-out-when-default-is-set-to-zero.patch)
NOTE: --- Patch fuzz start ---
Applying patch 0001-Fix-advertise-time-out-when-default-is-set-to-zero.patch
patching file src/advertising.c
Hunk #1 succeeded at 525 with fuzz 2.

Now at patch 0001-Fix-advertise-time-out-when-default-is-set-to-zero.patch

--- Patch fuzz end ---
NOTE: Applying patch '0002-Send-disconnect-signal-on-remote-device-disconnect.patch' (meta-lg-webos/meta-webos/recipes-connectivity/bluez5/bluez5/0002-Send-disconnect-signal-on-remote-device-disconnect.patch)
NOTE: Applying patch '0003-Fetching-device-type-like-BLE-BREDR-from-bluez.patch' (meta-lg-webos/meta-webos/recipes-connectivity/bluez5/bluez5/0003-Fetching-device-type-like-BLE-BREDR-from-bluez.patch)
NOTE: Applying patch '0004-Fix-Gatt-connect-when-device-address-type-is-BDADDR_.patch' (meta-lg-webos/meta-webos/recipes-connectivity/bluez5/bluez5/0004-Fix-Gatt-connect-when-device-address-type-is-BDADDR_.patch)
NOTE: Applying patch '0005-Use-system-bus-instead-of-session-for-obexd.patch' (meta-lg-webos/meta-webos/recipes-connectivity/bluez5/bluez5/0005-Use-system-bus-instead-of-session-for-obexd.patch)
NOTE: Applying patch '0006-Implementation-to-get-connected-profiles-uuids.patch' (meta-lg-webos/meta-webos/recipes-connectivity/bluez5/bluez5/0006-Implementation-to-get-connected-profiles-uuids.patch)
ERROR: Applying patch '0006-Implementation-to-get-connected-profiles-uuids.patch' on target directory 'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluez5/5.65-r0/bluez-5.65'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluez5/5.65-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0006-Implementation-to-get-connected-profiles-uuids.patch
patching file src/device.c
Hunk #2 succeeded at 997 (offset 9 lines).
Hunk #3 succeeded at 1916 (offset 32 lines).
Hunk #4 succeeded at 2446 (offset 32 lines).
Hunk #5 succeeded at 3059 (offset -149 lines).
Hunk #6 FAILED at 3315.
1 out of 6 hunks FAILED -- rejects in file src/device.c
Patch 0006-Implementation-to-get-connected-profiles-uuids.patch does not apply (enforce with -f)

stderr: ')
DEBUG: Python function patch_do_patch finished
DEBUG: Python function do_patch finished

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12999] CCC: Upgrade to Yocto 4.0 Kirkstone
[WRO-4709] Create GPVB with Yocto 4.1 Langdale

Change-Id: I3f698fca0ef8b2f450fb31e247c860107ce63422