wayland: update the patch files to apply on 1.18.0 version
ERROR: wayland-1.18.0-r0 do_patch: Command Error: 'quilt --quiltrc quiltrc push' exited with 0  Output:
Applying patch 0001-server-Fix-crash-when-accessing-client-which-is-alre.patch
patching file src/wayland-server.c
patch: **** malformed patch at line 36: &display->client_list, link) {

Patch 0001-server-Fix-crash-when-accessing-client-which-is-alre.patch does not apply (enforce with -f)
ERROR: Logfile of failure stored in: log.do_patch.111269
ERROR: Task (wayland_1.18.0.bb:do_patch) failed with exit code '1'
ERROR: wayland-native-1.18.0-r0 do_patch: Command Error: 'quilt --quiltrc /etc/quiltrc push' exited with 0  Output:
Applying patch 0001-server-Fix-crash-when-accessing-client-which-is-alre.patch
patching file src/wayland-server.c
patch: **** malformed patch at line 36: &display->client_list, link) {

Patch 0001-server-Fix-crash-when-accessing-client-which-is-alre.patch does not apply (enforce with -f)
ERROR: Logfile of failure stored in: log.do_patch.111273
ERROR: Task (wayland_1.18.0.bb:do_patch) failed with exit code '1'

[PLAT-115145] CCC: Upgrade to Yocto 3.1 Dunfell

Change-Id: I5f62d1fd1cb83f51ffdb4447c695819a0c983eaa