meta-webos: define LAYERDEPENDS
:Release Notes:
Define LAYERDEPENDS to fix layer parsing with yocto-check-layer tool.

:Detailed Notes:
Fixes:
$ yocto-check-layer -- /OE/meta-webosose/meta-webos
INFO: Detected layers:
INFO: meta-webos: LayerType.DISTRO, /OE/meta-webosose/meta-webos
INFO:
INFO: Setting up for meta-webos(LayerType.DISTRO), /OE/meta-webosose/meta-webos
INFO: Getting initial bitbake variables ...
INFO: Getting initial signatures ...
INFO: Adding layer meta-webos
INFO: Starting to analyze: meta-webos
INFO: ----------------------------------------------------------------------
INFO: skipped "BSPCheckLayer: Layer meta-webos isn't BSP one."
INFO: test_layerseries_compat (common.CommonCheckLayer)
INFO:  ... ok
INFO: test_parse (common.CommonCheckLayer)
INFO:  ... ERROR
INFO: Traceback (most recent call last):
  File "/OE/openembedded-core/scripts/lib/checklayer/cases/common.py", line 30, in test_parse
    check_command('Layer %s failed to parse.' % self.tc.layer['name'],
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 256, in check_command
    raise RuntimeError(msg)
RuntimeError: Layer meta-webos failed to parse.
Command: bitbake -p
Output:
Loading cache...done.
Loaded 0 entries from dependency cache.
Parsing recipes...WARNING: /OE/meta-webosose/meta-webos/recipes-webos/com.webos.app.enactbrowser/com.webos.app.enactbrowser.bb: Recipe com.webos.app.enactbrowser sets S variable with trailing slash '/OE/openembedded-core/build/tmp-glibc/work/core2-64-oe-linux/com.webos.app.enactbrowser/1.0.0-32-r11/git/', remove it
WARNING: /OE/meta-webosose/meta-webos/recipes-webos/com.webos.app.enactbrowser/com.webos.app.enactbrowser.bb: Recipe com.webos.app.enactbrowser sets B variable with trailing slash '/OE/openembedded-core/build/tmp-glibc/work/core2-64-oe-linux/com.webos.app.enactbrowser/1.0.0-32-r11/git/', remove it
ERROR: ParseError at /OE/meta-webosose/meta-webos/recipes-connectivity/iotivity-node/iotivity-node_git.bb:22: Could not inherit file classes/pythonnative.bbclass

Summary: There were 2 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

INFO: test_readme (common.CommonCheckLayer)
INFO:  ... ok
INFO: test_show_environment (common.CommonCheckLayer)
INFO:  ... ok
INFO: test_signatures (common.CommonCheckLayer)
INFO:  ... ERROR
INFO: Traceback (most recent call last):
  File "/OE/openembedded-core/scripts/lib/checklayer/cases/common.py", line 52, in test_signatures
    curr_sigs, _ = get_signatures(self.td['builddir'], failsafe=True)
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 281, in get_signatures
    check_command('Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.',
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 256, in check_command
    raise RuntimeError(msg)
RuntimeError: Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.
Command: BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BB_SIGNATURE_HANDLER" BB_SIGNATURE_HANDLER="OEBasicHash" bitbake -k -S none world
Output:
Loading cache...done.
Loaded 11 entries from dependency cache.
Parsing recipes...WARNING: /OE/meta-webosose/meta-webos/recipes-webos/com.webos.app.enactbrowser/com.webos.app.enactbrowser.bb: Recipe com.webos.app.enactbrowser sets S variable with trailing slash '/OE/openembedded-core/build/tmp-glibc/work/core2-64-oe-linux/com.webos.app.enactbrowser/1.0.0-32-r11/git/', remove it
WARNING: /OE/meta-webosose/meta-webos/recipes-webos/com.webos.app.enactbrowser/com.webos.app.enactbrowser.bb: Recipe com.webos.app.enactbrowser sets B variable with trailing slash '/OE/openembedded-core/build/tmp-glibc/work/core2-64-oe-linux/com.webos.app.enactbrowser/1.0.0-32-r11/git/', remove it
ERROR: ParseError at /OE/meta-webosose/meta-webos/classes/webos_qmake5.bbclass:3: Could not inherit file classes/qmake5.bbclass

Summary: There were 2 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-122674] CCC: build fixes for host-user-contaminated QA issues

Change-Id: I85b95a2e66cdd6ff282a289645a4e302fd3b0795