ose: protobuf-c: avoid race condition
:Release Notes:
Fix below error:
In file included from ../git/t/generated-code2/cxx-generate-packed-data.cc:5:0:
./t/test-full.pb.h:4:0: error: unterminated #ifndef
 #ifndef PROTOBUF_INCLUDED_t_2ftest_2dfull_2eproto

In file included from ../git/t/generated-code2/cxx-generate-packed-data.cc:5:0:
./t/test-full.pb.h:15659:1: error: ?inlin? does not name a type
 inline void TestRequiredFieldsBitmap::set_field27(const ::std::string& value) {
 ^~~~~
../git/t/generated-code2/cxx-generate-packed-data.cc:1169:1: error: expected ?}? at end of input
 }
 ^
Makefile:1554: recipe for target 't/generated-code2/cxx_generate_packed_data-cxx-generate-packed-data.o' failed
make: *** [t/generated-code2/cxx_generate_packed_data-cxx-generate-packed-data.o] Error 1
make: *** Waiting for unfinished jobs....
WARNING: exit code 1 from a shell command.

:Detailed Notes:
Add commits from warrior branch of meta-oe.

    Author: Qi.Chen@windriver.com <Qi.Chen@windriver.com>
    Date:   Thu Oct 17 20:45:24 2019 +0000

    protobuf-c: fix race condition

    Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
    Signed-off-by: Khem Raj <raj.khem@gmail.com>
    Signed-off-by: Sinan Kaya <okaya@kernel.org>
    (cherry picked from commit 489d3b4b932ee8016d792341f8ea5836a9522cd4)
    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
    Signed-off-by: Armin Kuster <akuster808@gmail.com>

    Date: Sun, 29 Sep 2019 17:20:42 +0800
    Subject: [PATCH] avoid race condition

    It's possible that the cxx-generate-packed-data.cc is compiled
    while the t/test-full.pb.h is being generated. This will result
    the following error.

:Testing Performed:
Only build tested.

:QA Notes:
None.

:Issues Addressed:
[PLAT-115973] protobuf-c-native 1.3.1 fails with yocto 3.1 on Jenkins
[PLAT-115976] CCC: ose: protobuf-c: avoid race condition

Change-Id: I4fbe6d83f23b167fdd868e61ec049db271000068