ecryptfs-utils: set --with-pamdir to fix QA issue with usrmerge
:Release Notes:
It uses /lib/security by default, but with usrmerge we need to set
this to /usr/lib/security (${base_libdir}/security).

:Detailed Notes:
Fixes:
ERROR: lib32-ecryptfs-utils-111-r1 do_package: QA Issue: lib32-ecryptfs-utils: Files/directories were installed but not shipped in any package:
  /lib/security/pam_ecryptfs.so
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
lib32-ecryptfs-utils: 1 installed and not shipped files. [installed-vs-shipped]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-24156] CCC: Various build fixes

Cherry-picked-from-commit: 02309b5a4f261f4b0c7c5f92b9e8e82f3a7ee32d
Cherry-picked-from-branch: