webos: bluez5=webos31 (ignore incompatible-pointer-types, implicit-function-declaration issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/819467
bluez-5.72/src/main.c:1042:41: error: passing argument 4 of 'parse_config_bool' from incompatible pointer type [-Wincompatible-pointer-types]
caused by 0012-Support-enabling-avdtp-delayReport.patch

bluez-5.72/profiles/audio/avrcp.c:4004:9: error: implicit declaration of function 'set_avrcp_ct_supported_events' [-Wimplicit-function-declaration]
caused by 0017-AVRCP-getting-supported-notification-events.patch

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19955] CCC: bluez5=webos31 (ignore incompatible-pointer-types, implicit-function-declaration issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: aa2643d351e139698649f0e7891a6eb628f48908
Cherry-picked-from-branch: