sstate.bbclass: fix error handling when sstate mirrors is ro
:Release Notes:
Fix error handling when sstate mirrors is ro.
These patchs should be removed when yocto version up.

:Detailed Notes:
The commit dd555537fc35c5f934af09d601d70772eb5955ae
 'sstate.bbclass: fix errors about read-only sstate mirrors'
 adds an additional exception handler to silently mask read
 only rootfs errors thrown during the touch.

The exception handler checks the error type with the python module errno
but this module needs to be imported as it don't exist.

Example of the error:

File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:sstate_task_postfunc(d)
     0003:
File: '/home/builder/src/base/poky/meta/classes/sstate.bbclass',
       lineno: 778, function: sstate_task_postfunc
     0774:
     0775:    omask = os.umask(0o002)
     0776:    if omask != 0o002:
     0777:       bb.note("Using umask 0o002 (not %0o)
                               for sstate packaging" % omask)
 *** 0778:    sstate_package(shared_state, d)
     0779:    os.umask(omask)
     0780:
     0781:    sstateinst = d.getVar("SSTATE_INSTDIR")
     0782:    d.setVar('SSTATE_FIXMEDIR', shared_state['fixmedir'])
File: '/home/builder/src/base/poky/meta/classes/sstate.bbclass',
                    lineno: 708, function: sstate_package
     0704:        except PermissionError:
     0705:            pass
     0706:        except OSError as e:
     0707:            # Handle read-only file systems gracefully
 *** 0708:            if e.errno != errno.EROFS:
     0709:                raise e
     0710:
     0711:    return
     0712:
Exception: NameError: name 'errno' is not defined

:Testing Performed:
build tested

:QA Notes:
No changes to image

:Issues Addressed:

Change-Id: Ib1b5170088d31c6fd9f62ab11511b1a27fd43235