webos: ofono=webos3 (ignore implicit-function-declaration issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/821863
ofono-2.4/drivers/hfpmodem/voicecall.c:1081:17: error: implicit declaration of function 'usleep'; did you mean 'g_usleep'? [-Wimplicit-function-declaration]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19569] CCC: ofono=webos3 (ignore implicit-function-declaration issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: a1410a77ba066779c9f3b884019f7b7c8a334ea3
Cherry-picked-from-branch: