rpi: mesa: update 0001-implement-wl-drm-create-linear-prime-buffer.patch to apply on 20.0.1 version
http://gecko.lge.com/jenkins/job/clean-engineering-webos-raspberrypi4-build/2688/
http://caprica.lgsvl.com:8080/Errors/Details/1829763

NOTE: Applying patch '0001-implement-wl-drm-create-linear-prime-buffer.patch' (meta-lg-webos/meta-webos-raspberrypi/recipes-graphics/mesa/mesa/0001-implement-wl-drm-create-linear-prime-buffer.patch)
ERROR: Command Error: 'quilt --quiltrc TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/mesa/2_19.3.1-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0001-implement-wl-drm-create-linear-prime-buffer.patch
patching file include/GL/internal/dri_interface.h
Hunk #1 succeeded at 1566 (offset 13 lines).
patching file src/egl/drivers/dri2/egl_dri2.c
Hunk #1 succeeded at 2948 (offset 170 lines).
Hunk #2 succeeded at 2969 (offset 170 lines).
patching file src/egl/drivers/dri2/platform_android.c
Hunk #1 FAILED at 565.
1 out of 1 hunk FAILED -- rejects in file src/egl/drivers/dri2/platform_android.c
patching file src/egl/wayland/wayland-drm/meson.build
patching file src/egl/wayland/wayland-drm/wayland-drm.c
patching file src/egl/wayland/wayland-drm/wayland-drm.h
patching file src/egl/wayland/wayland-drm/wayland-drm.xml
Hunk #1 succeeded at 184 (offset 2 lines).
patching file src/gallium/state_trackers/dri/dri2.c
Hunk #1 succeeded at 1370 (offset 86 lines).
patching file src/gbm/backends/dri/gbm_dri.c
Hunk #1 succeeded at 955 (offset 43 lines).
patching file src/loader/loader_dri3_helper.c
Hunk #1 succeeded at 1614 (offset 7 lines).
patching file src/mesa/drivers/dri/i915/intel_screen.c
Hunk #1 succeeded at 585 (offset 1 line).
patching file src/mesa/drivers/dri/i965/intel_screen.c
Hunk #1 succeeded at 1227 (offset 14 lines).
Patch 0001-implement-wl-drm-create-linear-prime-buffer.patch does not apply (enforce with -f)

[PLAT-115145] CCC: Upgrade to Yocto 3.1 Dunfell

Change-Id: I1cf2ccd88a4383577b34757cad6999c53f7ddc10