webos: tensorflow-lite=r2.*
:Release Notes:
gl-backend checks only MACHINE_FEATURES, but doesn't respect DISTRO_FEATURES

:Detailed Notes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'virtual
  meta-webos/recipes-upstreamable/tensorflow-lite/tensorflow-lite_2.9.3.bb
  DEPENDS on or otherwise requires it)
lib32-vc-graphics PROVIDES virtual/lib32-libgles2 but was skipped: PREFERRED_PROVIDER_virtual/lib32-libgles2 set to lib32-mesa, not lib32-vc-graphics
lib32-vc-graphics-hardfp PROVIDES virtual/lib32-libgles2 but was skipped: PREFERRED_PROVIDER_virtual/lib32-libgles2 set to lib32-mesa, not lib32-vc-graphics-hardfp
ERROR: Nothing PROVIDES 'virtual
  meta-webos/recipes-upstreamable/tensorflow-lite/tensorflow-lite_2.9.3.bb
  DEPENDS on or otherwise requires it)
lib32-vc-graphics PROVIDES virtual/lib32-egl but was skipped: PREFERRED_PROVIDER_virtual/lib32-libgles2 set to lib32-mesa, not lib32-vc-graphics
lib32-vc-graphics-hardfp PROVIDES virtual/lib32-egl but was skipped: PREFERRED_PROVIDER_virtual/lib32-libgles2 set to lib32-mesa, not lib32-vc-graphics-hardfp
ERROR: Nothing PROVIDES 'virtual
  meta-webos/recipes-upstreamable/tensorflow-lite/benchmark-model_2.9.3.bb
  DEPENDS on or otherwise requires it)
vc-graphics PROVIDES virtual/libgles2 but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics
vc-graphics-hardfp PROVIDES virtual/libgles2 but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics-hardfp
ERROR: Nothing PROVIDES 'virtual
  meta-webos/recipes-upstreamable/tensorflow-lite/benchmark-model_2.9.3.bb
  DEPENDS on or otherwise requires it)
vc-graphics PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics
vc-graphics-hardfp PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics-hardfp

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-18608] CCC: tensorflow-lite=r2.*
[WRQ-7027] ...
[WRQ-8249] ...
[WRQ-7034] ...
[WRQ-17413] ...

Cherry-picked-from-commit: 9124bae0526d1442bcc4057bdbb16b0dbaac86d8
Cherry-picked-from-branch: