bluez5 (refresh patches to apply on 5.61 version)
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: bluez5-5.61-r0 do_patch: Command Error: 'quilt --quiltrc /jenkins/home/anaconda/build-webos-auto-honister/build/BUILD/work/sa8155-webos-linux/bluez5/5.61-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
stdout: Applying patch 0012-Support-enabling-avdtp-delayReport.patch
patching file profiles/audio/a2dp.c
Hunk #1 succeeded at 2333 (offset 138 lines).
patching file profiles/audio/a2dp.h
patching file profiles/audio/avdtp.c
patching file profiles/audio/avdtp.h
Hunk #1 succeeded at 308 (offset 2 lines).
patching file profiles/audio/media.c
Hunk #3 succeeded at 2433 (offset 3 lines).
patching file profiles/audio/media.h
patching file src/adapter.c
Hunk #3 succeeded at 298 (offset 3 lines).
Hunk #4 succeeded at 504 (offset 3 lines).
Hunk #5 succeeded at 3270 (offset 16 lines).
Hunk #6 succeeded at 3654 (offset 103 lines).
Hunk #7 succeeded at 5040 (offset 160 lines).
Hunk #8 succeeded at 6496 (offset 164 lines).
Hunk #9 succeeded at 6537 (offset 164 lines).
Hunk #10 succeeded at 6545 (offset 164 lines).
patching file src/adapter.h
Hunk #1 FAILED at 25.
Hunk #2 succeeded at 69 (offset 1 line).
1 out of 2 hunks FAILED -- rejects in file src/adapter.h
patching file src/btd.h
patching file src/main.c
Hunk #2 succeeded at 730 (offset 1 line).
patching file src/main.conf
Patch 0012-Support-enabling-avdtp-delayReport.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12998] CCC: Upgrade to Yocto 3.4 Honister
[PLAT-141293] Create GPVB with Yocto 3.4 Honister

Change-Id: Iad34978c85d0bf4b8dab12a06489c678523ddad3