g-camera-pipeline=r2 (fix return statement)
:Release Notes:
Don't try to return values from void functions.

:Detailed Notes:
fix:
g-camera-pipeline/1.0.0-8-r1/git/camsrc/gstcamsrc.c:197:14: error:
  'return' with a value, in function returning void
[-Werror=return-type]

:Testing Performed:
Build tested.

:QA Notes:

:Issues Addressed:
[PLAT-79213] Missing return statements from non-void functions
[PLAT-84377] CCC: Fix return statements

Change-Id: I137698f83e2fbe8ff1c640b3ce69175bbd24daa7
Reviewed-on: http://gpro.lge.com/250999
Reviewed-by: OSE Helper Bot <ose@lge.com>
Reviewed-by: Martin Jansa <martin.jansa@lge.com>
Tested-by: Martin Jansa <martin.jansa@lge.com>