libgoogleassistant=r2
:Release Notes:
Fix various issues.

:Detailed Notes:
With newer meta-updater this /usr/local/atlas/lib/libtatlas.so (only
file in /usr/local) breaks do_image_ostree. With:
https://github.com/advancedtelematic/meta-updater/commit/bc6c9f098442a2c0bf4a7a40ba50c9ee5fe40cc1#diff-e2abc18e16bca9de6396cc6ab17ac27f
it fails with:
WARNING: webos-image-devel-1.0-r2 do_image: Android repo tool not found; manifest not copied.
WARNING: webos-image-devel-1.0-r2 do_image_ostree: Data in /opt directory is not preserved by OSTree. Consider moving it under /usr
WARNING: webos-image-devel-1.0-r2 do_image_ostree: Data in /mnt directory is not preserved by OSTree. Consider moving it under /usr
ERROR: webos-image-devel-1.0-r2 do_image_ostree: Data in /usr/local directory is not preserved by OSTree.
ERROR: webos-image-devel-1.0-r2 do_image_ostree: Function failed: do_image_ostree (log file is located at /jenkins/mjansa/build-webos-thud/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image-devel/1.0-r2/temp/log.do_image_ostree.16291)
ERROR: Logfile of failure stored in: /jenkins/mjansa/build-webos-thud/BUILD/work/raspberrypi3-webos-linux-gnueabi/webos-image-devel/1.0-r2/temp/log.do_image_ostree.16291

Move it to regular libdir and fix the included SONAME in this prebuilt
binary to prevent libgoogleassistant.so linking with the full path
/usr/local/atlas/lib/libtatlas.so

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-85555] CCC: Various build fixes

Change-Id: Ia64cf01745e72daa447576b405ee80086a4c6bc2