webos: webos-backports-5.0: backport fixes to build SDK without debian bbclass
:Release Notes:
Backport
https://git.openembedded.org/openembedded-core/commit/?h=scarthgap&id=8313a4201cde39c444aa6fbe82e46a767fc31f6b
https://git.openembedded.org/openembedded-core/commit/?h=scarthgap&id=372a7f2e3c5c03da044e576e1501e86f8938f5e6
to fix SDK failing to build with:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1009979

ERROR: Unable to install packages. Command 'recipe-sysroot-native/usr/bin/opkg --volatile-cache -f opkg-sdk-target.conf -t temp/ipktemp/ -o sdk/image/opt/sdk/sdk-ver/sysroots/aarch64-webos-linux  --force_postinstall --prefer-arch-to-version   --force-maintainer  --add-ignore-recommends update-rc.d install lib32-packagegroup-core-standalone-sdk-target' returned 1:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - conflicting requests
 *   - nothing provides lib32-glibc-gconv-cp1252 needed by lib32-packagegroup-core-standalone-sdk-target-1.0-r8.0.ca9v1
 *
 * Solution 1:
 *   - do not ask to install a package providing lib32-packagegroup-core-standalone-sdk-target

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-30007] CCC: webos-backports-5.0: backport fixes to build SDK
            without debian bbclass
[WRQ-30005] Drop debian renaming rules
[WRR-2117] Create GPVB with Yocto 5.0 Scarthgap
[WRR-291] [SCM SWP] Create new toolchain(BDK) for prebuilt binaries

Cherry-picked-from-commit: 8d411f22ed0aab25a8060c79d91fabead4184659
Cherry-picked-from-branch: