python3=webos2 (remove bash also with ${MLPREFIX})
:Release Notes:
It's one of the rare cases where the recipes adds bash dependency with
${MLPREFIX} since:
https://git.openembedded.org/openembedded-core/commit/?id=b3fda056a674889cd9697e779de023d4f993d3ce

:Detailed Notes:
Fixes:
ERROR: lib32-python3-3.10.4-r0 do_package_qa: QA Issue: lib32-python3-tests rdepends on lib32-bash,
  but it isn't a build dependency, missing lib32-bash in DEPENDS or PACKAGECONFIG? [build-deps]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-4984] CCC: Various build fixes

Change-Id: I83b4e3a5e69b89089813571b484f53bde64e2eb9