connman-conf: drop wired-setup
:Release Notes:
It's no longer very useful after:
  https://git.openembedded.org/openembedded-core/commit/?id=3c25b89720417a7b1963f0a32c870208a5803950

:Detailed Notes:
Now causes:
ERROR: connman-conf-1.0-r2 do_package: QA Issue: connman-conf: Files/directories were installed but not shipped in any package:
  /usr
  /usr/share
  /usr/share/connman
  /usr/share/connman/wired-setup
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
connman-conf: 4 installed and not shipped files. [installed-vs-shipped]

Should be re-evaluated and if still needed added the packaging
back in the .bbappend.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12999] CCC: Upgrade to Yocto 4.0 Kirkstone
[WRN-9820] Create GPVB with Yocto 4.0 Kirkstone

Change-Id: I4dd1bcb746ecb6414680fdab8f6592fd5369a2f7