webos.inc: use TUNE_PKGARCH for qemuwrapper-cross
:Release Notes:
Fix missing -cpu options from QEMU_EXTRAOPTIONS for qemux86 and qemux86-64.

:Detailed Notes:
With the MACHINE_ARCH being used by default in webOS it was
failing to find corresponding QEMU_EXTRAOPTIONS, because
it uses variable with PACKAGE_ARCH, see:

  # $QEMU_OPTIONS [2 operations]
  #   set /jenkins/mjansa/build/ros/webos-dashing-honister/openembedded-core/meta/classes/qemu.bbclass:57
  #     "-r ${OLDEST_KERNEL} ${@d.getVar("QEMU_EXTRAOPTIONS_%s" % d.getVar('PACKAGE_ARCH')) or ""}"
  #   append /jenkins/mjansa/build/ros/webos-dashing-honister/openembedded-core/meta/classes/qemu.bbclass:58
  #     [vardeps] "QEMU_EXTRAOPTIONS_${PACKAGE_ARCH}"
  # pre-expansion value:
  #   "-r ${OLDEST_KERNEL} ${@d.getVar("QEMU_EXTRAOPTIONS_%s" % d.getVar('PACKAGE_ARCH')) or ""}"
  QEMU_OPTIONS="-r 3.2.0 "

$ grep QEMU_.*OPTIONS.*= env.qemuwrapper-cross
QEMU_EXTRAOPTIONS_core2-32=" -cpu n270"
QEMU_EXTRAOPTIONS_core2-64=" -cpu core2duo"
QEMU_EXTRAOPTIONS_core2-64-x32=" -cpu core2duo"
QEMU_EXTRAOPTIONS_corei7-32=" -cpu Nehalem,check=false"
QEMU_EXTRAOPTIONS_corei7-64=" -cpu Nehalem,check=false"
QEMU_EXTRAOPTIONS_corei7-64-x32=" -cpu Nehalem,check=false"
QEMU_EXTRAOPTIONS_powerpc64le=" -cpu POWER8"
QEMU_EXTRAOPTIONS_ppc64e5500=" -cpu e500mc"
QEMU_EXTRAOPTIONS_ppc64e6500=" -cpu e500mc"
QEMU_EXTRAOPTIONS_ppc7400=" -cpu 7400"
QEMU_EXTRAOPTIONS_ppce500mc=" -cpu e500mc"
QEMU_EXTRAOPTIONS_ppce500v2=" -cpu e500v2"
QEMU_EXTRAOPTIONS_ppce5500=" -cpu e500mc"
QEMU_EXTRAOPTIONS_ppce6500=" -cpu e500mc"
QEMU_OPTIONS="-r 3.2.0 "

With this fix it will use correct values:
$ MACHINE=qemux86 bitbake-getvar -r qemuwrapper-cross --value QEMU_OPTIONS
-r 3.2.0  -cpu n270
$ MACHINE=qemux86-64 bitbake-getvar -r qemuwrapper-cross --value QEMU_OPTIONS
-r 3.2.0  -cpu core2duo
$ MACHINE=qemuarm bitbake-getvar -r qemuwrapper-cross --value QEMU_OPTIONS
-r 3.2.0

$ diff tmp-glibc-after/work/qemux86-webos-linux/webos-image-ros-core/1.0-r3/recipe-sysroot/usr/bin/crossscripts/qemuwrapper \
      tmp-glibc-before/work/qemux86-webos-linux/webos-image-ros-core/1.0-r3/recipe-sysroot/usr/bin/crossscripts/qemuwrapper
  10c10
  < qemu-i386 -r 3.2.0  -cpu n270 -E LD_LIBRARY_PATH=$D/usr/lib:$D/lib "$@"
  ---
  > qemu-i386 -r 3.2.0  -E LD_LIBRARY_PATH=$D/usr/lib:$D/lib "$@"

With fontconfig built with gcc-11 the postinst was failing with:

NOTE: > Executing update_font_cache intercept ...
NOTE: Exit code 132. Output:
+ '[' True = False -a qemuwrapper-cross '!=' nativesdk-qemuwrapper-cross ']'
+ qemu-i386 -r 3.2.0 -E LD_LIBRARY_PATH=/jenkins/mjansa/build/ros/webos-dashing-honister/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-core/1.0-r3/rootfs/usr/lib:/jenkins/mjansa/build/ros/webos-dashing-honister/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-core/1.0-r3/rootfs/lib -L /jenkins/mjansa/build/ros/webos-dashing-honister/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-core/1.0-r3/rootfs -E FC_DEBUG=16 /jenkins/mjansa/build/ros/webos-dashing-honister/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-core/1.0-r3/rootfs/usr/libexec/fc-cache --sysroot=/jenkins/mjansa/build/ros/webos-dashing-honister/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-core/1.0-r3/rootfs --system-only -v
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
/jenkins/mjansa/build/ros/webos-dashing-honister/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-core/1.0-r3/recipe-sysroot/usr/bin/crossscripts/qemuwrapper: line 10: 31195 Illegal instruction     qemu-i386 -r 3.2.0 -E LD_LIBRARY_PATH=$D/usr/lib:$D/lib "$@"

ERROR: The postinstall intercept hook 'update_font_cache' failed, details in /jenkins/mjansa/build/ros/webos-dashing-honister/tmp-glibc/work/qemux86-webos-linux/webos-image-ros-core/1.0-r3/temp/log.do_rootfs

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-142445] Fix build with gcc-11
[PLAT-142565] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: Ia56977124cbd85ff24a5fd17c4fd7aa7a80a6e8f