webos: nyx-modules=r20 (ignore incompatible-pointer-types and implicit-function-declaration issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/821714
nyx-modules/7.1.0-22/git/src/keys/keys_common.c:84:91: error: passing argument 4 of 'g_key_file_get_string_list' from incompatible pointer type [-Wincompatible-pointer-types]
nyx-modules/7.1.0-22/git/src/keys/keys_common.c:211:11: error: passing argument 1 of 'pipe2' from incompatible pointer type [-Wincompatible-pointer-types]
nyx-modules/7.1.0-22/git/src/device_info/device_info_generic.c:363:16: error: implicit declaration of function 'isspace' [-Wimplicit-function-declaration]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19569] CCC: nyx-modules=r20 (ignore incompatible-pointer-types and implicit-function-declaration issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: 85cb605ccd0debd68d6f66982e45961d1bf1b765
Cherry-picked-from-branch: