webos: enact-dev-native=r14 (avoid npm:* prefix in dependency versions)
:Release Notes:
Current version of npmsw fetcher doesn't support that.

:Detailed Notes:
Avoid:
http://gecko.lge.com:8000/Errors/Details/783192

ERROR: Bitbake Fetcher Error: ParameterError('Unsupported dependency: string-width-cjs', 'npmsw://TOPDIR/meta-lg-webos/meta-webos/recipes-webos/enact-dev/enact-dev/npm-shrinkwrap.json')

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-12001] CCC: enact-dev-native=r14 (avoid npm:* prefix in dependency versions)
[WRO-5448] Nodejs recipes should use bitbake fetcher to fetch
           sources in do_fetch instead of npm fetching them in
           do_install

Cherry-picked-from-commit: f1401af64643c40a3ace57fbc1a5b78f3f597149
Cherry-picked-from-branch: