wpa-supplicant: update p2p patch to apply on 2.10 version
:Release Notes:

:Detailed Notes:
Fixes:
NOTE: recipe wpa-supplicant-2.10-r0: task do_patch: Started
ERROR: wpa-supplicant-2.10-r0 do_patch: Applying patch '0001-Add-p2p-changes.patch' on target directory '/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/wpa-supplicant/2.10-r0/wpa_supplicant-2.10'
CmdError('quilt --quiltrc /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/wpa-supplicant/2.10-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0001-Add-p2p-changes.patch
patching file src/ap/drv_callbacks.c
Hunk #1 succeeded at 202 (offset 27 lines).
patching file src/ap/hostapd.c
Hunk #1 succeeded at 366 (offset 14 lines).
Hunk #2 succeeded at 2382 (offset 147 lines).
Hunk #3 FAILED at 3582.
1 out of 3 hunks FAILED -- rejects in file src/ap/hostapd.c
patching file src/ap/hostapd.h
Hunk #1 succeeded at 273 (offset 10 lines).
Hunk #2 succeeded at 300 (offset 10 lines).
Hunk #3 succeeded at 694 (offset 37 lines).
patching file src/ap/sta_info.c
Hunk #1 succeeded at 1268 (offset 45 lines).
Hunk #2 succeeded at 1295 (offset 45 lines).
Hunk #3 succeeded at 1342 (offset 45 lines).
patching file src/ap/wpa_auth.c
Hunk #1 succeeded at 729 (offset 44 lines).
Hunk #2 succeeded at 744 with fuzz 1 (offset 45 lines).
patching file src/common/ieee802_11_defs.h
Hunk #1 succeeded at 1715 (offset 68 lines).
patching file src/p2p/p2p.c
Hunk #1 succeeded at 1319 (offset 5 lines).
Hunk #2 FAILED at 1322.
Hunk #3 succeeded at 1647 (offset 20 lines).
Hunk #4 succeeded at 1758 (offset 20 lines).
Hunk #5 succeeded at 1797 (offset 20 lines).
Hunk #6 succeeded at 3005 (offset 28 lines).
Hunk #7 succeeded at 3280 (offset 28 lines).
Hunk #8 succeeded at 4646 (offset 44 lines).
Hunk #9 succeeded at 4665 (offset 44 lines).
Hunk #10 succeeded at 4700 (offset 44 lines).
Hunk #11 succeeded at 4811 (offset 44 lines).
1 out of 11 hunks FAILED -- rejects in file src/p2p/p2p.c
patching file src/p2p/p2p.h
Hunk #1 succeeded at 377 (offset 2 lines).
patching file src/p2p/p2p_build.c
patching file src/p2p/p2p_go_neg.c
Hunk #2 succeeded at 475 with fuzz 1 (offset 9 lines).
Hunk #3 succeeded at 511 (offset 9 lines).
Hunk #4 succeeded at 852 (offset 9 lines).
patching file src/p2p/p2p_group.c
patching file src/p2p/p2p_invitation.c
patching file src/p2p/p2p_pd.c
patching file src/wps/wps_attr_build.c
Hunk #2 succeeded at 209 (offset 2 lines).
patching file src/wps/wps_defs.h
patching file src/wps/wps_i.h
patching file wpa_supplicant/ap.c
Hunk #1 succeeded at 832 (offset 205 lines).
patching file wpa_supplicant/dbus/dbus_new.c
Hunk #2 succeeded at 1566 (offset 93 lines).
Hunk #3 succeeded at 1611 (offset 93 lines).
Hunk #4 succeeded at 1806 (offset 93 lines).
Hunk #5 succeeded at 1835 (offset 93 lines).
Hunk #6 succeeded at 1846 (offset 93 lines).
Hunk #7 succeeded at 1936 (offset 93 lines).
Hunk #8 succeeded at 1965 (offset 93 lines).
Hunk #9 succeeded at 1976 (offset 93 lines).
Hunk #10 succeeded at 2286 (offset 93 lines).
Hunk #11 succeeded at 2313 (offset 93 lines).
Hunk #12 succeeded at 2334 (offset 93 lines).
Hunk #13 succeeded at 2345 (offset 93 lines).
Hunk #14 succeeded at 3947 (offset 106 lines).
Hunk #15 succeeded at 4621 (offset 718 lines).
Hunk #16 succeeded at 4948 (offset 151 lines).
patching file wpa_supplicant/dbus/dbus_new.h
Hunk #1 succeeded at 213 (offset 5 lines).
Hunk #2 succeeded at 229 (offset 5 lines).
Hunk #3 succeeded at 238 (offset 5 lines).
Hunk #4 succeeded at 259 (offset 5 lines).
Hunk #5 succeeded at 452 (offset 12 lines).
Hunk #6 succeeded at 526 (offset 12 lines).
Hunk #7 succeeded at 555 (offset 12 lines).
patching file wpa_supplicant/dbus/dbus_new_handlers.c
Hunk #1 succeeded at 3481 (offset 390 lines).
Hunk #2 succeeded at 5557 (offset 603 lines).
patching file wpa_supplicant/dbus/dbus_new_handlers.h
Hunk #1 succeeded at 168 (offset 16 lines).
patching file wpa_supplicant/dbus/dbus_new_handlers_p2p.c
Hunk #1 succeeded at 1219 (offset 53 lines).
Hunk #2 succeeded at 1930 (offset 53 lines).
patching file wpa_supplicant/dbus/dbus_new_handlers_p2p.h
patching file wpa_supplicant/notify.c
Hunk #1 succeeded at 616 (offset 12 lines).
Hunk #2 succeeded at 711 (offset 12 lines).
Hunk #3 succeeded at 738 (offset 12 lines).
Hunk #4 succeeded at 750 (offset 12 lines).
Hunk #5 succeeded at 762 (offset 12 lines).
Hunk #6 succeeded at 787 (offset 12 lines).
Hunk #7 succeeded at 801 (offset 12 lines).
Hunk #8 succeeded at 910 (offset 13 lines).
patching file wpa_supplicant/notify.h
Hunk #1 succeeded at 92 (offset 1 line).
Hunk #2 succeeded at 121 (offset 1 line).
Hunk #3 succeeded at 147 (offset 1 line).
patching file wpa_supplicant/p2p_supplicant.c
Hunk #1 succeeded at 1455 (offset 58 lines).
Hunk #2 succeeded at 1890 (offset 58 lines).
Hunk #3 succeeded at 2124 (offset 159 lines).
Hunk #4 succeeded at 3254 with fuzz 2 (offset 164 lines).
Hunk #5 succeeded at 3273 (offset 169 lines).
Hunk #6 succeeded at 3304 (offset 169 lines).
Hunk #7 succeeded at 3318 (offset 169 lines).
Hunk #8 succeeded at 6912 (offset 493 lines).
Hunk #9 succeeded at 7393 (offset 498 lines).
Hunk #10 succeeded at 7800 (offset 506 lines).
Hunk #11 succeeded at 8849 (offset 509 lines).
Hunk #12 succeeded at 10123 (offset 527 lines).
patching file wpa_supplicant/p2p_supplicant.h
Hunk #1 succeeded at 221 (offset 9 lines).
patching file wpa_supplicant/wpa_supplicant.c
Hunk #1 succeeded at 130 with fuzz 2 (offset 4 lines).
Hunk #2 succeeded at 8232 (offset 1006 lines).
Hunk #3 succeeded at 8260 (offset 1006 lines).
Patch 0001-Add-p2p-changes.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12999] CCC: Upgrade to Yocto 4.0 Kirkstone
[WRN-9820] Create GPVB with Yocto 4.0 Kirkstone

Change-Id: I13b8826147192db98046877f30958ec0489180c1