webos: wayland=webos5 (fix implicit-function-declaration issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/819466
wayland-1.22.0/src/wayland-util.c:456:64: error: implicit declaration of function 'getpid' [-Wimplicit-function-declaration]
wayland-1.22.0/src/wayland-util.c:456:74: error: implicit declaration of function 'pthread_self' [-Wimplicit-function-declaration]
caused by 0004-Enhance-Wayland-debug-print.patch

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19955] CCC: wayland=webos5 (fix implicit-function-declaration issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead

Cherry-picked-from-commit: ae222fb683fc61b273ea434f6cde1f3bfcd1cc0c
Cherry-picked-from-branch: