webos: media-codec-interface=r13 (fix CMakeLists.txt to respect CMAKE_INSTALL_LIBDIR)
:Release Notes:
Improve the changes from:
[WRQ-13116] CCC: media-codec-interface=apollorpi1

With multilib enabled the libdir is usr/lib64 or usr/lib32 instead of usr/lib.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/793296

ERROR: QA Issue: lib32-media-codec-interface: Files/directories were installed but not shipped in any package:
  /usr/lib/libmedia-codec-impl.so.1
  /usr/lib/libmedia-codec-interface.so
  /usr/lib/libmedia-codec-interface.so.1
  /usr/lib/libmedia-codec-impl.so
  /usr/lib/libmedia-codec-interface.so.1.0
  /usr/lib/libmedia-codec-impl.so.1.0
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
lib32-media-codec-interface: 6 installed and not shipped files. [installed-vs-shipped]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-13879] CCC: media-codec-interface=r13 (fix CMakeLists.txt to respect CMAKE_INSTALL_LIBDIR)
[WRQ-10922] Fix compilation errors in MCIL for Apollo builds

Cherry-picked-from-commit: 4d60d8b76e7780d86758c17352e724eb0ab06be7
Cherry-picked-from-branch: