mediaindexer=r9 (fix build with gcc-13)
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/529426

FAILED: src/perf/CMakeFiles/perf.dir/performancechecker.cpp.o
TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++ -DCACHE_DIRECTORY=\"/media/.cache/\" -DCACHE_JSONFILE=\"cache.json\" -DHAS_GSTREAMER -DHAS_LUNA -DHAS_PMLOG -DHAS_TAGLIB -DJSON_CONFIGURATION_FILE=\"/etc/com.webos.service.mediaindexer/com.webos.service.mediaindexer.conf\" -DLOGGING_THREAD_ID -DPARALLEL_META_EXTRACTION=10 -DPERFCHECK_ENABLE=1 -DTHUMBNAIL_DIRECTORY=\"/media/.thumbnail/\" -DTHUMBNAIL_EXTENSION=\".jpg\" -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/include/taglib -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/include/gstreamer-1.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/include/orc-0.4 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/git/src/. -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/git/src/./jsonparser -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/git/src/./log -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/git/src/./mediaindexerclient -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/git/src/./perf -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/git/src/./cache -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/git/src/perf/. -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/git/src/perf/.. -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/git/src/perf/../log -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/git=/usr/src/debug/com.webos.service.mediaindexer/1.0.0-23-r8  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/git=/usr/src/debug/com.webos.service.mediaindexer/1.0.0-23-r8  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/build=/usr/src/debug/com.webos.service.mediaindexer/1.0.0-23-r8  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/build=/usr/src/debug/com.webos.service.mediaindexer/1.0.0-23-r8  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot-native=  -fvisibility-inlines-hidden  -std=c++17 -Wall -Wextra -fno-permissive -pthread -Wno-unused-parameter -Wno-deprecated-declarations -Wno-type-limits -Wno-comment -Werror=return-type -Werror=reorder -Werror=uninitialized -fPIC -Wl,--no-undefined -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/lib/glib-2.0/include -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/include/taglib -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/lib/glib-2.0/include -pthread -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/include/gstreamer-1.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/lib/glib-2.0/include -pthread -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/include/gstreamer-1.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/include/orc-0.4 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/include/gstreamer-1.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/recipe-sysroot/usr/lib/glib-2.0/include -g -MD -MT src/perf/CMakeFiles/perf.dir/performancechecker.cpp.o -MF src/perf/CMakeFiles/perf.dir/performancechecker.cpp.o.d -o src/perf/CMakeFiles/perf.dir/performancechecker.cpp.o -c TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/git/src/perf/performancechecker.cpp
TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediaindexer/1.0.0-23-r8/git/src/perf/performancechecker.cpp:31:44: error: 'name' has incomplete type
   31 | bool PerfChecker::addToPerfMap(std::string name)
      |                                ~~~~~~~~~~~~^~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-8053] CCC: Various build fixes

Cherry-picked-from-commit: 63d66660f2a090480ddc5155a63f3210f5d42d92
Cherry-picked-from-branch: