webos: com.webos.service.mediarecorder=r4
:Release Notes:
Add ANY_OF_DISTRO_FEATURES restriction.

:Detailed Notes:
ERROR: Nothing PROVIDES 'lib32-umediaserver' (but
  virtual:multilib:lib32:meta-webos/recipes-webos/com.webos.service.mediarecorder/com.webos.service.mediarecorder.bb
  DEPENDS on or otherwise requires it)
lib32-umediaserver was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'umediaserver' (but
  meta-webos/recipes-webos/com.webos.service.mediarecorder/com.webos.service.mediarecorder.bb
  DEPENDS on or otherwise requires it)
umediaserver was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES
ERROR: Nothing RPROVIDES 'lib32-com.webos.service.mediarecorder-dev' (but
  virtual:multilib:lib32:meta-webos/recipes-webos/com.webos.service.mediarecorder/com.webos.service.mediarecorder.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lib32-com.webos.service.mediarecorder-dev'
NOTE: Runtime target 'lib32-com.webos.service.mediarecorder-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-com.webos.service.mediarecorder-dev']
ERROR: Nothing RPROVIDES 'lib32-com.webos.service.mediarecorder' (but
  virtual:multilib:lib32:meta-webos/recipes-webos/com.webos.service.mediarecorder/com.webos.service.mediarecorder.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lib32-com.webos.service.mediarecorder'
NOTE: Runtime target 'lib32-com.webos.service.mediarecorder' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-com.webos.service.mediarecorder']
ERROR: Nothing RPROVIDES 'lib32-com.webos.service.mediarecorder-test-apps' (but
  virtual:multilib:lib32:meta-webos/recipes-webos/com.webos.service.mediarecorder/com.webos.service.mediarecorder.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'lib32-com.webos.service.mediarecorder-test-apps'
NOTE: Runtime target 'lib32-com.webos.service.mediarecorder-test-apps' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-com.webos.service.mediarecorder-test-apps']
ERROR: Nothing RPROVIDES 'com.webos.service.mediarecorder' (but
  meta-webos/recipes-webos/com.webos.service.mediarecorder/com.webos.service.mediarecorder.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'com.webos.service.mediarecorder'
NOTE: Runtime target 'com.webos.service.mediarecorder' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.service.mediarecorder']
ERROR: Nothing RPROVIDES 'com.webos.service.mediarecorder-test-apps' (but
  meta-webos/recipes-webos/com.webos.service.mediarecorder/com.webos.service.mediarecorder.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'com.webos.service.mediarecorder-test-apps'
NOTE: Runtime target 'com.webos.service.mediarecorder-test-apps' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.service.mediarecorder-test-apps']
ERROR: Nothing RPROVIDES 'com.webos.service.mediarecorder-dev' (but
  meta-webos/recipes-webos/com.webos.service.mediarecorder/com.webos.service.mediarecorder.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'com.webos.service.mediarecorder-dev'
NOTE: Runtime target 'com.webos.service.mediarecorder-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.service.mediarecorder-dev']

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-21052] CCC: com.webos.service.mediarecorder=r4

Cherry-picked-from-commit: 18b4dd02ce430257cd43630c12b94f3f88a9a767
Cherry-picked-from-branch: