com.webos.service.{ai,camera,contextintentmgr,tts}, g-camera-pipeline: don't append to COMPATIBLE_MACHINE
:Release Notes:
The append will append the value to the overriden variable, which isn't
what these COMPATIBLE_MACHINE restrictions should do here.

:Detailed Notes:
See bitbake -e output:
  # $COMPATIBLE_MACHINE [5 operations]
  #   set oe-core/meta/conf/documentation.conf:112
  #     [doc] "A regular expression that resolves to one or more target machines with which a recipe is compatible."
  #   set meta-webos/recipes-webos/com.webos.service.ai/com.webos.service.ai.bb:12
  #     "^raspberrypi3$"
  #   _append meta-webos/recipes-webos/com.webos.service.ai/com.webos.service.ai.bb:16
  #     "|^raspberrypi4$"
  #   override[raspberrypi3-64]:set meta-webos/recipes-webos/com.webos.service.ai/com.webos.service.ai.bb:13
  #     "^$"
  #   override[raspberrypi4-64]:set meta-webos/recipes-webos/com.webos.service.ai/com.webos.service.ai.bb:17
  #     "^$"
  # pre-expansion value:
  #   "^$|^raspberrypi4$"
  COMPATIBLE_MACHINE="^\$|^raspberrypi4\$"

Fixes:
ERROR: Nothing PROVIDES 'libgoogleassistant' (but meta-webos/recipes-webos/com.webos.service.ai/com.webos.service.ai.bb DEPENDS on or otherwise requires it)
libgoogleassistant was skipped: incompatible with machine raspberrypi4-64 (not in COMPATIBLE_MACHINE)
ERROR: Nothing RPROVIDES 'com.webos.service.ai' (but meta-webos/recipes-webos/com.webos.service.ai/com.webos.service.ai.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'com.webos.service.ai'
NOTE: Runtime target 'com.webos.service.ai' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.service.ai']
ERROR: Nothing RPROVIDES 'com.webos.service.ai-dev' (but meta-webos/recipes-webos/com.webos.service.ai/com.webos.service.ai.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'com.webos.service.ai-dev'
NOTE: Runtime target 'com.webos.service.ai-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.service.ai-dev']

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-101120] CCC: Blacklist failing recipes

Change-Id: I4f04261b43402e9e3081b30269cf01a08fa93fa2