com.webos.service.pdm=r7 (fix luna-service2 usage)
:Release Notes:
Since luna-service2 submission 143 from September 2012 ls2 headers
should be included from luna-service2 directory.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/556299

FAILED: CMakeFiles/physical-device-manager.dir/src/devices/sound/SoundDevice.cpp.o
TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++  -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/git/inc -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/git/inc/private -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/git/inc/public -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/recipe-sysroot/usr/include/libusb-1.0 -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6=/usr/src/debug/com.webos.service.pdm/1.0.1-79-r6                      -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6=/usr/src/debug/com.webos.service.pdm/1.0.1-79-r6                      -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/recipe-sysroot-native=  -fvisibility-inlines-hidden  -std=c++14 -Wall -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/recipe-sysroot/usr/lib/glib-2.0/include -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/recipe-sysroot/usr/lib/glib-2.0/include -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/recipe-sysroot/usr/lib/glib-2.0/include -include TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/build/Configured/webospaths.h -DNDEBUG -MD -MT CMakeFiles/physical-device-manager.dir/src/devices/sound/SoundDevice.cpp.o -MF CMakeFiles/physical-device-manager.dir/src/devices/sound/SoundDevice.cpp.o.d -o CMakeFiles/physical-device-manager.dir/src/devices/sound/SoundDevice.cpp.o -c TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/git/src/devices/sound/SoundDevice.cpp
In file included from TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/git/inc/public/Plugin-Api.h:22,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/git/inc/private/PluginAdapter.h:20,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/git/inc/private/Device.h:25,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/git/inc/private/SoundDevice.h:21,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/git/src/devices/sound/SoundDevice.cpp:17:
TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.pdm/1.0.1-79-r6/git/inc/public/pdm-plugin/PluginBase.h:21:10: fatal error: lunaservice.h: No such file or directory
   21 | #include <lunaservice.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-10642] Remove the temporary work around from 2012 from luna-service2 recipe
[WRP-11674] com.webos.service.pdm: Fix luna-service2 usage
[WRP-11864] CCC: Various build fixes and .patch files cleanup
[WRP-310] Apply .patch files for hot-fix to corresponding repositories
[WRP-11630] Add Upstream-Status to existing .patch files in meta-lg-webos

Cherry-picked-from-commit: 86bc6485b74a7ef7d3ebf2ee410650bd9d0ed29e
Cherry-picked-from-branch: