gettext: fix QA about runtime dependencies on locale-base-*
* fixes:
  ERROR: gettext-0.20.1-r0 do_package_qa: QA Issue: gettext-ptest rdepends
  on locale-base-de-de, but it isn't a build dependency? [build-deps]
  ERROR: gettext-0.20.1-r0 do_package_qa: QA Issue: gettext-ptest rdepends
  on locale-base-fr-fr, but it isn't a build dependency? [build-deps]

[PLAT-115145] CCC: Upgrade to Yocto 3.1 Dunfell

Change-Id: I5ca14f2cf9e3a4d55a564b60b0138a029c580bc7