edgeai-vision: depend on msgpack-cpp instead of msgpack-c
:Release Notes:
It's separate recipes since upgrade to version 4:
https://git.openembedded.org/meta-openembedded/commit/?id=71ab0ca5d65ded4cd812cb99addb6a52f6d5b6b2

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/415471

FAILED: framework/CMakeFiles/edgeai-vision.dir/base/WSServer.cpp.o
TOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/recipe-sysroot-native/usr/bin/arm-oemllib32-linux-gnueabi/arm-oemllib32-linux-gnueabi-g++ -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_IOSTREAMS_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DEDGEAI_VISION_HOME=\"/usr/share/aif\" -DENABLE_DEBUG -DLOG_APPLICATION=\"AIF\" -DLOG_CONTEXT=\"FACE\" -DUSE_ARMNN -DUSE_BASE64IMAGE -DUSE_GPU_DELEGATE -DUSE_XNNPACK -Dedgeai_vision_EXPORTS -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/lib32-recipe-sysroot/usr/include/opencv4 -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/lib32-recipe-sysroot/usr/include/armnn -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/include -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/log -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/tools -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/base -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/face -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/pose -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/movenet -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/semantic -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/bodypix -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/selfie -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/poseLandmark -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/handLandmark -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/palm -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/delegate -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/sample -ITOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/facade -mthumb -mfpu=neon -mfloat-abi=softfp -mcpu=cortex-a9 -mtune=cortex-a9 -funwind-tables -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/lib32-recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1=/usr/src/debug/lib32-edgeai-vision/1.0.0-7-r1                      -fdebug-prefix-map=TOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1=/usr/src/debug/lib32-edgeai-vision/1.0.0-7-r1                      -fdebug-prefix-map=TOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/lib32-recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/recipe-sysroot-native=  -fvisibility-inlines-hidden  -fPIC   -std=c++14 -MD -MT framework/CMakeFiles/edgeai-vision.dir/base/WSServer.cpp.o -MF framework/CMakeFiles/edgeai-vision.dir/base/WSServer.cpp.o.d -o framework/CMakeFiles/edgeai-vision.dir/base/WSServer.cpp.o -c TOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/base/WSServer.cpp
In file included from TOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/include/aif/base/WSServer.h:8,
                 from TOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/framework/base/WSServer.cpp:1:
TOPDIR/BUILD/work/MACHINE-oemllib32-linux-gnueabi/lib32-edgeai-vision/1.0.0-7-r1/git/include/aif/base/WSServerSession.h:11:10: fatal error: msgpack.hpp: No such file or directory
   11 | #include <msgpack.hpp>
      |          ^~~~~~~~~~~~~
compilation terminated.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12998] CCC: Upgrade to Yocto 3.4 Honister
[PLAT-141293] Create GPVB with Yocto 3.4 Honister

Change-Id: I6fae15241ed1ca0b5494a1aac06fa62944ab7c82