audiod=r33 (add missing functional include)
:Release Notes:
Fix build.

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/527952
audiod/1.0.0-57-r32/git/include/events.h:183:14: error: 'function' in namespace 'std' does not name a template type
audiod/1.0.0-57-r32/git/src/modules/deviceManager/deviceManager.cpp:1128:71: error: 'struct events::EVENT_REQUEST_INTERNAL_DEVICES_INFO_T' has no member named 'func'
audiod/1.0.0-57-r32/git/src/modules/masterVolumeManager/OSEMasterVolumeManager.cpp:2425:35: error: 'struct events::EVENT_REQUEST_INTERNAL_DEVICES_INFO_T' has no member named 'func'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-7956] CCC: Various build fixes

Change-Id: I939f7cf8eb005ac23f3f9c40533488fde84c5136
Reviewed-on: http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/344273
Reviewed-by: Multi Layer Checker <multi_layer@lge.com>
Reviewed-by: Vijaya Sundaram <vijaya.sundaram@lge.com>
Reviewed-by: milan shah <milan.shah@lge.com>
Static-Analysis: Vijaya Sundaram <vijaya.sundaram@lge.com>
Tested-by: milan shah <milan.shah@lge.com>