webos-sota.inc: disable for all qemu MACHINEs
:Release Notes:
not only qemux86, but also qemux86_64 and qemuarm.

:Detailed Notes:
Fixes qemuarm builds which started to fail with:
  ERROR: Nothing PROVIDES 'virtual/bootloader'
  u-boot PROVIDES virtual/bootloader but was skipped: Either UBOOT_MACHINE
  or UBOOT_CONFIG must be set in the qemuarm machine configuration.
because of the added virtual/bootloader dependency from do_image_sota.

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-85669] CCC: Upgrade meta-updater to latest revision and fix it

Change-Id: Iad3daa4f9a5cc1e0fdbd4b10cde1ca18d229d092