u-boot=v2019.01 (backport from Yocto 2.7 Warrior)
:Release Notes:
Backport the recipes from oe-core as well as the patches with
raspberrypi4 support from meta-raspberrypi in meta-webos-backports-2.7

:Detailed Notes:
This also fixes:
ERROR: u-boot-1_2019.01-r0 do_patch: Fuzz detected:

Applying patch 0004-rpi-Add-rpi_model-entry-for-RaspberryPi-4.patch
patching file board/raspberrypi/rpi/rpi.c
Hunk #1 succeeded at 143 with fuzz 2 (offset -5 lines).

The context lines in the patches can be updated with devtool:

    devtool modify u-boot
    devtool finish --force-patch-refresh u-boot <layer_path>

Don't forget to review changes done by devtool!

ERROR: u-boot-1_2019.01-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

Also fix qemuarm builds which were failing with:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'virtual/bootloader'
u-boot PROVIDES virtual/bootloader but was skipped: Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the qemuarm machine configuration.
u-boot PROVIDES virtual/bootloader but was skipped: Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the qemuarm machine configuration.
ERROR: Nothing RPROVIDES 'webos-image-devel'
No eligible RPROVIDERs exist for 'webos-image-devel'
NOTE: Runtime target 'webos-image-devel' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-devel']
ERROR: Nothing RPROVIDES 'u-boot-fw-utils' (but /jenkins/mjansa/build-webos-thud/meta-lg-webos/meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb RDEPENDS on or otherwise requires it)
u-boot-fw-utils was skipped: Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the qemuarm machine configuration.
u-boot-fw-utils was skipped: Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the qemuarm machine configuration.
NOTE: Runtime target 'u-boot-fw-utils' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['u-boot-fw-utils']
NOTE: Runtime target 'packagegroup-webos-extended' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-webos-extended', 'u-boot-fw-utils']

because meta-webos-raspberrypi/recipes-core/packagegroups/packagegroup-webos-extended.bbappend
was adding u-boot-fw-utils dependency to all MACHINEs (missing _rpi override).

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-76088] [FOTA] Prepare meta layer for libostree
[PLAT-85195] [FOTA] Add u-boot rpi4 support for ostree
[PLAT-81123] CCC: webos-sota.inc: enable FOTA by using ostree
[PLAT-85555] CCC: Various build fixes

Change-Id: I14071352ea5c4ca0c34599bb1c4c4b80c1a6d32b