com.webos.app.swupdater=r1 (drop webos_arch_indep inherit)
:Release Notes:
It depends on MACHINE_ARCH do_convert_webos_preferred_gfx_image_format
function from webos-app. And has runtime dependency on MACHINE_ARCH webruntime.

:Detailed Notes:
Fixes:
 === Comparing signatures for task do_configure.sigdata between qemux86 and qemux86copy ===
ERROR: com.webos.app.swupdater different signature for task do_configure.sigdata between qemux86 and qemux86copy
NOTE: Starting bitbake server...
NOTE: Started PRServer with DBfile: <https://jenkins-scm.lgsvl.net/job/jansa/job/webos-jansa-thud-test-signatures/ws/build/cache/prserv.sqlite3,> IP: 127.0.0.1, PORT: 37145, PID: 25467
Hash for dependent task com.webos.service.swupdater/com.webos.app.swupdater.bb.do_prepare_recipe_sysroot changed from 8856506545474d07c9f7f02d41375149 to c4e769d35fcc0a5e9d88f0c573cfe187
Unable to find matching sigdata for <https://jenkins-scm.lgsvl.net/job/jansa/job/webos-jansa-thud-test-signatures/ws/build/meta-lg-webos/meta-webos/recipes-webos/com.webos.service.swupdater/com.webos.app.swupdater.bb.do_prepare_recipe_sysroot> with hash c4e769d35fcc0a5e9d88f0c573cfe187

ERROR: 1 errors found in <https://jenkins-scm.lgsvl.net/job/jansa/job/webos-jansa-thud-test-signatures/ws/build/BUILD/sstate-diff/1578757624/signatures.qemux86copy.do_configure.sigdata.log>

 === Comparing signatures for task do_populate_sysroot.sigdata between qemux86 and qemux86copy ===
ERROR: com.webos.app.swupdater different signature for task do_populate_sysroot.sigdata between qemux86 and qemux86copy
NOTE: Starting bitbake server...
NOTE: Started PRServer with DBfile: <https://jenkins-scm.lgsvl.net/job/jansa/job/webos-jansa-thud-test-signatures/ws/build/cache/prserv.sqlite3,> IP: 127.0.0.1, PORT: 34977, PID: 25496
Hash for dependent task com.webos.service.swupdater/com.webos.app.swupdater.bb.do_convert_webos_preferred_gfx_image_format changed from 3ff3ee6f666b150b99c45a42f7950678 to 08cf4a1bc7307be099293159b217c255
Unable to find matching sigdata for <https://jenkins-scm.lgsvl.net/job/jansa/job/webos-jansa-thud-test-signatures/ws/build/meta-lg-webos/meta-webos/recipes-webos/com.webos.service.swupdater/com.webos.app.swupdater.bb.do_convert_webos_preferred_gfx_image_format> with hash 08cf4a1bc7307be099293159b217c255

ERROR: 1 errors found in <https://jenkins-scm.lgsvl.net/job/jansa/job/webos-jansa-thud-test-signatures/ws/build/BUILD/sstate-diff/1578757624/signatures.qemux86copy.do_populate_sysroot.sigdata.log>

 === Comparing signatures for task do_package_write_ipk.sigdata between qemux86 and qemux86copy ===
ERROR: com.webos.app.swupdater different signature for task do_package_write_ipk.sigdata between qemux86 and qemux86copy
NOTE: Starting bitbake server...
NOTE: Started PRServer with DBfile: <https://jenkins-scm.lgsvl.net/job/jansa/job/webos-jansa-thud-test-signatures/ws/build/cache/prserv.sqlite3,> IP: 127.0.0.1, PORT: 43253, PID: 25528
Hash for dependent task com.webos.service.swupdater/com.webos.app.swupdater.bb.do_package changed from ebfde4ded6913819a17fc7aad9f39489 to 2f472c5b66828e8f24510ed364b9852e
Unable to find matching sigdata for <https://jenkins-scm.lgsvl.net/job/jansa/job/webos-jansa-thud-test-signatures/ws/build/meta-lg-webos/meta-webos/recipes-webos/com.webos.service.swupdater/com.webos.app.swupdater.bb.do_package> with hash 2f472c5b66828e8f24510ed364b9852e

ERROR: 1 errors found in <https://jenkins-scm.lgsvl.net/job/jansa/job/webos-jansa-thud-test-signatures/ws/build/BUILD/sstate-diff/1578757624/signatures.qemux86copy.do_package_write_ipk.sigdata.log>

 === Comparing signatures for task do_configure.sigdata between qemux86 and qemuarm ===
ERROR: com.webos.app.swupdater different signature for task do_configure.sigdata between qemux86 and qemuarm
NOTE: Starting bitbake server...
NOTE: Started PRServer with DBfile: /jenkins/home/anaconda/build-webos-warrior/build/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 43925, PID: 34734
Hash for dependent task com.webos.service.swupdater/com.webos.app.swupdater.bb.do_prepare_recipe_sysroot changed from fd7a49fc218c13e5463cf164425b828146f762df0ae7b54c84c0e9de43d6ddf4 to 91cf8fba28d6b34da064d45cae8cc00b60e230231cd89e9b155fb5bcdaf0a6a1
  Hash for dependent task chromium/webruntime_68.bb.do_populate_sysroot changed from c71cf1f6cc09d15331aab494e1fc9dd8e60e58fc6b4ef34d9fb59d48d027a876 to 7c59c82916350237375781eb71f50dabbc39f91ade4401665407dbfe236fdfe3
    Hash for dependent task binutils/binutils-cross_2.32.bb.do_populate_sysroot changed from aeb421e3b2b335543499faa2dbe53b7910d8be646424eebc455e8c1a4cbb4c61 to 76f6d47db9b381e608b1900c782242e4f93433e1b782c7f189eab7256e8f83b5
    Unable to find matching sigdata for /jenkins/home/anaconda/build-webos-warrior/build/oe-core/meta/recipes-devtools/binutils/binutils-cross_2.32.bb.do_populate_sysroot with hashes aeb421e3b2b335543499faa2dbe53b7910d8be646424eebc455e8c1a4cbb4c61 or 76f6d47db9b381e608b1900c782242e4f93433e1b782c7f189eab7256e8f83b5

ERROR: 1 errors found in /jenkins/home/anaconda/build-webos-warrior/build/BUILD/sstate-diff/1578755795/signatures.qemuarm.do_configure.sigdata.log

 === Comparing signatures for task do_populate_sysroot.sigdata between qemux86 and qemuarm ===
ERROR: com.webos.app.swupdater different signature for task do_populate_sysroot.sigdata between qemux86 and qemuarm
NOTE: Starting bitbake server...
NOTE: Started PRServer with DBfile: /jenkins/home/anaconda/build-webos-warrior/build/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 39849, PID: 34774
Hash for dependent task com.webos.service.swupdater/com.webos.app.swupdater.bb.do_install changed from 550e856cbdac945fb12b1413bea517730ef4035905c083d8c92e84257fabb403 to adcbdd0e6171898e8d2461b6729c7af4a92b3350268d203956c62a84b43f084f
  Hash for dependent task com.webos.service.swupdater/com.webos.app.swupdater.bb.do_locate_enactjs_appinfo changed from 3a9959594797e90d595cb57fe02c25868af9c5b4d847a7ff8de459f7c85fb646 to 7ba7d0707b2f9689bc17c884c0f38f0e0ddb62619e3e0ede88d7335c6e3c88fc
    Hash for dependent task com.webos.service.swupdater/com.webos.app.swupdater.bb.do_configure changed from d40279b6fe49e12937cc5cefab1362ed5f1baa31fc55c82be931c6ff480860b1 to 6835b291ee386b55365a05cd7eaf38b76f2ab51f8ae7198b65c517b8c0c755fb
      Hash for dependent task com.webos.service.swupdater/com.webos.app.swupdater.bb.do_prepare_recipe_sysroot changed from fd7a49fc218c13e5463cf164425b828146f762df0ae7b54c84c0e9de43d6ddf4 to 91cf8fba28d6b34da064d45cae8cc00b60e230231cd89e9b155fb5bcdaf0a6a1
        Hash for dependent task chromium/webruntime_68.bb.do_populate_sysroot changed from c71cf1f6cc09d15331aab494e1fc9dd8e60e58fc6b4ef34d9fb59d48d027a876 to 7c59c82916350237375781eb71f50dabbc39f91ade4401665407dbfe236fdfe3
          Hash for dependent task chromium/webruntime_68.bb.do_install changed from 48a8bb690a054e29851f72c4a5ca01fdbc7e4fbc2b320471dce3ffa73f7fb8b9 to 7a6d2a4f061dcba5d7e096f46802c464692a37e25a07ed963a11e8fb2d9e710d
            Hash for dependent task chromium/webruntime_68.bb.do_compile changed from 845855bfa7699fc7f1965fd9ec63098fc07578f90d26a48c394659b03e7a1400 to 1b0b4bf1a4821f02882b3422b4921f4d78cbf4bb22c23b888a845feb76f57961
              Hash for dependent task chromium/webruntime_68.bb.do_configure changed from 8a41c06e58e5ad6439a3f1431bb60ed249f63a80cbfb92e20a3e090ebaf9a447 to 79f940a95416b8dea43c7068e9f8d61dd56fce6c717d925f4522d3693b520283
                Hash for dependent task chromium/webruntime_68.bb.do_patch changed from b4a95c0f212c70886a1168a133b1e5fbd6be7c3bd0dc8e1589ac7a92f366780e to 1a6cd812ae42f7042dcdfc773f026b94cd35f1afae702fc7c09e04cfb34906a8
                  Hash for dependent task chromium/webruntime_68.bb.do_unpack changed from ac1853c293fb59b37acfb83a8d553ec27ca57690e8713943394136b7f9bb6b11 to 6e6bce783b93542f73eb9f2102e393616d0499ef0802fc2e58e658a1fb9e1113
                    Hash for dependent task chromium/webruntime_68.bb.do_fetch changed from c8c14b2f324bf59fbcfb6f891f9965590d44099601ef147314f387ad12dbe19c to 1d855a6e67c23c3e7d3748bc6ef2fcf418eb35384ac3138cdb383a40c080a52f
                      Task dependencies changed from:
                      ['ABIEXTENSION', 'DEFAULTTUNE', 'EXTENDPE', 'INC_PR', 'LIBCEXTENSION', 'MACHINE', 'MACHINE_ARCH', 'MULTIMACH_TARGET_SYS', 'P', 'PACKAGE_ARCH', 'PE', 'PN', 'PR', 'PV', 'QA_LOGFILE', 'SRCREV', 'SRCREV_main', 'SRCREV_v8', 'SRC_URI', 'STAMP', 'TARGET_OS', 'TARGET_VENDOR', 'TUNE_PKGARCH', 'TUNE_PKGARCH_tune-i586', 'WEBOSOSE_GIT_PARAM_PROTOCOL', 'WEBOSOSE_GIT_PROTOCOL', 'WEBOSOSE_GIT_REPO', 'WEBOSOSE_GIT_REPO_COMPLETE', 'WEBOS_COMPONENT_VERSION', 'WEBOS_GIT_BRANCH', 'WEBOS_GIT_BRANCH_V8', 'WEBOS_GIT_PARAM_BRANCH', 'WEBOS_GIT_PARAM_BRANCH_V8', 'WEBOS_GIT_REPO_TAG', 'WEBOS_GIT_TAG', 'WEBOS_REPO_NAME', 'WEBOS_REPO_NAME_V8', 'WEBOS_SRCREV', 'WEBOS_SUBMISSION', 'WEBOS_VERSION', 'base_do_fetch', 'clean_recipe_sysroot', 'package_qa_handle_error', 'package_qa_write_error', 'webos_enhsub_get_srcrev', 'webos_enhsub_srcrev_sanity_check', 'webos_submissions_version_sanity_check', 'webos_version_get_branch', 'webos_version_get_component_version', 'webos_version_get_pv', 'webos_version_get_srcrev', 'webos_version_get_submission']
                      to:
                      ['ABIEXTENSION', 'ARMPKGARCH', 'ARMPKGARCH_tune-armv7vethf-neon', 'ARMPKGSFX_DSP', 'ARMPKGSFX_EABI', 'ARMPKGSFX_ENDIAN', 'ARMPKGSFX_FPU', 'ARMPKGSFX_THUMB', 'ARM_INSTRUCTION_SET', 'ARM_M_OPT', 'ARM_THUMB_OPT', 'ARM_THUMB_SUFFIX', 'DEFAULTTUNE', 'EXTENDPE', 'INC_PR', 'LIBCEXTENSION', 'MACHINE', 'MACHINE_ARCH', 'MULTIMACH_TARGET_SYS', 'P', 'PACKAGE_ARCH', 'PE', 'PN', 'PR', 'PREFERRED_ARM_INSTRUCTION_SET', 'PV', 'QA_LOGFILE', 'SRCREV', 'SRCREV_main', 'SRCREV_v8', 'SRC_URI', 'STAMP', 'TARGET_OS', 'TARGET_VENDOR', 'TUNE_CCARGS_MFLOAT', 'TUNE_CCARGS_MFPU', 'TUNE_FEATURES', 'TUNE_FEATURES_tune-armv7ve', 'TUNE_FEATURES_tune-armv7vet', 'TUNE_FEATURES_tune-armv7vet-neon', 'TUNE_FEATURES_tune-armv7vethf-neon', 'TUNE_PKGARCH', 'WEBOSOSE_GIT_PARAM_PROTOCOL', 'WEBOSOSE_GIT_PROTOCOL', 'WEBOSOSE_GIT_REPO', 'WEBOSOSE_GIT_REPO_COMPLETE', 'WEBOS_COMPONENT_VERSION', 'WEBOS_GIT_BRANCH', 'WEBOS_GIT_BRANCH_V8', 'WEBOS_GIT_PARAM_BRANCH', 'WEBOS_GIT_PARAM_BRANCH_V8', 'WEBOS_GIT_REPO_TAG', 'WEBOS_GIT_TAG', 'WEBOS_REPO_NAME', 'WEBOS_REPO_NAME_V8', 'WEBOS_SRCREV', 'WEBOS_SUBMISSION', 'WEBOS_VERSION', 'base_do_fetch', 'clean_recipe_sysroot', 'package_qa_handle_error', 'package_qa_write_error', 'webos_enhsub_get_srcrev', 'webos_enhsub_srcrev_sanity_check', 'webos_submissions_version_sanity_check', 'webos_version_get_branch', 'webos_version_get_component_version', 'webos_version_get_pv', 'webos_version_get_srcrev', 'webos_version_get_submission']
                      basehash changed from 9f59bfeecc3f970be4122b881a972e65a5efbe83533102d64ef8ae75d76b9de6 to f244ca62a1f6b4252c0b87d75abfc9e4b488184aab03ac45ff89ffd1f97e5f0a
                      List of dependencies for variable TUNE_PKGARCH changed from '{'DEFAULTTUNE', 'TUNE_PKGARCH_tune-i586'}' to '{'ARMPKGSFX_THUMB', 'ARMPKGARCH', 'ARMPKGSFX_FPU', 'ARMPKGSFX_DSP', 'ARMPKGSFX_ENDIAN', 'ARMPKGSFX_EABI'}'
                      changed items: {'DEFAULTTUNE', 'ARMPKGSFX_THUMB', 'ARMPKGARCH', 'ARMPKGSFX_ENDIAN', 'ARMPKGSFX_FPU', 'ARMPKGSFX_EABI', 'TUNE_PKGARCH_tune-i586', 'ARMPKGSFX_DSP'}
                      Dependency on variable TUNE_FEATURES_tune-armv7vet was added
                      Dependency on variable TUNE_CCARGS_MFPU was added
                      Dependency on variable ARMPKGSFX_THUMB was added
                      Dependency on variable ARM_M_OPT was added
                      Dependency on variable ARMPKGARCH was added
                      Dependency on variable TUNE_FEATURES_tune-armv7vethf-neon was added
                      Dependency on variable ARMPKGSFX_FPU was added
                      Dependency on variable ARM_THUMB_OPT was added
                      Dependency on variable ARMPKGARCH_tune-armv7vethf-neon was added
                      Dependency on variable TUNE_FEATURES was added
                      Dependency on variable TUNE_FEATURES_tune-armv7vet-neon was added
                      Dependency on variable ARMPKGSFX_DSP was added
                      Dependency on variable ARMPKGSFX_ENDIAN was added
                      Dependency on variable PREFERRED_ARM_INSTRUCTION_SET was added
                      Dependency on variable TUNE_FEATURES_tune-armv7ve was added
                      Dependency on variable TUNE_CCARGS_MFLOAT was added
                      Dependency on variable ARM_THUMB_SUFFIX was added
                      Dependency on variable ARMPKGSFX_EABI was added
                      Dependency on variable ARM_INSTRUCTION_SET was added
                      Dependency on Variable TUNE_PKGARCH_tune-i586 was removed
                      Variable TUNE_PKGARCH value changed from '${TUNE_PKGARCH_tune-${DEFAULTTUNE}}' to '${ARMPKGARCH}${ARMPKGSFX_THUMB}${ARMPKGSFX_DSP}${ARMPKGSFX_EABI}${ARMPKGSFX_ENDIAN}${ARMPKGSFX_FPU}'
                      Variable DEFAULTTUNE value changed from 'i586' to 'armv7vethf-neon'
                      Variable MACHINE value changed from 'qemux86' to 'qemuarm'
                      Variable ABIEXTENSION value changed:
                      @@ -1,2 +1 @@
                      -${@bb.utils.contains('TUNE_FEATURES', 'mx32', 'x32', '' ,d)}
                      -TUNE_FEATURES{mx32} = Unset
                      +eabi

ERROR: 1 errors found in /jenkins/home/anaconda/build-webos-warrior/build/BUILD/sstate-diff/1578755795/signatures.qemuarm.do_populate_sysroot.sigdata.log

 === Comparing signatures for task do_package_write_ipk.sigdata between qemux86 and qemuarm ===
ERROR: com.webos.app.swupdater different signature for task do_package_write_ipk.sigdata between qemux86 and qemuarm
NOTE: Starting bitbake server...
NOTE: Started PRServer with DBfile: /jenkins/home/anaconda/build-webos-warrior/build/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 42879, PID: 34811
Hash for dependent task com.webos.service.swupdater/com.webos.app.swupdater.bb.do_packagedata changed from 19c4abff50481d0a6b2fbbe3d94018ed3485064a21e86a0e2b80debaf61ef34e to 5bda666b740a76dc1b7b067a2ea01af2deb463d652cb290da5e35ab5480dd100
  Hash for dependent task com.webos.service.swupdater/com.webos.app.swupdater.bb.do_package changed from e2a5eaf4633aad19298e5c616394a4cd580e03b79f3fba5382cb09401f7e16f3 to 388154f569e6135135116f5ae42b9d84970d5a4cd129e6990a7814c7b428a417
    Hash for dependent task chromium/webruntime_68.bb.do_packagedata changed from 152021f4aa5e8aabfb14a9028663ad28ffb2e2c93ea06c7e0dd14d43f3c5ed0a to 97fc6f81ae4d51240bfda88f70bd3cb4c1f801981dc11c07b0796f89c6c9803a
      Hash for dependent task chromium/webruntime_68.bb.do_package changed from bb7ad5d34a7369c9f1cc6cf6e4c38359cce94f176c9d98d2f4832524b263f7c4 to 8a1239507ba6c30d381b56b6c3903841ddb1cc826781e045ecc3b7d7ca7a3597
        Hash for dependent task xorg-lib/pixman_0.38.0.bb.do_packagedata changed from 868c42eacff1db34fd3cdfeed43c6a61500272267508fbf8802dcd75f2ed1a87 to b24c050d9f9fbd04285893f57db28b61a485e4df61f4d383d75ca308d7f0b81b
          Hash for dependent task xorg-lib/pixman_0.38.0.bb.do_package changed from 4545f3988e2fe1488bf9913d2de35b528042f120d7b192095d04e198f6dc4842 to f940281b677a83071af06c526c027af593bd2a968720fa609a352b35ae7d039e
            Hash for dependent task xorg-lib/pixman_0.38.0.bb.do_install changed from 9c0cb1a3243e469ae83a6dfa224c1e66b164da32c4c31df0767b2a6d2efacd63 to e362cb9848871c0404c57951c6c0dad6f656ef66748b96d9f6f987c41592fd2d
            Unable to find matching sigdata for /jenkins/home/anaconda/build-webos-warrior/build/oe-core/meta/recipes-graphics/xorg-lib/pixman_0.38.0.bb.do_install with hashes 9c0cb1a3243e469ae83a6dfa224c1e66b164da32c4c31df0767b2a6d2efacd63 or e362cb9848871c0404c57951c6c0dad6f656ef66748b96d9f6f987c41592fd2d

ERROR: 1 errors found in /jenkins/home/anaconda/build-webos-warrior/build/BUILD/sstate-diff/1578755795/signatures.qemuarm.do_package_write_ipk.sigdata.log
ERROR: 6 issues were found in these recipes: com.webos.app.swupdater

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-98534] CCC: Various build fixes

Change-Id: I71057f87da0bfc98a21bbae797e86b8e7bad52ec