libgoogleassistant=r7 com.webos.service.ai=r7 (add COMPATIBLE_MACHINE restriction)
:Release Notes:
From meta-webos/recipes-upstreamable/snowboy/snowboy_%.bbappend

:Detailed Notes:
Fixes:
ERROR: Nothing PROVIDES 'snowboy' (but /jenkins/home/anaconda/build-webos-ose-kirkstone/build/meta-webosose/meta-webos/recipes-webos/libgoogleassistant/libgoogleassistant.bb DEPENDS on or otherwise requires it)
snowboy was skipped: incompatible with machine qemux86 (not in COMPATIBLE_MACHINE)
ERROR: Nothing RPROVIDES 'libgoogleassistant-dev' (but /jenkins/home/anaconda/build-webos-ose-kirkstone/build/meta-webosose/meta-webos/recipes-webos/libgoogleassistant/libgoogleassistant.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'libgoogleassistant-dev'
NOTE: Runtime target 'libgoogleassistant-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libgoogleassistant-dev']
ERROR: Nothing RPROVIDES 'snowboy-models' (but /jenkins/home/anaconda/build-webos-ose-kirkstone/build/meta-webosose/meta-webos/recipes-webos/libgoogleassistant/libgoogleassistant.bb RDEPENDS on or otherwise requires it)
snowboy RPROVIDES snowboy-models but was skipped: incompatible with machine qemux86 (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'snowboy-models' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['snowboy-models']
ERROR: Nothing RPROVIDES 'libgoogleassistant' (but /jenkins/home/anaconda/build-webos-ose-kirkstone/build/meta-webosose/meta-webos/recipes-webos/libgoogleassistant/libgoogleassistant.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'libgoogleassistant'
NOTE: Runtime target 'libgoogleassistant' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libgoogleassistant']
ERROR: Nothing RPROVIDES 'com.webos.service.ai-dev' (but /jenkins/home/anaconda/build-webos-ose-kirkstone/build/meta-webosose/meta-webos/recipes-webos/com.webos.service.ai/com.webos.service.ai.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'com.webos.service.ai-dev'
NOTE: Runtime target 'com.webos.service.ai-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.service.ai-dev']
ERROR: Nothing RPROVIDES 'com.webos.service.ai' (but /jenkins/home/anaconda/build-webos-ose-kirkstone/build/meta-webosose/meta-webos/recipes-webos/com.webos.service.ai/com.webos.service.ai.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'com.webos.service.ai'
NOTE: Runtime target 'com.webos.service.ai' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.service.ai']

:Testing Performed:
Only build tested.

:QA Notes:
None.

:Issues Addressed:
[WRN-10062] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: I36c30bd5c22bfeee84e3363bd36c3f554e1f5156