opkg: update patches to apply on 0.4.4 version
:Release Notes:

:Detailed Notes:
ERROR: opkg-1_0.4.4-r0 do_patch: Fuzz detected:

Applying patch 0005-Add-symlink-path-validity.patch
patching file libopkg/opkg_archive.c
Hunk #1 succeeded at 883 (offset -23 lines).
patching file libopkg/opkg_conf.c
patching file libopkg/opkg_conf.h
Hunk #1 succeeded at 107 (offset 2 lines).
patching file src/opkg.c
Hunk #1 succeeded at 60 (offset 3 lines).
Hunk #2 succeeded at 108 with fuzz 2 (offset 2 lines).
Hunk #3 succeeded at 258 (offset 3 lines).

The context lines in the patches can be updated with devtool:

    devtool modify opkg
    devtool finish --force-patch-refresh opkg <layer_path>

Don't forget to review changes done by devtool!

ERROR: opkg-1_0.4.4-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-12997] CCC: Upgrade to Yocto 3.3 Hardknott
[PLAT-124341] Create GPVB with Yocto 3.3 Hardknott

Change-Id: I74c5e0a615618b9dac08fecacecab51a2a15fca0