cpupower=webos1 (fix build-deps QA issue with bash)
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: cpupower-1.0-r0 do_package_qa: QA Issue: cpupower rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-139325] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: If79ec07fb8654e80e86cc993b0a442e7e48907d2