webos-open-test-apps.inc=r4.* (inherit webos_arch_indep before webos_cmake)
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: bareapp different signature for task do_package_write_ipk.sigdata between qemux86 and qemuarm
Hash for dependent task test-apps/bareapp.bb.do_package changed from 9fc0756b4aa601a718f381d37b16c06c55b1a567c7a5ffa9eb0fa77e5e8716b7 to 449f2dca3aa8666cab4e554f3d9808c018e3f1172ef44c563b006d73ae8808eb

ERROR: com.webos.app.test.enact different signature for task do_package_write_ipk.sigdata between qemux86 and qemuarm
Hash for dependent task test-apps/com.webos.app.test.enact.bb.do_package changed from 011845ce479c59c72eb562dbcb23e2ebde0f1e03657b3c3cf0fc1540d0a53860 to 7d497fc439c1497d1dbc1fc0c5e8e19cf0b92141fe0732f3f40f333ca787a322

ERROR: com.webos.app.test.webosose different signature for task do_package_write_ipk.sigdata between qemux86 and qemuarm
Hash for dependent task test-apps/com.webos.app.test.webosose.bb.do_packagedata changed from 020710513b7a2ff5f9f508a572bacd1c3b1d46166b93a8058a9f79f7ff9c616c to 6807affb14ba9f063ee406ecaf2af460edd2e9a004e8be3a29a86b30e736f17d

ERROR: com.webos.app.test.youtube different signature for task do_package_write_ipk.sigdata between qemux86 and qemuarm
Hash for dependent task test-apps/com.webos.app.test.youtube.bb.do_packagedata changed from 3a04838f439d433ed253f4d85473bf7c1d3bea3ee287b6b07684acfab5a1e29c to 330e15093e1895f5619a4b6bab438a80c133a22a33383f5f92274aed332eddcf

bitbake-diffsigs BUILD/sstate-diff/1557597589/qemu???/*/com.webos.app.test.enact/*do_generate_toolchain_file.sigdata*
basehash changed from d1ce51d389efd0c701560ec2c3385f1f7a0053aeae1bdf96e1ee4db9f5329a3d to 72746fc03534f07a47263deda117c9e8173210e1f88359867e96b116aff5fd26
Variable OECMAKE_C_COMPILER value changed from 'arm-webos-linux-gnueabi-gcc' to 'i586-webos-linux-gcc'
Variable OECMAKE_CXX_COMPILER value changed from 'arm-webos-linux-gnueabi-g++' to 'i586-webos-linux-g++'

:Testing Performed:
oe-core/scripts/sstate-diff-machines.sh --tmpdir=BUILD --machines="qemux86 qemux86copy qemuarm" --targets="bareapp com.webos.app.test.enact com.webos.app.test.webosose com.webos.app.test.youtube" --analyze

:QA Notes:

:Issues Addressed:
[PLAT-78082] Upgrade to Yocto 2.6 Thud
[PLAT-78507] [OSE] CCC: Upgrade to Yocto 2.6 Thud

Change-Id: I64b9cfc69eec727aa97cb8c4575c55d10bb2415c