webos: pmklogd=r7 (ignore implicit-function-declaration issues)
:Release Notes:
These are fatal by default with gcc-14.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/821713
pmklogd/2.0.0-2/build/Configured/src/PmKLogDaemon.c:274:30: error: implicit declaration of function 'g_strstr_len' [-Wimplicit-function-declaration]
pmklogd/2.0.0-2/build/Configured/src/PmKLogDaemon.c:298:28: error: implicit declaration of function 'g_str_has_prefix' [-Wimplicit-function-declaration]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-19569] CCC: pmklogd=r7 (ignore implicit-function-declaration issues)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRQ-1041] [SCM SWP] Force component owners to fix security issues
           detected by security-flags.inc and other code errors

Cherry-picked-from-commit: b86a286d63d9e3d2bbc7918fd77e827d371971b1
Cherry-picked-from-branch: