arm-compute-library=r1 (fix various build issues)
:Release Notes:
Fix build with gcc-12.
Fix build with softfp.
Use append with overrides.

:Detailed Notes:
The fix for build with gcc-12 was already applied in:
http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/330062
but it wasn't migrated to this new recipes.

Setting the option for SConstruct is very limited and was
causing build failure for any machine with call-convention
hard as in:
http://gecko.lge.com/Errors/Details/415425

TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/arm-compute-library/21.11-r0/recipe-sysroot/usr/include/gnu/stubs-32.h:7:11: fatal error: gnu/stubs-soft.h: No such file or directory
    7 | # include <gnu/stubs-soft.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.

That's because of this chunk of SConstruct:
     if (env['os'] == 'android' or env['os'] == 'tizen' or env['os'] == 'webos') and not 'hf' in env['arch']:
         env.Append(CXXFLAGS = ['-mfloat-abi=softfp'])
     else:
         env.Append(CXXFLAGS = ['-mfloat-abi=hard'])

It expects to find 'hf' in env['arch'] but for all 32bit arm we
were passing just 'arch=armv7a', add 'hf' suffix where needed to
fix this issue, but it's still very limited for other possible
MACHINEs and their DEFAULTTUNEs.

Also add explicit estate=32 to fix build with qemux86:
http://gecko.lge.com:8000/Errors/Details/415527

i686-webos-linux-g++ -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-z,relro,-z,now -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type --sysroot=TOPDIR/BUILD/work/qemux86-webos-linux/arm-compute-library/21.11-r1/recipe-sysroot -o build/utils/CommonGraphOptions.o -c -Wall -DARCH_ARM -Wextra -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -std=c++14 -Woverloaded-virtual -Wformat-security -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-overlength-strings -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -fopenmp -fPIC -DENABLE_NEON -DARM_COMPUTE_ENABLE_NEON -Wno-ignored-attributes -DENABLE_FP16_KERNELS -DENABLE_FP32_KERNELS -DENABLE_QASYMM8_KERNELS -DENABLE_QASYMM8_SIGNED_KERNELS -DENABLE_QSYMM16_KERNELS -DENABLE_INTEGER_KERNELS -DENABLE_NHWC_KERNELS -DENABLE_NCHW_KERNELS -O3 -fPIC -O2 -m64 -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_OPENMP_SCHEDULER=1 -DARM_COMPUTE_GRAPH_ENABLED -DARM_COMPUTE_OPENCL_ENABLED -DEMBEDDED_KERNELS -Iinclude -I. -I. utils/CommonGraphOptions.cpp
cc1plus: sorry, unimplemented: 64-bit mode not compiled in

Because the SConstruct only sets 32 for 'v7a' in arch:
  # Validate and define state
  if env['estate'] == 'auto':
      if 'v7a' in env['arch']:
          env['estate'] = '32'
      else:
          env['estate'] = '64'
so -m64 ends in command line even when we want to build 32bit qemux86.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-4984] CCC: Various build fixes

Change-Id: I01db5382f405d588b3f515c23e34693ad5ac17e5