webos: com.webos.app.home: include only for not armv[45]
:Release Notes:
Fixes build for qemuarm.

:Detailed Notes:
Fixes:
ERROR: Nothing RPROVIDES 'com.webos.app.home' (but /jenkins/mjansa/build-webos-ose-thud/meta-webosose/meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb RDEPENDS on or otherwise requires it)
com.webos.app.home was skipped: incompatible with machine qemuarm (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'com.webos.app.home' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.app.home']
NOTE: Runtime target 'packagegroup-webos-extended' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-webos-extended', 'com.webos.app.home']
NOTE: Runtime target 'webos-image-devel' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webos-image-devel', 'packagegroup-webos-extended', 'com.webos.app.home']

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-86843] CCC: Various build fixes

Change-Id: Ib1dee60c97a66f046d8f98a91789bf62108f0eef