webos-recipe-blacklist.inc: blacklist libqofonoext, python3-pyqtchart, qt-kiosk-browser
:Release Notes:
Fix issues detected by yocto-check-layer.
libqofonoext depends on already blacklisted libqofono.
python3-pyqtchart depends on already blacklisted python3-pyqt5.
qt-kiosk-browser depends on already blacklisted qtwebengine.

:Detailed Notes:
ERROR: Nothing PROVIDES 'libqofono' (but meta-qt5/recipes-connectivity/libqofono/libqofonoext_git.bb DEPENDS on or otherwise requires it)
libqofono was skipped: Recipe is blacklisted: requires dbus module enabled in qtbase, which was disabled in PLAT-18268 http://caprica.lgsvl.com:8080/Errors/Details/1509141
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'libqofonoext', 'libqofono']

ERROR: Nothing PROVIDES 'python3-pyqt5' (but meta-qt5/recipes-python/pyqtchart/python3-pyqtchart_5.15.1.bb DEPENDS on or otherwise requires it)
python3-pyqt5 was skipped: Recipe is blacklisted: needs newer sip than 4.19.12 what we have in thud, This version of PyQt5 requires sip 4.19.14 or later. http://caprica.lgsvl.com:8080/Errors/Details/1509149
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'python3-pyqtchart', 'python3-pyqt5']

ERROR: Nothing PROVIDES 'qtwebengine' (but meta-qt5/recipes-qt/qt-kiosk-browser/qt-kiosk-browser_git.bb DEPENDS on or otherwise requires it)
qtwebengine was skipped: Recipe is blacklisted: We use own webruntime based on chromium
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'qt-kiosk-browser', 'qtwebengine']

:Testing Performed:
Build test done
CAT was passed

:QA Notes:
N/A

:Issues Addressed:
[PLAT-123586] CCC: ose: downgrade GPLv3 component
[PLAT-117224] Licenses GPL-3.0 and LGPL-3.0 found in OSE components
[PLAT-127791] Create meta-lg-gplv2 layer
[PLAT-128326] CCC: Introduce meta-lg-gplv2

Change-Id: I241ffb3783008740527e02e0dd9cc33692aacb9a